### ISSUE TITLE
Fossamail support

### ISSUE THREAD

**Issue by sergeevabc** [lieser/dkim_verifier#101]
Dear Philippe,
Fossamail x64 user here, the project is [somehow][1] alive and is based, I believe, on Thunderbird 38.x.
It means DKIM Verifier 1.7.0 should be working fine, right?
But no matter how hard I try, DKIM field shows blank line only.
Could you be so kind, at least, to check if it works on your side in mentioned environment?

[1]: https://href.li/?https://forum.palemoon.org/viewtopic.php?f=58&t=15761

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by lieser** [comment]
FossaMail 38.2 (I tested it with 38.2.0) should now work with version 1.7.1, which you can download from https://github.com/lieser/dkim_verifier/releases. Note that the new upcoming major release 2.0.0 will drop support for Thunderbird 38, and therefore also FossaMail 38.

PS: I know a reaction time of two weeks is not ideal, but please remember I'm working on this add-on voluntarily in my free time. And I wanted to have at least a quick look into it, before i respond.  Also, there are nicer ways to ask for an status update than writing "Err… Hello?".

**Comment by sergeevabc** [comment]
Philippe, your extension works as expected now, danke schön.

Yes, time changes things, but I’ll stay with Fossamail until its last breath, because @wolfbeast, the maintainer, despite the project was officially discontinued, still keeps eyes [open][1] and delivers [fixes][2], what I wouldn't say about Thunderbird’s [team][3], who could postpone forever until devs with vision and commitment [show][4] up.

As for your err-hello remark, indeed, there are nicer ways to ask for a status update, but you even didn’t care to let us know initially polite appeal (with “dear name” and “could you be so kind”) was received. “I’m busy, will respond in X days/weeks/months” is expected, which  takes a minute to type and establishes a friendly circuit.

[1]: https://github.com/MoonchildProductions/Pale-Moon/issues/1423#issuecomment-342856368
[2]: https://forum.palemoon.org/viewforum.php?f=58
[3]: https://bugzilla.mozilla.org/show_bug.cgi?id=1370217
[4]: https://trac.torproject.org/projects/tor/ticket/22484
