### ISSUE TITLE
Detect and warn about possibly spoofed mail headers

### ISSUE THREAD

**Issue by lieser** [lieser/dkim_verifier#102]
Try to detect possibly spoofed mail headers, there TB is not showing/using the signed header but one that was added after the signature. If this is detected, either add a waring or let the verification fail.

See http://noxxi.de/research/breaking-dkim-on-purpose-and-by-chance.html#hdr2 for some examples.

Maybe also warn if critical headers (e.g. from address) are not signed.

**Comment by ale5000-git** [comment]
Does having multiple subject lines in mails make sense?
If not I suggest to fail completely when it is detected (not just warn).

**Comment by lieser** [comment]
I don't know of a valid reason for multiple subject lines, and seems to be even a violation of the e-mail RFC (https://tools.ietf.org/html/rfc5322#page-21). Same for multiple From headers.

What will be a hard failure, or what a waring exactly is not yet decided. And probably also will not be before I look into this in detail than it gets implemented.

But at least for multiple subjects/from headers, I currently don't see a reason why it should be anything less than a hard failure, like you also suggest.

**Comment by lieser** [comment]
Added a heuristic to detect this. Simply checks that if one the the headers the RFC recommends or advices to sign is present and signed at least once, that all present headers of that type are signed.
That should be able to prevent many of this attacks of added headers.

**Comment by lieser** [comment]
Forgot to mention, a version to try this out can be downloaded from https://github.com/lieser/dkim_verifier/issues/277#issuecomment-1159783266.
