### ISSUE TITLE
Said not signed while it is

### ISSUE THREAD

**Issue by jodumont** [lieser/dkim_verifier#109]
Hi;

When I test my emailserver with your extension;  it said : Invalid (Should be signed by jodumont.com)

But when I'm testing it with [http://mail-tester.com/](http://mail-tester.com/) everything seams fine
![untitled](https://user-images.githubusercontent.com/5204724/38563910-46973b32-3cde-11e8-98f5-0e01d106d8b5.jpg)

and I also have a positive result with : [http://dkimvalidator.com/](http://dkimvalidator.com/)
> DKIM Information:
> 
> DKIM Signature
> 
> Message contains this DKIM Signature:
> DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed;
> 	d=jodumont.com; s=mail; h=Content-Type:In-Reply-To:MIME-Version:Date:
> 	Message-ID:From:To:References:Reply-To:Subject:Sender:Cc:
> 	Content-Transfer-Encoding:Content-ID:Content-Description:Resent-Date:
> 	Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID:List-Id:
> 	List-Help:List-Unsubscribe:List-Subscribe:List-Post:List-Owner:List-Archive;
> 	 bh=aoo4WWpPupdHDrO3zmeKVssuVlzFzeAv/MBCgq6usGo=; b=uYz71B2Tyno6tObZJzN3pfIFu
> 	IaA4b1joj3dTXKQObWNNEJRE49ViXjsv7eH6AOilkaFLyhJ7sfhdD8eAXnnARqf73eiw8We2oIPRC
> 	RKBAUbqAl+cM7nbGHGymkApj+iqteVv7OfxMfp2v4VP611LpvibFr+BwERpDHglQopb8k=;
> 
> http://dkimvalidator.com/
> Signature Information:
> v= Version:         1
> a= Algorithm:       rsa-sha256
> c= Method:          relaxed/relaxed
> d= Domain:          jodumont.com
> s= Selector:        mail
> q= Protocol:        dns/txt
> bh=                 aoo4WWpPupdHDrO3zmeKVssuVlzFzeAv/MBCgq6usGo=
> h= Signed Headers:  Content-Type:In-Reply-To:MIME-Version:Date:
> 	Message-ID:From:To:References:Reply-To:Subject:Sender:Cc:
> 	Content-Transfer-Encoding:Content-ID:Content-Description:Resent-Date:
> 	Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID:List-Id:
> 	List-Help:List-Unsubscribe:List-Subscribe:List-Post:List-Owner:List-Archive
> b= Data:            uYz71B2Tyno6tObZJzN3pfIFu
> 	IaA4b1joj3dTXKQObWNNEJRE49ViXjsv7eH6AOilkaFLyhJ7sfhdD8eAXnnARqf73eiw8We2oIPRC
> 	RKBAUbqAl+cM7nbGHGymkApj+iqteVv7OfxMfp2v4VP611LpvibFr+BwERpDHglQopb8k=
> Public Key DNS Lookup
> 
> Building DNS Query for mail._domainkey.jodumont.com
> Retrieved this publickey from DNS: v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHmLxY+3st8DHH9Vt+1Ue5iP06JALa80PJIIHImptnIGAVed1Qdoi8TIcq+SA5oCq6MseAN6Ab8Lf1XCv1WfggRwouTxf75xPbQg1QH8TmUrRrMaTu041Q483uZaHPSvwiH+3y+TRokDwHa69pwzY3318vSOfulynZB98J/oAq/wIDAQAB
> Validating Signature
> 
> result = pass
> Details: 

How I could update the info inside your plugins and/or make it positive also inside your plugins ?

**Comment by lieser** [comment]
As you haven't responded yet, I'm considering your question answered. If not, please reopen the issue.
