### ISSUE TITLE
When is the plugin updated in the Thunderbird "addon-site"?

### ISSUE THREAD

**Issue by wioxjk** [lieser/dkim_verifier#110]
As the title says - when does the plugin get an update on the addon.mozilla.org?
I can't see that the latest branch is actually in the "store".

**Comment by lieser** [comment]
Are you talking about the 1.7.1 version, or the 2.0.0preX/2.0.0 version?

1.7.1:
Initially didn't plan to upload it to AMO, as it is only a fix for FossaMail (which I don't know if it is using AMO). But I did upload it just now, and it is currently awaiting review.

2.0.0preX:
sadly Mozilla disabled support for a beta channel, so no new preview versions will be uploaded to AMO.

2.0.0:
I'm currently waiting for the Chinese translation to be updated. If this is finished I will upload the 2.0.0 to AMO (or in 1-2 weeks with an unfinished translation, If I do see no progress there)

**Comment by lieser** [comment]
2.0.0 was just released and is now awaiting review on AMO. Note that this may take some time. As the review for 1.7.1 was not none yet, it was canceled, and the 1.7.1 version will probably be never on AMO.
