### ISSUE TITLE
Verify fails with odd keys "rsasign: hSig has wrong length"

### ISSUE THREAD

**Issue by alevesely** [lieser/dkim_verifier#112]
The relevant code is in modules/rsasign-1.2.js:282
```js
    if (hSig.length != this.n.bitLength() / 4) {
        DKIMVerifier.log.debug("rsasign: hSig has wrong length");
        return 0;
        // throw new Error("rsasign Error: hSig has wrong length");
    }
```
That test is probably useless (it is not there in [newer versions](https://github.com/kjur/jsrsasign/releases/tag/8.0.0)) and is wrong for odd keys, because bitLength() returns the exact length in bits, not the bytes.  If the key, and hence the signature, happen to have the four most significant bits zero, `hSig.length` is the full byte length, while `bitLength() / 2` would be an odd number.
An example key (`gamma._domainkey.tana.it`) is this:
```
MIGuMA0GCSqGSIb3DQEBAQUAA4GcADCBmAKBkAtziQN+Y0LCjJBbGdAu2R6hgiJ4V
mPi9rQHZtNbVq5G6lwSU2L/eMjuMeiQNa47h8vRiZPRuOkeh4fLjBpBQSGgFnIOhn
tMrBkheNcUiDNHhGKG6E6m54UK0qO34NZ6yRAwv72oJ3UNDPj+Pg7HVaV6DehV0lg
lGlXclZoRu17WooC44YVaMbLwMN0lLozQIDAQAB

00000000  30 81 ae  SEQUENCE 1byte length's length = 0xae = 174 bytes length
                   30 0d  SEQUENCE 13 bytes length
                         06 09 OBJECT 9 bytes
                               2a  86 48 86 f7 0d 01 01 01  |0..0...*.H......|
00000010  05 00 NULL
                03 81 9c  BIT STRING 1byte length's length = 0x9c = 156 bytes
                         00 number of unused bits in the final octet of bitstring
                            30 81  98 SEQUENCE 1byte length's length = 0x98 = 152
                                      02 81 90 INTEGER 1byte length's length =
                                            = 0x90 = 144 bytes length (1148 bits)

                                               0b 73 89 03  |......0......s..|
00000020  7e 63 42 c2 8c 90 5b 19  d0 2e d9 1e a1 82 22 78  |~cB...[......."x|
...
```
That modulus is not 144*8=1152, but 1148 bits.  DER breakdown can be checked [here](https://lapo.it/asn1js/#3081AE300D06092A864886F70D010101050003819C003081980281900B7389037E6342C28C905B19D02ED91EA18222785663E2F6B40766D35B56AE46EA5C125362FF78C8EE31E89035AE3B87FF2F46264F46E3A47A1E1F2E30690504868059C83A19ED32B06485E35C5220CD1E118A1BA13A9B9E142B4A8EDF8359EB2440C2FEF6A09DD43433E3F8F83B1D5695E837A157497F8251A55DC959A11BB5ED6A280B8E1855A31B2F030DD252E8CD0203010001).

**Comment by lieser** [comment]
Thanks a lot for the very detailed bug report. I updated `rsasign-1.2.js` (and `asn1hex.js`) to the newest version (8.0.12).

As I don't have an e-mail signed with such a key, could you please test it? Thanks.
[dkim_verifier@pl.zip](https://github.com/lieser/dkim_verifier/files/1948587/dkim_verifier.pl.zip)

**Comment by alevesely** [comment]
I have installed 2.0.1pre1 (on TB 52.7.0 (64-bit)) and it now says "Valid"!

Thank you for a quick fix
