### ISSUE TITLE
Add Support for TB 68

### ISSUE THREAD

**Issue by SkateScout** [lieser/dkim_verifier#115]
Hi, with the nightly version of Thunderbird i got an error when i try to install this plugin.
I know it is beta version but maybe it can be fixed without breaking the current version.

1527190073854	addons.xpi	WARN	Invalid XPI: Error: Non-restartless extensions no longer supported (resource://gre/modules/addons/XPIInstall.jsm:646:13) JS Stack trace: loadManifestFromRDF@XPIInstall.jsm:646:13
async*loadFromRDF@XPIInstall.jsm:786:23
async*loadManifest@XPIInstall.jsm:809:21
async*loadManifest@XPIInstall.jsm:1535:28
async*init@XPIInstall.jsm:1952:13
async*getInstallForURL@XPIInstall.jsm:3731:13
async*XPIProvider[meth]@XPIProvider.jsm:3101:29
promiseCallProvider@AddonManager.jsm:228:12
async*getInstallForURL@AddonManager.jsm:1631:16
getInstallForURL@AddonManager.jsm:3359:12
onDrop@extensions.js:3473:29
async*initialize/<@extensions.js:146:5
initAddonPrefsMenu@mailWindowOverlay.js:3764:5
onpopupshowing@messenger.xul:1:1
set_open@menu.xml:52:11
onxblmouseover/<@mailWidgets.xml:2793:17
setTimeout handler*onxblmouseover@mailWidgets.xml:2791:13

**Comment by n8v8R** [comment]
same expirience on WIN 10 1709 b16299.641 trying to install v.2 in TB 62.0a1 (2018-05-28) (64-bit)

v1.7 does not work work with TB 62.0a1 (2018-05-28) (64-bit), options just producing a transparent window.

**Comment by lieser** [comment]
It will probably take quite some work to make the extension work with TB versions after 60. So although I plan to add support for versions after 60, don't expect it any time soon.

**Comment by Nothing4You** [comment]
Even though they claim next will be 63 there's 60 as stable and 64 as beta currently. You can still enable legacy extensions in 64 by setting `extensions.strictCompatibility=false`. Can you please allow using it as legacy extension on 64 beta build?

**Comment by gene-git** [comment]
I haven't tried that setting - sounds like with it all you need is the max version to be bumped maybe? 

Wondering if you have a rough timeline for compatibility with 64 beta?

thank you

g

**Comment by Nothing4You** [comment]
That's what I'm hoping for, it could be that simple for a temporary fix. Although I don't know whether that setting will make it to release considering the way they did it on firefox.
As far as I understand the documentation for creating webextensions for TB doesn't even exist yet (I was unable to find it).

**Comment by lieser** [comment]
Today I finally had a little time to look into this.

Simply setting `extensions.strictCompatibility=false` did not work for me in TB 64.0b3. TB still complained that the add-on is not compatible.

What was however somehow successful was to adapt the add-on to use the XUL overlay loader that was added in TB (see also https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63).

One thing that is not working is the preference window. So all add-on settings have to be done via TB's config editor (TB Options > Advanced > General > Config Editor). Look into the https://github.com/lieser/dkim_verifier/blob/master/defaults/preferences/prefs.js file to see a little info about the settings.

You can get the build that seems to work for me at [dkim_verifier@pl-beta.zip](https://github.com/lieser/dkim_verifier/files/2613499/dkim_verifier.pl-beta.zip). Note that I have not done any extensive testing. Please let me know if you find something else besides the options windows that is not working.

> Wondering if you have a rough timeline for compatibility with 64 beta?

No, there does not exist any timeline on when the add-on is completely compatible with TB beta.

**Comment by gene-git** [comment]
Hi - thanks for all the work you're doing - it has allowed me to remove all the message filters I was previously using to color code for dkim etc - a big thank you!

Do you plan on merging the legacy overlay loader into the released version anytime soon? The 3.0 pre snapshot from last Nov seems to have not been getting the code changes happening on the 2.0 branch.

Thanks again for the really great and highly useful addon.

**Comment by lieser** [comment]
I just released a new pre release (v3.0.0pre2) with the following changes:
- merged the changes from the 2.0.1 release into the beta branch
- fixed incompatibility with Thunderbird 66. As I do not know if it still works with TB 64/65, it now requires at least TB 66
- options GUI now works again. The GUI for the account specific options is still broken.

You can get the version from https://github.com/lieser/dkim_verifier/releases.

Briefly tested with:
- TB beta 66.0b1 (32-bit)
- TB daily 67.0a1 (2019-02-11) (32-bit)

**Comment by gene-git** [comment]
Awesome, thank you will test.

**Comment by n8v8R** [comment]
The next FF ESR branch seems to be 68 and to be released 2019-07-09. Hope that the changes in this TB extension will survive

**Comment by lieser** [comment]
I just released a new pre release (v3.0.0pre3) with the following changes:
- fixed incompatibility with Thunderbird 68

You can get the version from https://github.com/lieser/dkim_verifier/releases.

Briefly tested with:
- TB beta 66.0b2 (32-bit)
- TB daily 68.0a1 (2019-04-13) (32-bit)

**Comment by gene-git** [comment]
Assume devs already aware of this but for info for those who may not. TB have updated the guidance for addons for TB 68

https://developer.thunderbird.net/add-ons/upgrading-add-ons-for-tb68

**Comment by gene-git** [comment]
The pre-release version (3.0 pre4) breaks enigmail.
Fresh profile - add enigmail extension - all fine.
Add dkim_verifier and the account settings -> Openpgp menu is messed up in strange ways.
The error says:
File not found

The file jar:file:///opt/mozilla/x86_64/thunderbird-68.0a1.20190520/omni.ja!/chrome/messenger/content/messenger/am-enigprefs.xul cannot be found

Disabling dkim_verifier and it works fine again.

There is some odd interaction as the enigmail file actually inside the xpi is 
chrome/content/am-enigprefs.xul.

Ideas how to fix this issue ?

thanks

**Comment by gene-git** [comment]
Be nice to get this one fixed (for me for sure but probably others).
I use 3 addons - this one, cardbook and enigmail. 
At this point this bug is holding me up from using daily full time.

thanks!

**Comment by gene-git** [comment]
Any chance to stop the enigmail breakage here? I really like this addon but I cannot not use enigmail unfortunately. Do you understand how this is breaking the enigmail account settings -> openpgp menu?
TB68 is now in beta (beta 1 / build3) - unfortunately it has the idiotic persistant new profie thing- so i cannot use it unless someone has a workaround - i tried new profile, copied ImapMail and usual key flles but didnt work. 

So all my testing is on 69 daily build now.

thanks.

**Comment by gene-git** [comment]
I am disabling this for now - please post here when there's a fix for this bug, and I'll retest it again

thanks!

**Comment by lieser** [comment]
Finally found some time to look into this. The following versions should not only fix Enigmail account preferences, but also shows the ones from the DKIM verifier again:
[dkim_verifier@pl-beta.zip](https://github.com/lieser/dkim_verifier/files/3288165/dkim_verifier%40pl-beta.zip)

**Comment by gene-git** [comment]
I confirm the menu is fixed in TB 69 as of today. However that build has messed up the From/Correspondents column when there is a thread - first 'from' is empty (TB bug nothing to do with dkim-v.

Thank you very much for fixing this ... yay!!

**Comment by gene-git** [comment]
I had to install twice for some reason - perhaps as it as same version string as prior - maybe change to pre5?

**Comment by gene-git** [comment]
With today's 69 daily, the above pl-beta doesn't work - it just says 'validating' and never completes.

Error console has a ton of messages like this:
WebExtensions: Loading packed extension from /home/gene/.thunderbird/Home-8-test/extensions/dkim_verifier@pl.xpi ext-legacy.js:109
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:17

And then this :+1: 
7/3/2019, 12:00:43	DKIM_Verifier.Display	FATAL	TypeError: headerBox.emailAddresses.boxObject is undefined(chrome://dkim_verifier/content/dkim.js:672:29) JS Stack trace: setDKIMFromTooltip@dkim.js:672:29
Display_setCollapsed@dkim.js:724:4
Display_onEndHeaders/promise<@dkim.js:960:9
Display_onEndHeaders@dkim.js:976:5
onEndHeaders@msgHdrView.js:403:32
processHeaders@msgHdrView.js:508:10
loadCards/cursorRequest.onsuccess@cardbookIndexedDB.js:191:33
dkim.js:672:29
    setDKIMFromTooltip chrome://dkim_verifier/content/dkim.js:672
    Display_setCollapsed chrome://dkim_verifier/content/dkim.js:724
    promise chrome://dkim_verifier/content/dkim.js:960
    Display_onEndHeaders chrome://dkim_verifier/content/dkim.js:976
    onEndHeaders chrome://messenger/content/msgHdrView.js:403
    processHeaders chrome://messenger/content/msgHdrView.js:508
    onsuccess chrome://cardbook/content/cardbookIndexedDB.js:191

**Comment by lieser** [comment]
Thanks for reporting the issue. The new [3.0.0pre5](https://github.com/lieser/dkim_verifier/releases/tag/3.0.0pre5) version should work with the latest daily again (tested with 69.0a1 (2019-07-04) (32-bit)).

**Comment by gene-git** [comment]
Thank you - that works ok now. Will continue testing again

FYI - I'm using Linux 64 bit.

**Comment by gene-git** [comment]
I just noticed you added ability to check headers - that's awesome thank you.
2 questions.
1) The default value for use headers - what is it - yes or no? 
    is there some way to show that?
2) What happens if there is no list of trusted servers?
    Are all servers trusted?
 3) If I add a list of servers to trust -is that a space or comma separated list or what?

thank you!!

**Comment by lieser** [comment]
> I just noticed you added ability to check headers - that's awesome thank you.

You are probably talking about the account specific options? They already exist since a wile, we GUI was just broken for TB beta/daily

See also the info in the wiki: https://github.com/lieser/dkim_verifier/wiki/Account-Options

> The default value for use headers - what is it - yes or no?

It is the one specified in the normal add-ons options. The reading of the ARH is by default off

> What happens if there is no list of trusted servers?
> Are all servers trusted?

Yes, the default empty mean all servers are trusted.

> If I add a list of servers to trust -is that a space or comma separated list or what?

Space.

But in most case you probably only want to trust a single server per account, the one you download the e-mails from. The ARH for other servers (or for the server itself, if it is not aware of ARH) could be easily spoofed, as the headers are normally not signed in any way. There exist some effort to change this, but it is not supported by the add-on (see #87)

If you have any other question, please create a separate issues, to keep this about the support for TB68+

**Comment by gene-git** [comment]
Thanks - yes will do.

**Comment by d4k0** [comment]
@lieser 
Thunderbird 68 was released yesterday. Is there a schedule when a compatible version of dkim_verifier will be released?

**Comment by lieser** [comment]
There is no clear schedule, but I hope to finalize the 3.0.0 version in a few days. Note that the last [pre release 3.0.0pre5](https://github.com/lieser/dkim_verifier/releases/tag/3.0.0pre5) should already work with TB68.

**Comment by lieser** [comment]
I just released version 3.0.0, currently under review on ATN.
