### ISSUE TITLE
Warnings in console

### ISSUE THREAD

**Issue by cmq-cmq** [lieser/dkim_verifier#116]
I occasionally find notifications like this in my TB console:
"27.5.2018, 08:02:12	DKIM_Verifier.JSDNS	ERROR	Error reading Registry: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWindowsRegKey.readStringValue]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://dkim_verifier/JSDNS.jsm :: DNS_get_OS_DNSServers/interfaces< :: line 404"  data: no]
DNS_get_OS_DNSServers/interfaces<@resource://dkim_verifier/JSDNS.jsm:404:23
DNS_get_OS_DNSServers@resource://dkim_verifier/JSDNS.jsm:401:17
dnsChangeGetNameserversFromOS@resource://dkim_verifier/JSDNS.jsm:270:3
init@resource://dkim_verifier/JSDNS.jsm:207:2
@resource://dkim_verifier/JSDNS.jsm:1109:1
XPCU_moduleLambda@resource://gre/modules/XPCOMUtils.jsm:273:9
XPCU_defineLazyGetter/<.get@resource://gre/modules/XPCOMUtils.jsm:198:21
asyncJSDNS_QueryDNS/<@resource://dkim_verifier/DNSWrapper.jsm:155:42
asyncJSDNS_QueryDNS@resource://dkim_verifier/DNSWrapper.jsm:155:9
DNS_resolve@resource://dkim_verifier/DNSWrapper.jsm:90:12
getKeyFromDNS@resource://dkim_verifier/dkimKey.jsm:305:21
Key_getKey@resource://dkim_verifier/dkimKey.jsm:189:17

"
Is it an error of the plugin? Or a report on unsuccessful DKIM verification?

**Comment by lieser** [comment]
This seems to be an error, so thanks a lot for reporting it. I will try to have a closer look at it this weekend.

The error should not affect DKIM verification. It only means that the preferred DNS server can not be read from Windows, so it will use the statically configured on from the add-on settings (default Googles 8.8.8.8)

**Comment by lieser** [comment]
Sorry that this took way longer than initial thought. The error should be fixed in the upcoming 2.0.1 release.

Note that the OS DNS detection on Windows 10 still has problems. More info in #136.
