### ISSUE TITLE
Request: Load favicon from URL

### ISSUE THREAD

**Issue by kroerig** [lieser/dkim_verifier#118]
Hello,

is it possible to add a function that loads the favicon from the website if DKIM is valid. The addon ships with some built-in favicons but it would be nice to see one's own favicon, too.

Thx,

Klaus

**Comment by lieser** [comment]
It is unlikely that this will come. At least I will not add it myself (I would properly except a PR for it, as long as it is not enabled by default).

The favicons there added to allow an easy recognition of a sender, without the need to carefully read the signing domain (SDID). For this to work, the mapping between the SDID and the favicon must come from a trusted source.

Simply loading the favicon from the URL of the SDID would not result in a trusted mapping. Nothing is preventing a malicious website from using the favicon from a different site.

Note that there is an open issue to allow the user to extend the list himself (#83).

You can also always request fo new favicons being added (or add it yourself and create a PR for it). Note that E-Mail providers will not be added to the favicon list.
