### ISSUE TITLE
DNS from (W10) OS not working

### ISSUE THREAD

**Issue by n8v8R** [lieser/dkim_verifier#120]
TB 60.0b10 (64-bit) on W10 1709 b16299.579
DV 2.0.0 (`JS DNS library` | `checked/enabled Get DNS from OS`)

---

> DKIM_Verifier.Logging	DEBUG	initialized logging.jsm:101
> DKIM_Verifier.Key	DEBUG	DB initialized dkimKey.jsm:132
> DKIM_Verifier.Policy	DEBUG	DB initialized
> DKIM_Verifier.JSDNS	CONFIG	changed DNS Servers to : [{server:"9.9.9.9", alive:true}] JSDNS.jsm:314
> DKIM_Verifier.JSDNS	DEBUG	Found 5 interfaces. JSDNS.jsm:392
> DKIM_Verifier.JSDNS	DEBUG	Interface deactivated: ROOT\KDNIC\0000 JSDNS.jsm:422
> DKIM_Verifier.JSDNS	DEBUG	Interface deactivated: PCI\VEN_1969&DEV_E091&SUBSYS_10DF1462&REV_13\4&17d0621b&0&00E2 JSDNS.jsm:422
> DKIM_Verifier.JSDNS	DEBUG	Interface deactivated: PCI\VEN_168C&DEV_0034&SUBSYS_20031A56&REV_01\4&3361c84c&0&00E3 JSDNS.jsm:422
> DKIM_Verifier.JSDNS	DEBUG	Interface deactivated: {5d624f94-8850-40c3-a3fa-a4fd2080baf3}\vwifimp_wfd\5&3b22da97&0&11 JSDNS.jsm:422
> DKIM_Verifier.JSDNS	DEBUG	Interface deactivated: BTH\MS_BTHPAN\7&c70f0e4&1&3 JSDNS.jsm:422
> DKIM_Verifier.JSDNS	CONFIG	changed DNS Servers to : [{server:"9.9.9.9", alive:true}] JSDNS.jsm:279
> DKIM_Verifier.JSDNS	INFO	Resolving _dmarc.pdx.hu TXT by querying 9.9.9.9

---
`wmic nic get PNPDeviceID, NetConnectionStatus, NetEnabled`

> NetConnectionStatus  NetEnabled  PNPDeviceID
>                                  ROOT\KDNIC\0000
> 4                    FALSE       PCI\VEN_1969&DEV_E091&SUBSYS_10DF1462&REV_13\4&17D0621B&0&00E2
> 2                    TRUE        PCI\VEN_168C&DEV_0034&SUBSYS_20031A56&REV_01\4&3361C84C&0&00E3
> 4                    FALSE       BTH\MS_BTHPAN\7&C70F0E4&1&3
>                                  {5D624F94-8850-40C3-A3FA-A4FD2080BAF3}\VWIFIMP_WFD\5&3B22DA97&0&11

---
`PCI\VEN_168C&DEV_0034&SUBSYS_20031A56&REV_01\4&3361c84c&0&00E3` is apprently the enabled and connected iface. From the log it is not apparent why DV is deactivating it (for DNS resolution).

**Comment by d4k0** [comment]
Same problem here after updating to Thunderbird 60.0. When I click on an e-mail it just says "Error in the DNS resolver" in the DKIM field. Furthermore, it seems that the settings can't be accessed anymore.

**Comment by d4k0** [comment]
Ah, I missed this. Thanks!

I just found out what my problem was: I installed the 64-bit version of Thunderbird and the libunbound DLL is 32-bit. Therefore I switched to the JavaScript library and it works again.

Unfortunately, there doesn't seem to be a working 64-bit version of the DLL. The newer versions of the DNSSEC Validator add-on contain a 64-bit version (`libDANEcore-WINNT-x86_64.dll`), but it isn't compatible with Thunderbird :(.

**Comment by n8v8R** [comment]
@d4k0 

> Therefore I switched to the JavaScript library and it works again.

That is with the resolver specified in the DV settings or the `DNS server from the OS`?
Latter does not work for me, as shown in the above logs, and thus opened this issue.

---
DNSSEC is not really the scope of DV but rather complementary and thus dependend on another WX (web extention) since mozilla-core has no interest in implementing it natively (https://bugzilla.mozilla.org/show_bug.cgi?id=672600) and TB subsequently being impacted (https://bugzilla.mozilla.org/show_bug.cgi?id=1479423)

**Comment by d4k0** [comment]
I set a DNS server in the settings (which also supports DNSSEC), so it doesn't use the DNS server that is set in the OS.

For testing purposes I removed it (`Get DNS from OS` is enabled) and it now says `Error connecting to the DNS server` in the DKIM field.

**Comment by n8v8R** [comment]
@d4k0  Thanks for testing and the result confirms the issue

**Comment by n8v8R** [comment]
I would reckon that `NetConnectionStatus=’2′` (2 = connected) should be the trigger rather than `NetEnabled` considering that users may have various hardware interfaces enabled simultaniously (eth, wlan) but rather being connected only to one hardware interface at a time.

Of course then there is the potential virtual interface (e.g. VPN) being connected at the same time as the hardware interface.

Maybe this is a good hint https://www.ravichaganti.com/blog/finding-network-adapter-with-a-active-link

---
Suppose PowerShell is not ideal as perhaps not being present on every local machine?

`get-wmiobject win32_networkadapter -filter "netconnectionstatus = 2"`

---
`netsh` does not seem to expose the necessary information

**Comment by Nekotje** [comment]
i have the same problem im getting the error. "error in DNS resolver" But only on my own emailserver. i have also some gmail accounts in my thunderbird and they seems fine. When i send a email from my mail server to my gmail. it shows all green. but otherway around i get the error.

**Comment by lieser** [comment]
I could not find any way to fix the detection via registry. And I do not see myself having the time to add a completely new mechanism for the detection any time soon.

To not delay the fixing of getting the DNS servers from the OS any further, I decided to simply remove the enabled/disabled detection if all interfaces are detected as disabled (added in the upcoming 2.0.1). This however can result in the first query taking some time. The work for a proper fix will be tracked in #136. Please subscribe to that issue to get updates.

@Nekotje If you only have DNS issues with a specific account, this sounds like a different issue. Could you please create a new issue for that? Please include the complete error message as shown in the error console. See https://github.com/lieser/dkim_verifier/wiki/Debug#view-error-and-debug-messages on how to open it.
