### ISSUE TITLE
DKIM_SIGERROR_KEY_HASHNOTINCLUDED for my DKIM keys

### ISSUE THREAD

**Issue by stefangweichinger** [lieser/dkim_verifier#121]
I test your plugin and I am surprised that my DKIM key triggers "Ungültig (Falscher Hash Algorithmus im DKIM Schlüssel Record)".

Where is my mistake (I assume that it is my mistake and not one in your software ;-) )

-> 

``` 
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=oops.co.at;
	s=key2-201807-2048-1807232239; t=1533736900;
	h=from:subject:date:message-id:to:mime-version:content-type:content-transfer-encoding;
	bh=osj+MMjKmn57m9MbqK/D/gm3O4ahlXAlf/mTpG0kysA=;
	b=KTKrHYMbF90mfixFU+VI/5mgTCryuxTws6vqQdz6ULnYd3AALcVp8yUBHmYdhCRAjTqpI9
	aXj/a/SuzrnINn3PIppBmVV2UZscz2UaxaKNEoQ/zjhuNTtwEuxg89ejo53ufVLrK/uq0S
	3t5oy0CaUKpV3iyzwZZuBDZ/EBjPZ0aNC5Fh32cOe+2WF3PJRGHkVDDYZAuFOtVqWfHtsc
	EaMTRD8NSGFowiXW1D5oBEuP4uIThflrvTmy0sm5IuPCteqsgNS8jpMDxCBnBPES3Boua6
	CZT5AWG+ZONnrWF+a2GrLDA8okjMOPJ+jT9XAYvq4wy8iTA3ef9RNQuKPD0xlw==

**Comment by lieser** [comment]
It is a problem with the h-tag in your DKIM key (`h=rsa-sha256`), which is invalid. It must only contain the actual hash algorithm (`sha256`).

See also #41 and #21.

**Comment by stefangweichinger** [comment]
Sure, I already solved it 6 days ago ;-) thanks for checking anyway, and for your plugin that pointed me at that mistake.
