### ISSUE TITLE
Provide 64-bit libunbound libraries for Windows

### ISSUE THREAD

**Issue by lieser** [lieser/dkim_verifier#122]
Instead of relying on the DLLs included in the old version of DNSSEC Validator, the libunbound DLLs should be build from source in 64 and 32 bit version.

**Comment by n8v8R** [comment]
the developer of unbound been kind enough to provide the DLL

> The zip file with unbound.exe in it can also have the DLL files that have been crosscompiled.  They are in the libunbound subdirectory.
> I have put an example of the new zipfile with libunbound directory in www.nlnetlabs.nl/~wouter/unbound-1.7.4_20180814.zip
> 
> Best regards, Wouter

---
Thus tried with `libunbound-2.dll` which produced however:

> DKIM_Verifier.libunbound	DEBUG	libunboundWorker: Posting exception back to main script: Error: libunbound not correctly initialized (ub_resolve missing)   libunbound.jsm:297
> DKIM_Verifier.Verifier	ERROR	DKIM verifier internal error (DKIM_DNSERROR_UNKNOWN): libunboundWorker: Error: libunbound not correctly initialized (ub_resolve missing) (resource://dkim_verifier/helper.jsm:416:3) JS Stack trace: libunboundWorker.onmessage@libunbound.jsm:316:16   libunbound.jsm:316:16
> DKIM_Verifier.Verifier	DEBUG	Exception on DKIM-Signature 1   dkimVerifier.jsm:1247
> DKIM_Verifier.AuthVerifier	DEBUG	result not saved because DKIM result is a TEMPFAIL   AuthVerifier.jsm:344
> DKIM_Verifier.AuthVerifier	DEBUG	authResult: ({version:"2.1", dkim:[{version:"2.0", result:"TEMPFAIL", sdid:"foo.bar", auid:"@foo.bar", selector:"20171231", errorType:"DKIM_DNSERROR_UNKNOWN", res_num:20, result_str:"Error in the DNS resolver", favicon:(void 0)}]})   AuthVerifier.jsm:185

**Comment by lieser** [comment]
Thanks for asking the unbound developers for the dll and providing it.

Before the error you posted, are you getting the following error?
> FATAL	Exception in libunboundWorker: DKIM verifier internal error (DKIM_DNSERROR_UNKNOWN): libunboundWorker: Error: couldn't open library C:/workX/libunbound-2.dll: error 126 (resource://dkim_verifier/helper.jsm:416:3) JS Stack trace: libunboundWorker.onmessage@libunbound.jsm:316:16

I had to also put `libcrypto-1_1-x64.dll` and `libssl-1_1-x64.dll` from the zip in the same directory as `libunbound-2.dll` (`C:/work/` in my case). Afterwards, it worked for me (with path `C:/work/libunbound-2.dll`, and checkbox for path relative to profile dir disabled).

**Comment by n8v8R** [comment]
@lieser Got it working now after having placed those 3 *.dll into `C:\Program Files\Mozilla Thunderbird`.

Are you going to bundle those into the extension?

**Comment by lieser** [comment]
On AMO, included binary files made the review process a lot more complicated and longer. I would assume that it is currently similar on addons.thunderbird.net (ATN).

That's why currently I do not plan to bundle the dlls with the extension. If the above changes, or someone can convince me that bundling will bring a lot of value. this may change.

**Comment by SilmorSenedlen** [comment]
@d4k0 see my [comment](https://github.com/lieser/dkim_verifier/issues/170#issuecomment-533922795) about DLL's and configuration.

**Comment by lieser** [comment]
I finally found some time to create a CI for building libunbound both in 32-bit and 64-bit.

Unfortunately I currently don't have a 64-bit installation of Thunderbird for testing. Would be nice if someone could try it out and give me feedback if it works.
The build can be found at https://github.com/lieser/libunbound-builds/actions/runs/845516153.

Note that I was able to integrate everything in one dll. So there should no longer be potential issues with not finding `libcrypto`/`libssl`.

**Comment by SilmorSenedlen** [comment]
> Unfortunately I currently don't have a 64-bit installation of Thunderbird for testing. Would be nice if someone could try it out and give me feedback if it works.
It works fine.
Checked on Thunderbird 78.10.1 x64 in Windows 10 (1809) x64.

Is it need to check something specific?

**Comment by lieser** [comment]
@SilmorSenedlen Thanks a lot for the quick feed back.
And no, there is nothing special to check. Just make sure it is actually doing a DNS query, i.e. caching of DKIM keys and saving of the result should be off for the test,

**Comment by SilmorSenedlen** [comment]
> Just make sure it is actually doing a DNS query

Yep, it does.
![libunbound_test](https://user-images.githubusercontent.com/6761903/118379210-5992e400-b5e1-11eb-9197-7d56ced8303d.png)
_Use dnscrypt-proxy as system dns._

**Comment by d4k0** [comment]
I can also confirm that it works with Thunderbird 78.10.2 x64 on Windows 10 (20H2) x64.

**Comment by lieser** [comment]
Thank you both for you feedback. I have made a release for it (https://github.com/lieser/libunbound-builds/releases), and updated the instructions at https://github.com/lieser/dkim_verifier/wiki/DNS#windows-use-a-pre-build-libunbound-library
