### ISSUE TITLE
Update prefs.js to include new DNSSEC trust-anchor

### ISSUE THREAD

**Issue by mweinberg** [lieser/dkim_verifier#123]
Assuming that your software enforces DNSSEC validation, then it will not be able to validate DNS after October the 11th 2018.

Your repository contains a defaults/preferences/prefs.js file without the new DNSSEC trust-anchors:

. IN DS 19036 8 2 49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5

It should also include:

. IN DS 20326 8 2 E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D

More information can be found at: https://www.icann.org/resources/pages/ksk-rollover

**Comment by lieser** [comment]
Thanks for letting me know, but I think you overlooked the end of the line.

pref("extensions.dkim_verifier.dns.dnssec.trustAnchor", ". IN DS 19036 8 2 
49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5;. IN DS 
20326 8 2 E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D");

Currently both the new and the old key should be included, separated by ;

Note that it is also possible to change the default trust anchor via the 
preference editor of Thunderbird.

Am 15. September 2018 11:49:28 nachm. schrieb Matt Weinberg 
<notifications@github.com>:

**Comment by mweinberg** [comment]
Oops!  Sorry, I missed that.  All is well.
