### ISSUE TITLE
With multiple DKIM signatures, verifier can wrongly state from not in signing domain

### ISSUE THREAD

**Issue by counterpoint** [lieser/dkim_verifier#124]
Emails can have multiple DKIM signatures. In my case, they have one for the sender's domain and one for the mail relay service. The verifier appears to look only at the first signature in deciding whether the from email address is in the signing domain. I don't know the logic of signature ordering. The email should be flagged as correct if any of the DKIM signatures is for the from domain (and is valid).

**Comment by lieser** [comment]
The add-on should check all Signatures, it's just only showing the result 
of one. See my comment at 
https://github.com/lieser/dkim_verifier/issues/48#issuecomment-144373585 
for details.

Please have a look at the log to see what happens. Best enable debug 
logging in the advanced add-on options first.
https://github.com/lieser/dkim_verifier/wiki/Debug#view-error-and-debug-messages

**Comment by isleshocky77** [comment]
I have run into this same issue with emails being sent out from hubspot.com which are verified with my domain as well as the hubspot's.  At first I assumed hubspot was sending out broken emails; however, GMail was identifying the same message as being signed correctly. After looking further into it, I can see the emails are signed with both domains.

**Comment by lieser** [comment]
@isleshocky77 can you please enable logging and post the output of the verification? Would also be nice if you can send the affected mail as an eml file to lieser+dkim@posteo.net, but debug output is probably enough if it contains personal information you don't want to share.

**Comment by lieser** [comment]
Thanks @isleshocky77 for sending the mail and debug output a while ago. As I already said in my reply there, the issue you observed seems to be unrelated to this (both signatures failed to verify).

I will close this issue for now. If someone still has this problem, please reopen the issue (or create a new one) and provide more information. Thanks.
