### ISSUE TITLE
Unexpected return value from Verifier.parseTagValueList: [object Map]

### ISSUE THREAD

**Issue by RealityRipple** [lieser/dkim_verifier#125]
Enabled the DMARC verification and ran into an issue... namely that the tagMap variable is not an instance of Map, even though it is...

> Ignored error in parsing of DMARC record: DKIM verifier internal error (undefined): unexpected return value from Verifier.parseTagValueList: [object Map] (resource://dkim_verifier/helper.jsm:416:3) JS Stack trace: parseDMARCRecord @ dkimDMARC.jsm:327:9
> getDMARCRecord @ dkimDMARC.jsm:278:18

As far as I can tell, it can only possibly be a -1, a -2, or a Map object, and the variable spitout confirms it's a Map object... I'd like to offer a solution, but I don't have one, other than removing the type check, which is generally a bad idea.

**Comment by lieser** [comment]
Thanks a lot for reporting this. Seems like the `instanceof` operator has a problem if the variable was created in a different JavaScript code module, as the exact same check works without problems in a different place in *dkimVerifier.jsm*.

I will probably change it to a check done with `Object.prototype.toString` as described at https://javascriptweblog.wordpress.com/2011/08/08/fixing-the-javascript-typeof-operator/

**Comment by lieser** [comment]
Should be fixed in the upcoming 2.0.1
