### ISSUE TITLE
TB 63 beta

### ISSUE THREAD

**Issue by gene-git** [lieser/dkim_verifier#127]
The beta builds of 63 are now in build2.  I don’t fully understand TB status with regard to Webapps API, but according to the Firefox side [1] it might be a lot of work.

Can you share your thoughts on getting dkim_verifier to work with TB 63?

Thank  you for a nice and highly useful addon!

best

gene

[1] https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on

**Comment by lieser** [comment]
I will definitely try to update the add-on to make it work with TB versions past 60. But I currently don't know yet then I will find time to do so.

Note that there is already an open issue for this (#115), so I will close this one.
