### ISSUE TITLE
The trust-anchor of the root has changed - please update

### ISSUE THREAD

**Issue by mdavids** [lieser/dkim_verifier#128]
I wonder if the DNSSEC validation still works. 

The add-on shows a warning: "DKIM key is not signed by DNSSEC", even though it is.
(Version 2.0.0)

Perhaps related: https://www.icann.org/resources/pages/ksk-rollover

Not sure, because the new KSK is present in prefs.js:
https://github.com/lieser/dkim_verifier/blob/250bcbdf42115bea8b0b45cb3724e4bc2d4d6c06/defaults/preferences/prefs.js#L33

**Comment by lieser** [comment]
I just tried DNSSEC validation with one of the few emails I have with a signed key, and it worked for me.

Just to make sure, you are using the libunbound resolver? The default one does not support DNSSEC. Also make sure you are using a DNS server which supports DNSSEC.

If it is an error in the DNSSEC validation, it should also be a different error, and not a warning.
