### ISSUE TITLE
Thunderbird Offline Mode

### ISSUE THREAD

**Issue by AnanasPfirsichSaft** [lieser/dkim_verifier#129]
If I start in offline mode OR switch to it, the DKIM verifier states that it cannot connect to the DNS server. Even if I put Thunderbird back into online mode.

Maybe this can be fixed that the verifier starts working again when I return to online mode?

__
_Thunderbird 60.2.1 (Ubuntu Bionic [18.04LTS]) and DKIM Verifier 2.0.0_

**Comment by lieser** [comment]
Until a proper handling of the offline mode is added, you can enable the [`extensionsdkim_verifierdnsjsdnsautoresetserveralive-boolean`](https://github.com/lieser/dkim_verifier/wiki/DNS#extensionsdkim_verifierdnsjsdnsautoresetserveralive-boolean) setting as a workaround. Note that this setting is not exposed in the settings window of the add-on. You will have to change it via TB's config editor (TB Options > Advanced > General > Config Editor).

**Comment by lieser** [comment]
Note that the default JSDNS resolver uses Thunderbird for the network communication. As you are in offline mode, network communication is disabled by Thunderbird itself (connection fails with `NS_ERROR_OFFLINE (804B0010)`). This behavior can probably not be changed.

As libunbound uses the underlying OS directly for the network, it is not affected by Thunderbird's offline mode.

If you are often in offline mode, I would recommend you to enable the caching of the DKIM keys, if you haven't already.

**Comment by lieser** [comment]
Still have to actually test it but seems like the [`navigator.onLine`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) property and the [`online`](https://developer.mozilla.org/en-US/docs/Web/API/Window/online_event)/[`offline`](https://developer.mozilla.org/en-US/docs/Web/API/Window/offline_event) events could be used to implement this.

**Comment by lieser** [comment]
The addon now detects if Thunderbird is in the offline mode and if it goes back to online. This means for both DNS resolvers:
- No DNS queries are done if Thunderbird is in the offline mode
- DNS configuration is reset after Thunderbird goes back online
