### ISSUE TITLE
What if the upstream DNS does DNSSEC validation?

### ISSUE THREAD

**Issue by AnanasPfirsichSaft** [lieser/dkim_verifier#130]
I have an Unbound resolver doing the hard work in the local area network and the desktop clients use it (i.e. by systemd-resolved). Unbound checks DNSSEC signatures and blocks invalid replies with SERVFAIL (val-permissive-mode=no, ignore-cd-flag=yes).

I am unsure. But I guess it is useless to let DKIM verifier do the checks (through libunbound), if the upstream dns does it in the first place? If there is a wrong DNSSEC signature, DKIM would also fail, because Unbound gives no reply? Or is the TXT-RR fetched by DKIM verfifier independent of DNSSEC results?

**Comment by lieser** [comment]
> But I guess it is useless to let DKIM verifier do the checks (through libunbound), if the upstream dns does it in the first place?

Assuming you trust the network between the client (you PC there TB is running) and the DNS server, when using libunbound should not be necessary.

Using libunbound however has still one advantage, that is you can see in the add-on if a DKIM key was secured via DNSSEC. The JSDNS resolver is completely DNSSEC unaware, meaning it does not support the AD flag in the response of the server.

> If there is a wrong DNSSEC signature, DKIM would also fail, because Unbound gives no reply? 

Yes, if the DNS server replies with SERVFAIL, the verification will fail with a geneal DNS error ("Error connecting to the DNS server").

With the libunbound resolver, you would get a more meaningful error, "DNS result is bogus".

> Or is the TXT-RR fetched by DKIM verfifier independent of DNSSEC results?

The add-on (with default JSDNS resolver) is only requesting the TXT-RR. And it is not setting the CD (checking disabled) flag in it's request. So I would assume no DNSSEC aware server will respond with the requested TXT-RR if DNSSEC validation fails.
