### ISSUE TITLE
Dkim_verifier as Featured Addon

### ISSUE THREAD

**Issue by gene-git** [lieser/dkim_verifier#131]
What would it take to get dkim_verifier recommended as a featured addon for TB? This would hugely increase it’s visibility.

As per TB planning:

https://groups.google.com/forum/#!topic/tb-planning/RmRdfg1ZK2E

Comments?

**Comment by lieser** [comment]
> What would it take to get dkim_verifier recommended as a featured addon for TB?

The add-on should meet all the criteria mentioned in the *Criteria for Featured Extensions* section at https://github.com/thundernest/policies/blob/master/docs/featured-addons.md#criteria-for-featured-extensions.

The *Losing Featured Status* section in the same document however also mentions that *"Featured add-ons are expected to be compatible with stable and beta versions of Thunderbird"*. Currently the add-on is not completely working in TB beta. 

So I'm unsure if the add-on is entitled to the features status.

Note that I currently do not plan to nominate the add-on myself. But if you (or another user) wants to nominate it, feel free to do so.

**Comment by gene-git** [comment]
As soon as its compatible with the beta be happy to nominate.

thanks!

**Comment by lieser** [comment]
Note that I just releases version 3.0.0 which is compatible with TB68 (currently still under review).

I don't think keeping this issue open here makes much sense. If anyone wants to nominate the add-on feel free to just do it, no need to keep and issue here around for it.

**Comment by gene-git** [comment]
Nominated - also pointed out that version 3 is pending approval and does satisfy the requirements of being compatible with current ESR version.

Thanks,

**Comment by gene-git** [comment]
Its now a featured add-on ...

**Comment by ale5000-git** [comment]
@gene-git
I don't see the "Recommended" label.
Why?

**Comment by gene-git** [comment]
@ale5000-git I honestly don't understand your question. 
As required by Thundbird, I emailed atn-featured@thunderbird.topicbox.com for it to be added to featured list.
In the email i said "I strongly recommend".
That's all i did.
Strangely today when I look at the Featured list it's no longer scrollable and and its one page only and dkim-v is not listed.

Anyway, if there's more to do perhaps you can add the "recommended" label as I have no idea what that is.

**Comment by ale5000-git** [comment]
I mean that this label is missing on DKIM Verifier:
![Label](https://user-images.githubusercontent.com/15793015/64187536-0dd1f280-ce71-11e9-87aa-d3ad039e314c.png)

**Comment by gene-git** [comment]
Yes - It's not there - may I suggest you (and others) likewise recommend this to be featured. Perhaps it is not yet approved without additional recommendations. 

Send email as I did in above comment.
