### ISSUE TITLE
When the AddOn is active, Followup-To headers get malformed

### ISSUE THREAD

**Issue by arnowelzel** [lieser/dkim_verifier#132]
When the AddOn is active and you try to send a news post with a Followup-To header, the header gets an extra " <>" added, which makes it invalid and the post will not be accepted by the NNTP server.

Expected:

Followup-To:  groupname.example

Actual behaviour:

Followup-To:  groupname.example <>

Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1510191

**Comment by lieser** [comment]
I tried to reproduce it, but was unable to do so.

I'm also surprised that you get this behavior only with this add-on. The add-on is not doing anything regarding message creation/sending.

I used the following:
Thunderbird: 60.3.1 (32-bit)
NNTP server: `news.mozilla.org`
Newsgroup: `mozilla.test`
Followup-To: `mozilla.test`

**Comment by arnowelzel** [comment]
Strange. Maybe it's a side effect with Enigmail, which I also had installed. But as soon as I disable DKIM verifier, the headers are OK.

**Comment by cnleo** [comment]
@arnowelzel Maybe obtained the problem from this setting.
In the settings of Enigmail there is an entry that is suspicious.
Enigmail Settings --> Advanced/Extended
Checkbox >> Use the characters "<" and ">" to identify email addresses

**Comment by lieser** [comment]
Is anyone still having problems with this in TB78? Otherwise I would like to close this.
