### ISSUE TITLE
DKIM verification fail with DKIM_SIGERROR_KEY_NOTEMAILKEY

### ISSUE THREAD

**Issue by dinacel** [lieser/dkim_verifier#134]
Hi,
when I define my DKIM DNS record with "s=*" (service type), the verification fails with "DKIM key is not an e-mail key". I don't really understand because the "\*" wildcard should matches all service types. It works as intented if I remove the "s" parameter.
 https://github.com/lieser/dkim_verifier/blob/250bcbdf42115bea8b0b45cb3724e4bc2d4d6c06/modules/dkimVerifier.jsm#L832

**Comment by lieser** [comment]
Thanks a lot for reporting this issue. Should be fixed in the upcoming 2.0.1
