### ISSUE TITLE
Auth results from google mails not correctly read

### ISSUE THREAD

**Issue by bonanza123** [lieser/dkim_verifier#135]
For most of the mails coming in via google (gmail or one of google services itself), the A-R does not seem to be read correctly.

E.g. for the header
```
Authentication-Results: mail-in-2.itc.mail.com; spf=Pass smtp.mailfrom=user@gmail.com; dkim=pass (signature verified) header.i=@gmail.com
```

The plugin in thunderbird says: No Signature

Here some output from the log in debug mode:
```
16:43:51.617 1/12/2019, 16:43:51	DKIM_Verifier.AuthVerifier	ERROR	Ignoring error in parsing of ARH: Error: Parsing error (resource://dkim_verifier/ARHParser.jsm:292:9) JS Stack trace: match@ARHParser.jsm:292:9
parseResinfo@ARHParser.jsm:201:15
_ARHParser_parse@ARHParser.jsm:170:21
getARHResult@AuthVerifier.jsm:252:10
_authVerifier_verify/promise<@AuthVerifier.jsm:138:20
 1 AuthVerifier.jsm:254
```

**Comment by lieser** [comment]
Thanks a lot for reporting this issue. The problem was the casing in `spf=Pass` (the ARH RFC only specifies lower case results, but old SPF RFCs used mixed case).

The upcoming 2.0.1 will also accept the mixed case results specified in the old SPF RFC.

**Comment by bonanza123** [comment]
@lieser thanks so much for the swift fix. Is there an ETA for the 2.0.1 release?

**Comment by lieser** [comment]
I'm currently planning to release it in a few days latest. Note that review on ATN will probably take at least a few days, if not weeks, so automatic update may take more time.

But you will be able to manually download it here on GitHub before that already. You can watch the repository for releases to get a notification.
