### ISSUE TITLE
2.0.1 release missing on https://addons.thunderbird.net

### ISSUE THREAD

**Issue by beerisgood** [lieser/dkim_verifier#138]
Latest listed version is 2.0.0
https://addons.thunderbird.net/en/thunderbird/addon/dkim-verifier/

**Comment by lieser** [comment]
The 2.0.1 version is currently still under review on ATN. That is why it 
does not show up.

Am 30. Januar 2019 10:37:15 vorm. schrieb beerisgood 
<notifications@github.com>:

**Comment by beerisgood** [comment]
Okay

**Comment by lieser** [comment]
The 2.0.1 version is now also available on ATN.

**Comment by beerisgood** [comment]
And update in Thunderbird works.
Thanks!
