### ISSUE TITLE
Invalid format of DKIM key

### ISSUE THREAD

**Issue by mklemme1** [lieser/dkim_verifier#139]
Hallo

We moved from an Ubuntu 14.4 server with Postfix 2.11.0 to Ubuntu 16.04 with Postfix 3.3.0.
On mails sent from the new systems, dkim_verifier reports "Ungültig (DKIM Schlüssel ist falsch formatiert)" ("Invalid (DKIM key is formatted wrong)").

Other systems report the DKIM signature as valid.
I see that older emails have a "b" (body+header hash) element, where we now have a "bh" (body hash)
Could this be an issue on the side of dkim_verifier?

Thanks
  Michael 

> Return-path: <XXXXXXXXXXXXXXXXX@adfc-hessen.de>
Delivery-date: Sun, 24 Feb 2019 19:28:01 +0100
Received: from mi025.mc1.hosteurope.de ([80.237.138.230])
	by wp425.webpack.hosteurope.de running ExIM with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
	id 1gxyVN-0000JR-Bg; Sun, 24 Feb 2019 19:28:01 +0100
Received: from adfc-hessen-server.de ([87.230.17.108])
	by mx0.webpack.hosteurope.de (mi025.mc1.hosteurope.de) with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	id 1gxyVM-0004Zg-Tq
	for XXXXXXXXXXXXX@XXXXX.de; Sun, 24 Feb 2019 19:28:01 +0100
Received: from [192.168.178.20] (ip-88-153-206-217.hsi04.unitymediagroup.de [88.153.206.217])
	by adfc-hessen-server.de (Postfix) with ESMTPSA id 626D6BAD1E
	for <XXXXXXXXXXXXX@XXXXX.de>; Sun, 24 Feb 2019 19:28:00 +0100 (CET)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=adfc-hessen.de;
	s=default; t=1551032880;
	bh=OBwXnhY3G56tKHVI5fnSkwuQox16wqRUicrDusJIi2s=; l=198;
	h=To:From:Subject;
	b=usDTOSL016vM/DqMOLBclMhACPSC7vpVnrTOZB39zDZReGgm46JECnxqtv7kB/a4s
	 Odb/yTanyhAkWGD5/xeg13Xcz4RXTDJXEYWu13EtPMMzc8kLDRjOrnksuhrAjkeauq
	 NzSEn2z81FZfroB1e5ixGvb2C2wIVez1jomZ6/wQ=
Authentication-Results: adfc-hessen-server.de;
        spf=pass (sender IP is 88.153.206.217) smtp.mailfrom=yyyyyyy.yyyy@adfc-hessen.de smtp.helo=[192.168.178.20]
Received-SPF: pass (adfc-hessen-server.de: connection is authenticated)

**Comment by lieser** [comment]
It is not a problem with the signature, but the DKIM key.

The key `default._domainkey.adfc-hessen.de` used for signing looks like the following:
`v=DKIM1; p=DKIM1; p=MIGfM...;`
The DKIM key contains two times the `p=` tag (public-key data). This is not allowed. Delete the ` p=DKIM1; ` part and it should work.

You can also first test this localy without changing the DNS.

1. Enable [caching of the DKIM keys](https://github.com/lieser/dkim_verifier/wiki/Options#caching-of-the-dkim-keys)
2. Try to verify the email (should fail)
3. Go to the options an manually change the key (with SDID `adfc-hessen.de` and selector `default`)
4. Reverify the email. Verification should now work.

It would also be good to enable [Show detailed error reasons](https://github.com/lieser/dkim_verifier/wiki/Options#show-detailed-error-reasons) and debugging in the advanced options, giving you more information about what exactly the add-on complains about.

> I see that older emails have a "b" (body+header hash) element, where we now have a "bh" (body hash)

The signature you posted contains both the `bh=` tag (the hash of the canonicalized body) and the `b=` tag (the signature). Both tags are required in all DKIM signatures.

**Comment by mklemme1** [comment]
Thanks for explaining.
I could fix the DKIM signatures in DNS.
