### ISSUE TITLE
RFC 8301: Cryptographic Algorithm and Key Usage Update

### ISSUE THREAD

**Issue by lieser** [lieser/dkim_verifier#141]
Update algorithm and key usage according to [RFC 8301](https://tools.ietf.org/html/rfc8301):
- "rsa-sha1 MUST NOT be used for signing or verifying"
- "Signers SHOULD use RSA keys of at least 2048 bits"
- "Verifiers MUST NOT consider signatures using RSA keys of less than 1024 bits as valid signatures."
  - add-on is currently only warning if lower than 1024

**Comment by lieser** [comment]
Added in 33dec5564be0801719a115349d0e9ec48e0d2e3c. As there still seems to be quite a lot of signers using rsa-sha1, usage of it is for now only treated as a warning (can be changed in settings)

**Comment by ale5000-git** [comment]
Most DKIM are currently less than 2048 bits (at least in Italy), usually 1024 bits, could you please add an option to allow to disable this warning (at least until most mail servers are updated)?

Otherwise in most mails I see the gold color and I can't imediately distinguish a more serious problem (like the use of sha1) without place the mouse over it.

**Comment by lieser** [comment]
The new pre-release [2.1.0pre2](https://github.com/lieser/dkim_verifier/releases/tag/2.1.0pre2) contains a hidden preference `extensions.dkim_verifier.error.algorithm.rsa.weakKeyLength.treatAs` for this.
- `0`: error
- `1`: warning (default)
- `2`: ignore

**Comment by ale5000-git** [comment]
Thanks.

**Comment by blakerwry** [comment]
While above it is written that "add-on is currently only warning if lower than 1024", add-on version 2.1.0 is actually presenting a warning when the key size is equal to 1024 (not just lower than). By my reading of RFC 8301:
"Signers MUST use RSA keys of at least 1024 bits..."
"Signers SHOULD use RSA keys of at least 2048 bits."
"Verifiers MUST be able to validate signatures with keys ranging from 1024 bits to 4096 bits"
"Verifiers MUST NOT consider signatures using RSA keys of less than 1024 bits as valid signatures."

The most common DKIM signatures that I encounter are currently using 1024 bit keys. The add-on presents these messages with a warning/caution while other DKIM validators (OpenDKIM, Yahoo, Gmail, etc) treat these messages as successfully authenticated. 

I feel DKIM Verifier's treatment of messages with a 1024 bit key is self-defeating and I cannot recommend using software that does not validate messages in a manner consistent with industry standards. I believe that 1024 bit keys should still be seen as trusted (without warning) by the DKIM Verifier add-on until an RFC is released indicating that 1024 bit keys should no longer be trusted. At that time, a warning or error would then be appropriate.

**Comment by ale5000-git** [comment]
@blakerwry: It validate 1024 bit keys, it just show a warning (but validation still pass).
And there is an hidden option to remove the warning: `extensions.dkim_verifier.error.algorithm.rsa.weakKeyLength.treatAs`

Still I think that adding this option also in the UI would be better.

**Comment by blakerwry** [comment]
I don't feel the current configuration option is acceptable as this seems to lump 1024 bit keys (which RFC 8301 says "Verifiers MUST be able to validate") into the same bucket as 512 bit and lower keys (which RFC 8301 says "Verifiers MUST NOT consider signatures using RSA keys of less than 1024 bits as valid").

My belief is that the DKIM Verifier add-on v2.1.0 has not correctly implemented RFC 8301 and does not follow industry norms (with respect to key length). I would like to be able to recommend this add-on to friends and staff, but cannot do so while the add-on presents a warning with the most common DKIM signatures used by domains today (1024 bit, rsa-sha256).

**Comment by ale5000-git** [comment]
It is treated differently, with 512 bit it give an error (in red) instead of a simple warning.

**Comment by lieser** [comment]
> While above it is written that "add-on is currently only warning if lower than 1024", add-on version 2.1.0 is actually presenting a warning when the key size is equal to 1024 (not just lower than).

"current" refereed here to version 2.0.0.

> The most common DKIM signatures that I encounter are currently using 1024 bit keys. The add-on presents these messages with a warning/caution while other DKIM validators (OpenDKIM, Yahoo, Gmail, etc) treat these messages as successfully authenticated.

The add-on also considers this e-mails as successfully authenticated. It only additionally indicates via warnings that the signer should use a bigger key length.

In general the warnings are meant to indicate to the end user that he should have a closer look. Depending on the warning, he may not want to trust this signature.
The warnings is a concept not mentioned in the RFC's, and also not used by any other verifiers as far as I know. But as the add-on is a verifier which results are meant to be viewed by end users (unlike most other verifiers), I believe them to be a valuable addition.

I admit the current wording of the warning `Signature is insecure (key size too small)` is probably not good. I wanted to simply reuse the already existing translations for it, which was a bad idea.

I will probably change it something like `DKIM key is weak`.  Better proposals welcomed.

> I feel DKIM Verifier's treatment of messages with a 1024 bit key is self-defeating and I cannot recommend using software that does not validate messages in a manner consistent with industry standards. 

Like you also mentioned, the RFC 8301 defines 3 ranges of key:
1. key length < 1024 (MUST not be used by signers, MUST NOT be considered valid by verifiers)
2. 1024 <= key length < 2048 (SHOULD not be used by signers)
3. 2048 < key length

And from my perspective the add-on is doing exactly that the RFC 8301 is intending:
1. failing if key is smaller than 1024 bits
2. validating if key is between 1024 and 2048 bits, but discouraging its use by adding a warning (as signers SHOULD use bigger ones)
3. validating if key is at least 2048 bits long without a warning

> I believe that 1024 bit keys should still be seen as trusted (without warning) by the DKIM Verifier add-on until an RFC is released indicating that 1024 bit keys should no longer be trusted. At that time, a warning or error would then be appropriate.

Are you referring to the fact that the RFC 8001 is still only in the proposed state?

My idea was for this add-on to become an early adopter for the RFC. Especially because it has, unlike other verifiers only reporting success or failure, the ability to indicate a possible problem to a technically correct signature. 
So it can bring awareness to the fact that an e-mail server should update it's key to a bigger one, without directly letting the signature fail completely.

The question is whether it was a good idea to directly make the warning the default, and not just first add it as an opt-in.
And not at least exposing the setting to disable it in the advanced GUI options was definitely an overlook that should be fixed.

> I don't feel the current configuration option is acceptable as this seems to lump 1024 bit keys (which RFC 8301 says "Verifiers MUST be able to validate") into the same bucket as 512 bit and lower keys (which RFC 8301 says "Verifiers MUST NOT consider signatures using RSA keys of less than 1024 bits as valid").

This is not the case. In 2.1.0, signature with a key size smaller than 1024 are always considered invalid, regardless of the `extensions.dkim_verifier.error.algorithm.rsa.weakKeyLength.treatAs` setting.

> My belief is that the DKIM Verifier add-on v2.1.0 has not correctly implemented RFC 8301 and does not follow industry norms (with respect to key length).

As already mentioned above, I believe that the add-on does follow the RFC 8301.

But I admit that the add-on is probably not following the industry norm here. But not because it is violating an RFC, but because the RFC 8301 is not yet considered the industry norm. Which I hope will change as soon as possible.

> with the most common DKIM signatures used by domains today (1024 bit, rsa-sha256)

The hope with the warning in the add-on is to have at least a small impact on signers to start using keys with at least 2048 bit. And in this way increasing the security of the DKIM signatures used.

**Comment by blakerwry** [comment]
I appreciate the thorough response Philippe. My concern is that uses are presented with a warning/caution when they encounter an email message signed with the most popular DKIM key size. Regardless of your intention, this signals to the user that he or she cannot trust that the message is genuine, when the opposite is actually true (the message is valid and passed all DKIM/SPF/DMARC checks consistent with common practices). 

I see now that I was mistaken about 512 bit keys and am glad that they are displayed as failing DKIM checks regardless of the weakKeyLength configuration setting.

I feel that the current warning and color coding does a disservice to users receiving messages that are signed with a 1024 bit key; it lumps these messages into a category along side messages that have significantly worse problems. I would suggest that messages that pass DKIM validation, but are signed with a 1024 bit key be color coded in green. If desired, a small indicator of some sort could still be present to indicate they key size. I agree that the industry should be moving towards 2048 bit keys, but it is not there now and attempts to be so far ahead of the curve may actually hinder your goal.

**Comment by ale5000-git** [comment]
@lieser: From my perspective I would like too much to have more detailed warnings/errors.

My suggestions (words aren't the same they are only to get an idea):
- Weak key => weak key of 1024
- Signed by different domain => Signed by different domain: domainname.com

Also another case, when server is missing dkim key on the dns server then the warning of "signed by different domain" doesn't appear, for me it is important because there can be variant:
- Case 1: Signed by the same domain but missing dkim key on the dns server, possible temporary server issue but legitimate mail;
- Case 2: Signed by a different domain and missing dkim key on the dns server, possible fake mail with missing dkim key message masking it.

**Comment by lieser** [comment]
@ale5000-git Thanks for the input, but I don't see how this relates to the things discussed here. Please create a separate issue for for this.

**Comment by lieser** [comment]
@blakerwry 

> I would suggest that messages that pass DKIM validation, but are signed with a 1024 bit key be color coded in green.

This would mean no warning is added anymore for a weak key, as the coloring does not depend on the kind of warning.
This is already possible via the setting. I'm also currently thinking about making this the default again (together with #174). At least for some time, until bigger keys are more common.

> If desired, a small indicator of some sort could still be present to indicate they key size.

Note that there is a related feature request for this: #160

**Comment by blakerwry** [comment]
> I'm also currently thinking about making this the default again

I appreciate the consideration. Given the frequency of encountering 1024 bit keys in daily use (I receive them more than any other key size) I think that would be ideal until either the industry moves forward or the RFCs indicate 1024 bit keys are no longer valid.

**Comment by lieser** [comment]
Note that option about weak key will be exposed in 2.2.0/3.1.0 and default changed to ignore. Warning is also reworded.
