### ISSUE TITLE
RFC 8463: add new signing algorithm Ed25519-SHA256

### ISSUE THREAD

**Issue by lieser** [lieser/dkim_verifier#142]
Add support for new signing algorithm Ed25519-SHA256 added in [RFC 8463](https://tools.ietf.org/html/rfc8463)

**Comment by gene-git** [comment]
Great thanks - and Sorry I dont have sample as was from kernel mail list which I regularly clear. First time that I noticed ecc only.

**Comment by lieser** [comment]
Support for Ed25519-SHA256 was added, and will be included in the upcoming 4.2.0 release.

**Comment by gene-git** [comment]
That's excellent thank you so much
