### ISSUE TITLE
Opening attached .eml files in IMAP account results in internal error (< TB 78)

### ISSUE THREAD

**Issue by ale5000-git** [lieser/dkim_verifier#144]
In Italy there is PEC ([certified mail](https://en.wikipedia.org/wiki/Certified_email) with legal validity) where the real message is an eml attachment of the main message.
When I open the eml attachment that is inside the received mail I get "DKIM: Internal error".

Instead if I first export the mail as eml, then open it and then open the eml attacchment I do not get the "DKIM: Internal error".

I have sent you one sample.

**Comment by lieser** [comment]
For some reason the email sample you send me does not show any content if opened in Thunderbird.

But your probably run into a known bug: verifying the DKIM signature of an attached .eml file by opening it does not work in IMAP accounts. It only work in POP/local accounts. See also #51.

**Comment by lieser** [comment]
Closing this as I don't plan to still fix this for the 3.x version of the add-on. Support for external massages in newer versions is tracked in #216.
