### ISSUE TITLE
SPF and DMARC check in addition of DKIM verification

### ISSUE THREAD

**Issue by ale5000-git** [lieser/dkim_verifier#146]
Please add an option to verify and see `SPF: pass` `DMARC: pass` also when the add-on verify the DKIM signature.

**Comment by lieser** [comment]
The add-on currently does not do any client side SPF or DMARC verification. There is currently also no plan to add this (some work on SPF was started a long time ago, but was never finished and should be considered abandoned).

What the add-on already supports is reading Authentication-Results header (ARH) of a verification done on the server side (Note that not all servers add this header). Besides DKIM, this includes also SPF and DMARC.
This can be enabled in the general add-ons options: https://github.com/lieser/dkim_verifier/wiki/Options#read-authentication-results-header.

If you have already enabled reading of the ARH, but still want to let the add-on do a separate DKIM verification, you can [disable that the ARH result replaces the add-ons verification](https://github.com/lieser/dkim_verifier/wiki/Options#reading-the-authentication-results-header-replaces-the-add-ons-verification) in the advanced options.
