### ISSUE TITLE
Does it remove revoked keys from cache?

### ISSUE THREAD

**Issue by ale5000-git** [lieser/dkim_verifier#153]
When it see a revoked key does it remove the key from cache?

Ref: https://mail.mozilla.org/pipermail/tb-planning/2011-February/000821.html

**Comment by lieser** [comment]
If you have selected the option `Store DKIM keys`, no further DNS lockups will be made for keys already cached. So unless you manually trigger a key update the add-on will not notice that the key got revoked.

If you have selected `Store DKIM keys and compare them with the current key`, and a previously seen key gets revoked, the verification will fail with `Stored DKIM key is different from the current one`.  
The stored key will **not** be automatically be deleted.

**Comment by ale5000-git** [comment]
I have selected `Store DKIM keys and compare them with the current key`, I think the best way would be to differentiate.

If the old record is removed keep the old key in cache and use it instead if the old record is kept but empty delete the key in cache since the key may be compromized and it may have been used by spammers.

**Comment by lieser** [comment]
Explicit revocation of keys seems to be rarely used, if at all. Mostly the DKIM record gets just deleted. So I don't see a benefit of complicated the code for this.

Do you have any example of the key revocation being actually used because of compromised keys?

Also note the following from the RFC:
>      INFORMATIVE NOTE: A key may also be revoked as described below.
>      The distinction between revoking and removing a key selector
>      record is subtle.  When phasing out keys as described above, a
>      signing domain would probably simply remove the key record after
>      the transition period.  However, a signing domain could elect to
>      revoke the key (but maintain the key record) for a further period.
>      There is no defined semantic difference between a revoked key and
>      a removed key.

So as far as I can tell the RFC itself does not specify a different meaning between removed and revoked key.

**Comment by lieser** [comment]
As you haven't responded yet, I will consider your questions to be answered. If not, please reopen.
