### ISSUE TITLE
DKIM sign policy - Author Domain Signing Practices (ADSP)

### ISSUE THREAD

**Issue by ale5000-git** [lieser/dkim_verifier#155]
Does the plugin support ADSP (Author Domain Signing Policy) `_adsp._domainkey.domain`?

It specify whether the domain sign all mails or only some of them and what to do with the one not signed.

More info:
http://wiki.whyaskwhy.org/Email/OpenDKIM
https://tools.ietf.org/html/rfc5617

**Comment by lieser** [comment]
No, and there are currently no plans on adding it. when I was initially thinking about adding it, the RFC was already marked as historic, and as far as I could tell not widely used. That is why I chose to implement the DMARC heuristic instead (https://github.com/lieser/dkim_verifier/wiki/Options#use-dmarc-to-heuristically-determine-if-an-e-mail-should-be-signed).

Pull reuqests to add this are of course always welcomed.

**Comment by andreasschulze** [comment]
I suggest to not implement any RFC 5617 related functionality. [RFC 5617 was moved 2013 to historic](https://datatracker.ietf.org/doc/status-change-adsp-rfc5617-to-historic/) for good reasons.

**Comment by lieser** [comment]
I don't think ADSP is currently used much, and as the RFC is marked as historic, I expect the usage to get even lower over time.

So I don't think it makes much sense to spent any time on this. Even if I liked that ADSP allows to explicitly state that it should be DKIM signed, which DMARC lacks (it only requires DKIM **or** SPF).
I will therefore close this feature request.
