### ISSUE TITLE
createElement -> createXULElement required as of Thunderbird nightly 2019-05-24

### ISSUE THREAD

**Issue by jikamens** [lieser/dkim_verifier#156]
FYI, as of the 2019-05-24 Thunderbird nightly build, you can't use `document.createElement` to create XUL elements, you have to use `document.createXULElement`. If you use `document.createElement`, Thunderbird crashes.

**Comment by lieser** [comment]
Thanks for letting me know. A new pre-release can be found at https://github.com/lieser/dkim_verifier/releases/tag/3.0.0pre4
