### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by ale5000-git** [lieser/dkim_verifier#157]
- Banca Mediolanum - `bmed.news@bancamediolanum.it` OK
- UBI Banca - `noreply@info.ubibanca.it` (signed by info.ubibanca.it) OK
- UBI Banca - `QuiUBImail@ubibanca.it` (unfortunately not signed) OK
- TIM Business - `info@timbusinessmail.it` OK

**Comment by lieser** [comment]
Thanks again for the new domains. [2.1.0pre2](https://github.com/lieser/dkim_verifier/releases/tag/2.1.0pre2) includes updated sign rules and favicons.

I did not include `info@timbusinessmail.it`. Reason is I could not find any publicly available association between the domains `timbusinessmail.it` and `timbusiness.it` (e.g. via whois https://web-whois.nic.it/). I was also unsure if customers can potentially get a e-mail address from the domain `timbusinessmail.it`

If you find more domains that you would like to have added, please reuse this issue if the final 2.1.0 is not yet released. Thanks.

**Comment by ale5000-git** [comment]
@lieser
They don't publish their mails because they don't want to receive mail from users but I have sent you the mail that you got from them when you are subscribed to their newsletter.

**Comment by ale5000-git** [comment]
- `no-reply@yelp.com` and `no-reply@mail.yelp.com` (both signed by yelp.com) => https://yelp.com/favicon.ico
- `italoimpresa@news.italotreno.it` (signed by news.italotreno.it) = https://www.italotreno.it/Content/favicon/favicon.ico
- `notice-25637753@noip.com`, old emails were signed by no-ip.com but new mails are signed by noip.com, need to add icon also to it.

**Comment by mortenn** [comment]
`news.ikeafamily.no` signs emails from `newsletter@news.ikeafamily.no` => https://www.ikea.com/ext/ikeagateway/statics/favicon-16x16.png / https://www.ikea.com/ext/ikeagateway/statics/apple-touch-icon.png

**Comment by mortenn** [comment]
`efaktura.no` signs emails from `varsel@efaktura.no` => https://www.efaktura.no/Style Library/Efaktura/images/favicon.png

**Comment by mortenn** [comment]
`rhbank.no` signs emails from `betalingsformidling@rhbank.no` and `forsikring.kundesenter@rhbank.no` => https://www.sparebank1.no/etc/designs/sb1/nettsider/favicon.ico
`sparebank1.no` signs emails from `forsikring.privat@sparebank1.no` - same icon as rhbank.no (rhbank is part of sparebank1)

**Comment by ale5000-git** [comment]
Google add DKIM signature also to their notifications of unexistent addresses, so it would be nice to display Google icon also on them: `Mail Delivery Subsystem <mailer-daemon@googlemail.com>` (signed by googlemail.com)

**Comment by lieser** [comment]
Thanks a lot to both of you again for the additional domain. But I will probably not have time to look at it and add them before next week.

@ale5000-git No, adding single address is currently not possible. And I will not add favicons for domains used by e-mail providers. More about this at #107.

**Comment by ale5000-git** [comment]
- `comunicazioni@staff.aruba.it` (signed aruba.it) => http://www.aruba.it/favicon.ico
The icon should be visible only for the `staff.aruba.it` subdomain.

**Comment by ale5000-git** [comment]
`noreply@activesearchresults.com` (signed by activesearchresults.com) => https://www.activesearchresults.com/favicon.ico
`info@kycsafe.com` (sygned by kycsafe.com) => https://kycsafe.com/favicon.ico
`news@buyon.com` (signed by buyon.com) => https://www.buyon.it/favicon.ico
American Consumer Opinion - `aparksint@acop.com` (signed by acop.com) => https://acop.com/favicon.ico

**Comment by ale5000-git** [comment]
New rule:
`noreply@wetransfer.com` (signed by email.wetransfer.com) - this is unusual but they do it like this although I have seen also mails signed by the base domain

**Comment by lieser** [comment]
Sorry for the late reply. Finally had some time to take a closer look at the domains. Thanks to both of you again for them, and your patience.

The new [pre release 2.1.0pre3](https://github.com/lieser/dkim_verifier/releases/tag/2.1.0pre3) contains the following new domains from your suggestions:

Added/changed (unless specified both sign rule and favicon):
- `timbusinessmail.it`
- `yelp.com`
- `news.italotreno.it`
- `noip.com`
- `news.ikeafamily.no`
- `efaktura.no`
- `rhbank.no`/`sparebank1.no`
- `gelsh.it`
- `activesearchresults.com`
- `kycsafe.com`
- `buyon.com`
- `acop.com`
- `r.grouponmail.it`
- `news.pimkie.com`
- `email.decathlon.it` (no favicon, as it is an animated gif)
- `poliambulatoriovalturio.it`
- `doveconviene.it`
- sign rule `noreply@wetransfer.com`
- sign rule `sourceforge.net`
- `infocert.it` (sign rule also allows unsigned mails)
- `generali.com` (sign rule also allows unsigned mails)
- `engieperte.it`
- `spotify.com`
- `dhl.com`
- `nexway.com`
- changed sign rule for `sda.it` to also allow unsigned mails

Not added:
- favicon for `staff.aruba.it` (needs #107, as currently only distinguishing on signing domain can be done)

**Comment by ale5000-git** [comment]
Sorry for not replying for some time but I was busy and I'm still busy currently.

- email@mail.onedrive.com (signed by mail.onedrive.com) => https://p.sfx.ms/images/favicon.ico
- no-reply@notifications.skype.com (signed by notifications.skype.com) => https://secure.skypeassets.com/apollo/2.1.1423/images/icons/favicon.ico

**Comment by ale5000-git** [comment]
email.decathlon.it (it is an animated gif): Chrome support it also if it is a gif, if you need as ico you can use this to convert => https://www.docspal.com/it/convertire/gif-in-ico

**Comment by ale5000-git** [comment]
By verifying some mails I have noticed the there is a problem with the rule of `nexway.com` because unfortunately there are 2 cases of mails:
- `noreply@nexway.com` (signed by nexway.com)
- `kaspersky_it@nexway.com` (signed by zendesk.com, unrelated domain)

**Comment by lieser** [comment]
Thanks a gain for the domains. They there added to the 2.1.0 version:
- `mail.onedrive.com`
- `notifications.skype.com`
- `elfispa.it`
- `crm.bticino.it`
- `monsterinsights.com`
- `mprogetti.com` (no favicon, as it (http://www.mprogetti.com/favicon.png) looks broken to me)
- `altroconsumo.it`/`noreply.altroconsumo.it`
- `ford.com`
- `mail.fatturecloud.it`
- `services.telepass.it`
- `soltechonline.com`
- `culligan.it`
- `kaspersky_it@nexway.com` will no longer require SDID `nexway.com`

As the 2.1.0 version is now finally released, please create a new issue for further updates of the rules.
