### ISSUE TITLE
hu locale

### ISSUE THREAD

**Issue by ovari** [lieser/dkim_verifier#164]
@lieser would you please accept the https://github.com/lieser/dkim_verifier/pull/161 and https://github.com/lieser/dkim_verifier/pull/162 pull requests in the `beta` and `master` branches respectively?

Can you merge the Hungarian translations from the `beta` branch into the `master` branch? Or do we need to retype the Hungarian translations in the `master` branch?

Thank you

**Comment by lieser** [comment]
Thanks a lot for the Hungarian translation. There is no need to create a separate pull request for master.

Note that I will not directly merge #162 (including the new translations) in to beta. Instead I will manually rebase it onto master, and then merge it also into beta (I hope to get time for that tomorrow).

The next time please create a pull request for master. Uplifting it to beta is easier than the over way around.

**Comment by ovari** [comment]
Sorry for doing this the wrong way. Not sure if we completely understand; however, can you please advise when you have all our files? This is so we can delete our fork. Thank you

**Comment by lieser** [comment]
I added now the Hungarian translation to master. So it should be safe to delete your branch now.
I will later also add them to the beta branch.

Note that I did some changes. Most notably I shortened some of the translations you did. They are shown at places with limited place, so not fully writing out DKIM is intentional. Also the `Verifier` in the add-ons name should not be translated, so that the add-on always has the same name regardless of the local.

See https://github.com/lieser/dkim_verifier/commit/036b2fa00ee2c9c44ef2aeaf70b1ad7c3308a18a for a diff of the Hungarian translation compared to your branch.

Here is an 2.1.0pre2 version of the add-on with your translation added that you could already try out: [dkim_verifier@pl.zip](https://github.com/lieser/dkim_verifier/files/3462194/dkim_verifier%40pl.zip)

**Comment by ovari** [comment]
Thank you for advising that our fork can be deleted.

Would you please allow the name of your add-on to be translated. It makes it easier to search for your add-on as it is in the local language. Having the English name in brackets enables [ATN hu](https://addons.thunderbird.net/hu/thunderbird/search/?q=verifier) to find your add-on when it is searched from in English or Hungarian.

Below is a list of some add-ons whose names which have been translated into Hungarian:

Bagoly az Exchange számára
https://addons.thunderbird.net/hu/thunderbird/addon/owl-for-exchange/

Gyorsszöveg (Quicktext)
https://addons.thunderbird.net/hu/thunderbird/addon/quicktext/

Küldés később
https://addons.thunderbird.net/hu/thunderbird/addon/send-later-3/

MutasdMeg! (LookOut)
https://addons.thunderbird.net/hu/thunderbird/addon/lookout-fix-version/

Névjegyzék (CardBook)
https://addons.thunderbird.net/hu/thunderbird/addon/cardbook/

Nyelvtan-ellenőrzés (Grammar Checker)
https://addons.thunderbird.net/hu/thunderbird/addon/grammar-checker/

Területi kapcsoló (Simple Locale Switcher)
https://addons.thunderbird.net/hu/thunderbird/addon/simple-locale-switcher/

Thunderbird-összehangolás (TbSync)
https://addons.thunderbird.net/hu/thunderbird/addon/tbsync/

Tömörített fejléc (CompactHeader)
https://addons.thunderbird.net/hu/thunderbird/addon/compactheader/

Üzenet átirányítás (Mail Redirect)
https://addons.thunderbird.net/hu/thunderbird/addon/mailredirect/

Can you please allow the your add-on name to be translated?

We will wait until you respond until we delete our fork as you may like to enable the Hungarian localization of your add-on name.

Thank you

**Comment by ovari** [comment]
Please see `3.1.2 Acronyms` on page 18 of the [Microsoft Hungarian Style Guide (2017)](https://github.com/lieser/dkim_verifier/files/3462926/MicrosoftHungarianStyleGuide2017.pdf), which gives the example:
English `Object Linking Embedding (OLE)` → Hungarian `OLE (Object Linking and Embedding – objektumcsatolás és beágyazás)`

This another reason for
English `DKIM Verifier` → Hungarian `DKIM (DomainKeys Identified Mail – TartományKulcsok azonosított levelek) ellenőrző`

Thank you for your understanding

**Comment by lieser** [comment]
Reverted part of my changes in 23c09d778449ec2d78bba49f5e63febbdf3eb2be.

In the add-ons option GUI it now uses the Hungarian translation. In the add-on overview and on ATN (still have to add the translations there) it will use the Hungarian, and also show the original name in parentheses.

**Comment by ovari** [comment]
Thank you

**Comment by lieser** [comment]
The translation is now also on ATN: https://addons.thunderbird.net/hu/thunderbird/addon/dkim-verifier/

**Comment by ovari** [comment]
@lieser are you able to advise when the xpi file with the hu locale will be available on ATN? Thank you

**Comment by lieser** [comment]
No, that depends a lot on the reviewers on ATN. Can be just a few days, or multiple weeks. Note that you can already get it from https://github.com/lieser/dkim_verifier/releases.

**Comment by ovari** [comment]
Thank you for the link.

Do you know when your add-on, which works with [Thunderbird 68.0 ESR](https://www.thunderbird.net/), will be sent to [ATN](https://addons.thunderbird.net/addon/dkim-verifier/)? Thank you once again.

**Comment by lieser** [comment]
No, but I hope to finalize the 3.0.0 release in a few days. Subscribe to #115 to get notified about any news regarding TB 68.
