### ISSUE TITLE
onmicrosoft.com global rule

### ISSUE THREAD

**Issue by ale5000-git** [lieser/dkim_verifier#165]
That I know all mails from `*@*.onmicrosoft.com` are signed (but every subdomain have a different signer).

Since I got an unsigned mail that is phishing is it possible to specify that this domain must be globally signed without specify the signer domain?

**Comment by lieser** [comment]
It should be possible by creating the following sign rule:
- domain `onmicrosoft.com`
- From: `*` (i.e. matching all addresses)
- SDID: leave empty
- Rule type 1 (must be signed)
- Priority: lower than any other you have for the `onmicrosoft.com` domain specifying a specify SDID (e.g. `1000`)

**Comment by ale5000-git** [comment]
Hi,
thanks for the reply but what I mean is if it was possible to add it to the default rules as this will help to discover bad mails.

**Comment by ale5000-git** [comment]
I mean a different thing.
I get a spam mail in the past where the originating address was ending in `@onmicrosoft.com`.

Regular mails:
`some-user@some-domain.com` (signed by some-domain.onmicrosoft.com)

Spam mails:
`some-user@onmicrosoft.com` (not signed)

So the `From` could be `From: *@onmicrosoft.com` instead of `From: *` (I suppose it doesn't interfere in this case or I'm wrong?)

**Comment by lieser** [comment]
Ok, than I misunderstood you. Adding a rule saying all e-mail directly from the domain `onmicrosoft.com` (and not a subdomain) should not be a problem

**Comment by lieser** [comment]
added a rule for `onmicrosoft.com`
