### ISSUE TITLE
Beta Candidate builds not working

### ISSUE THREAD

**Issue by gene-git** [lieser/dkim_verifier#167]
I get this in error console:

TypeError: DKIM_Verifier.Display is undefined messenger.xul:1:1
    on command chrome://messenger/content/messenger.xul:1
Also see things like these which may be related
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIMsgFolder.server]

With released version 3.0.0
Candidate build : 70.0b1   build1  20190904175853

I usually use the Beta Candidates as they'll be the next beta.

thanks.

**Comment by gene-git** [comment]
Hi - curious, fi you have any thoughts on what may need doing to get this working again?

**Comment by gene-git** [comment]
Found some more console error messages that may be of interest:

MozMailMultiEmailheaderfield is not defined dkim.js:371
    <anonymous> chrome://dkim_verifier/content/dkim.js:371
    loadScript resource:///modules/Overlays.jsm:543
    load resource:///modules/Overlays.jsm:226
    load resource:///modules/Overlays.jsm:48
    observe chrome://messenger/content/parent/ext-legacy.js:229

**Comment by lieser** [comment]
Sorry that this took a little longer.
But it should be now fixed in the 3.0.1 version (currently under review on ATN). You can get it already from https://github.com/lieser/dkim_verifier/releases/tag/v3.0.1

**Comment by gene-git** [comment]
nothing to apologize for - thank you!!
