### ISSUE TITLE
The curious case of culligan.it

### ISSUE THREAD

**Issue by ale5000-git** [lieser/dkim_verifier#168]
Hi,
unfortunately I have discovered some peculiar cases:

- `postmaster@culligan.it` (signed by culligan.it)
- `fatturazionebw@CULLIGAN.IT` (signed by culligan.it)
- `goccione@culligan.it` (signed by culligan.it, some aren't signed at all)
- `goccione@CULLIGAN.IT` (signed by culliganorg.onmicrosoft.com)
- `no-reply@culligan.it` (signed by culligan.it, some aren't signed at all)
- `amministrazionebw@CULLIGAN.IT` (signed by culliganorg.onmicrosoft.com)
- Some other mails signed by culligan.it

- `infobw@culligan.it` (signed by mail330.bms6.bmsend.com, some aren't signed at all)

--------------------------------------------------------------------------------

So it can possibly be like this:

General rule:
- `*@culligan.it` (all mails signed by culligan.it)

Specific rules:
- `amministrazionebw@culligan.it` (all mails signed by culliganorg.onmicrosoft.com)
- `goccione@culligan.it` (mails signed by culligan.it or culliganorg.onmicrosoft.com, but signing is optional)
- `no-reply@culligan.it` (mails signed by culligan.it, but signing is optional)
- `infobw@culligan.it` (exclude rules for this address and leave it with the default behaviour without rules)

--------------------------------------------------------------------------------

Or if you want to simplify (probably more foolproof):

General rule:
- `*@culligan.it` (all mails signed by culligan.it or culliganorg.onmicrosoft.com)

Specific rules:
- `goccione@culligan.it` (signing is optional)
- `no-reply@culligan.it` (signing is optional)
- `infobw@culligan.it` (exclude rules for this address and leave it with the default behaviour without rules)

**Comment by ale5000-git** [comment]
Not very important, I think making it optional could be fine in this case.

**Comment by lieser** [comment]
changed the `culligan.it` domain to neutral
