### ISSUE TITLE
`libunbound2` DNS resolver available on Arch Linux ?? 

### ISSUE THREAD

**Issue by Cbhihe** [lieser/dkim_verifier#171]
The DNS recursive resolver package `libunbound2` seems not to exist (as such) for the Arch Linux distro.  (Surprise !)
There is similar tech and logic available but not under the same name.  
See: https://repology.org/project/unbound/versions
Does that preclude the use of could-be-substitute packages such as `unbound`or `python-unbound`? 
If so, it would mean that Archers are stuck with the JavaScript DNS library.  
Do you confirm ?

**Comment by lieser** [comment]
Not familiar with arch linux. The important question is whether you can find a package with a unbound library included, that exposes the needed functions, i.e. `ub_resolve`. As a last resolve, you can always try compile one yourself directly from the unbound sources.

But it look like the `unbound` package has included that you need. At least according to https://www.archlinux.org/packages/community/x86_64/unbound/files/ it contains library files such as `/usr/lib/libunbound.so`, which are probably exposing the needed functions.

The `python-unbound` according to https://aur.archlinux.org/packages/python-unbound has the `unbound` package as a dependency. It is probably only a wrapper using the library files included in the `unbound` package. It should not be needed. But it is a strong indicator that the libraries included in the  `unbound` package are exposing all needed functions.

**Comment by Cbhihe** [comment]
Thank you very much for your reply, Philippe. Will experiment a bit.

**Comment by lieser** [comment]
If you find a working solution for you, would be nice if you could add some info to this issue or to the wiki (https://github.com/lieser/dkim_verifier/wiki/DNS#linux-install-the-libunbound-library-with-the-package-manager) for others. who may have the same question in the future
