### ISSUE TITLE
No DKIM status visible anywhere when a message is opened in a new window

### ISSUE THREAD

**Issue by tibitts** [lieser/dkim_verifier#172]
TB 68.1.0, DKIM Verifier 3.0.0
I installed the add-on and haven't changed the default options.
'Show DKIM header' is set to 'when an email with a DKIM signature is viewed'.
'Show DKIM status bar' is set to 'Never'.
Resolver is set to 'JavaScript DNS library', and 'Get DNS servers from OS' is checked.

When opening a message with a DKIM signature (e.g. from Google, or Github), there is no indication about it at all in the message window.
The only visible trace of DKIM Verifier is a text label 'DKIM:' in the status bar of the main window.

This happens with both, Linux and Windows Thunderbird installations.
It used to work in the message header without a hitch in TB versions before TB60.

DKIM related messages in the error console:
WebExtensions: Loading packed extension from /home/xxx/.thunderbird/zzz/extensions/dkim_verifier@pl.xpi ext-legacy.js:157
WebExtensions: Loading add-on preferences from  /home/xxx/.thunderbird/zzz/extensions/dkim_verifier@pl.xpi ext-legacy.js:190
WebExtensions: Firing profile-after-change listeners for dkim_verifier@pl ext-legacy.js:194

What am I missing?

**Comment by lieser** [comment]
Can not reproduce the issue. The messages you see in the log are coming from Thunderbird itself, and are normal. Please enable debugging in the advanced options of the add-on, maybe this will show more.

Do you have any other add-ons enabled? If yes please disable them and try again. Could be an incompatibility with another add-on.

**Comment by tibitts** [comment]
Yes, there are other add-ons:
Allow HTML Temp
Enigmail
File Link Provider for Box
gContactSync
IMAP Received Date 
Lightning

Disabling all add-ons except DKIM Verifier makes no difference. Turning on debug logging does not produce any additional output.

Here's the entire output from the Error Console with DKIM Verifier being the only enabled add-on.

WebExtensions: Loading packed extension from /home/xxx/.thunderbird/zzz/extensions/dkim_verifier@pl.xpi ext-legacy.js:109
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:19
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:20
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:21
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:23
WebExtensions: Loading add-on preferences from  /home/xxx/.thunderbird/zzz/extensions/dkim_verifier@pl.xpi ext-legacy.js:142
WebExtensions: Firing profile-after-change listeners for dkim_verifier@pl ext-legacy.js:146
9/19/2019, 18:42:35	DKIM_Verifier.Logging	DEBUG	initialized logging.jsm:101
No chrome package registered for chrome://browser/skin/identity-icon.svg

**Comment by groland11** [comment]
I noticed that DKIM status is missing (header, tooltip, statusbar) if you open message in a new window. If you display messages in preview pane or new tab everything works perfectly.

Maybe the title of this issue should be renamed to "No DKIM status visible if message is opened in new window".

**Comment by tibitts** [comment]
I can confirm the problem only happens when a message is opened in a new window. That's what I always do.

**Comment by lieser** [comment]
Thanks a lot for the hint with opening in a new window. Problem was easy to find thanks to it.

This should be fixed in the 3.0.1 version (currently under review on ATN). You can get it already from https://github.com/lieser/dkim_verifier/releases/tag/v3.0.1
