### ISSUE TITLE
[Exception... "Not enough arguments [nsIProtocolProxyService.newProxyInfo]"

### ISSUE THREAD

**Issue by Cbhihe** [lieser/dkim_verifier#173]
Hi:
I use the JavaScript DNS library on an up to date Arch linux with TB 68.1.0.
Setting TB's manual proxy 127.0.0.1 over port 9050 and socks v5 cripples the DKIM validation.  

**_Error console:_**

9/14/2019, 12:24:23	DKIM_Verifier.JSDNS	FATAL	[Exception... "Not enough arguments [nsIProtocolProxyService.newProxyInfo]"  nsresult: "0x80570001 (NS_ERROR_XPC_NOT_ENOUGH_ARGS)"  location: "JS frame :: resource://dkim_verifier/JSDNS.jsm :: DNS_readAllFromSocket :: line 1030"  data: no]
DNS_readAllFromSocket@resource://dkim_verifier/JSDNS.jsm:1030:16
queryDNSRecursive@resource://dkim_verifier/JSDNS.jsm:790:11
queryDNS@resource://dkim_verifier/JSDNS.jsm:571:2
asyncJSDNS_QueryDNS/<@resource://dkim_verifier/DNSWrapper.jsm:155:48
asyncJSDNS_QueryDNS@resource://dkim_verifier/DNSWrapper.jsm:155:9
DNS_resolve@resource://dkim_verifier/DNSWrapper.jsm:90:12
getKeyFromDNS@resource://dkim_verifier/dkimKey.jsm:305:25
Key_getKey@resource://dkim_verifier/dkimKey.jsm:174:17
verifySignature@resource://dkim_verifier/dkimVerifier.jsm:1153:44
processSignatures@resource://dkim_verifier/dkimVerifier.jsm:1291:20
Verifier_verify2/promise<@resource://dkim_verifier/dkimVerifier.jsm:1427:23
Verifier_verify2@resource://dkim_verifier/dkimVerifier.jsm:1432:5
_authVerifier_verify/promise<@resource://dkim_verifier/AuthVerifier.jsm:173:45

JSDNS.jsm:792
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Request to access cookie or storage on “https://www.google.com/recaptcha/api2/anchor?ar=2&k=6LddtWQU…0OjQ0Mw..&hl=en&v=v1566858990656&size=normal&cb=65uuug3oiy9l” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. dkim-verifier:318:107
Request to access cookie or storage on “https://www.google.com/recaptcha/api2/anchor?ar=2&k=6LddtWQU…0OjQ0Mw..&hl=en&v=v1566858990656&size=normal&cb=65uuug3oiy9l” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. 2 dkim-verifier:310:148
Request to access cookie or storage on “https://www.google.com/recaptcha/api2/anchor?ar=2&k=6LddtWQU…0OjQ0Mw..&hl=en&v=v1566858990656&size=normal&cb=65uuug3oiy9l” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. dkim-verifier:311:193
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Request to access cookie or storage on “https://www.google.com/recaptcha/api2/bframe?hl=en&v=v156685…6&k=6LddtWQUAAAAAJNHNYsvFo0IyLewR0S71DvQe7k0&cb=b4iw7zfmyomq” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. 2 dkim-verifier

....  content blocking at MUA level ? at MTA level ? or within Google ? 
Not sure even that is the issue.

**Comment by lieser** [comment]
I can reproduce the issue with `Not enough arguments`, will try to fix it in the next release.

I don't see any messages about content security policy. And the log messages you posted are to me looking unrelated to the actual error of the add-on.

**Comment by Cbhihe** [comment]
Yes, right. The second part is related to cookie settings and uBlock. Sorry for the mix-up. 
Thank you.

**Comment by lieser** [comment]
Reopening this for now, as it is not yet fixed in the add-on.

**Comment by lieser** [comment]
This should be fixed in the 3.0.1 version (currently under review on ATN). You can get it already from https://github.com/lieser/dkim_verifier/releases/tag/v3.0.1
