### ISSUE TITLE
Emails mostly invalid question

### ISSUE THREAD

**Issue by PintLang** [lieser/dkim_verifier#175]
Thanks for this excellent addon. 
Question. When I send from my gmail.com address to my other addresses (my own domain and a Outlook hasted domain), I get a valid signature.  Most other emails, including those from gmail.com addresses, get "eMail has been modified".  I've attempted look at the source information but I can't see why.

Thanks.

**Comment by lieser** [comment]
If I understand you correctly, the receiving account you have problems with is an Outlook account.

There are known problems with Outlook modifying messages after receiving them. See also https://github.com/lieser/dkim_verifier/wiki/FAQ#all-or-almost-all-e-mails-with-dkim-signature-are-failing-with-the-same-error and #70.

Have you already tried to use enable the reading of the Authentication-Results header?

As for why you don't have problems with sending e-mails coming from your own gmail address, I can only guess. Probably for some reason the emails you send are by chance already in a format that is not changed by outlook.
Are you also using Thunderbird for your gmail address? That is probably something a lot of other gmail users you are receiving emails from are not using.

As for looking at the source:
If you don't have access to the original email, it is pretty hard/impossible to find that changed. Best do this not by comparing to the one send, but by sending one single email to multiple recipients (affected server, and one know to be not affected), and compare both received emails.

**Comment by lieser** [comment]
As you didn't respond yet, I assume your question is answered. If not, feel free to reopen this.
