### ISSUE TITLE
Status in email header box and status bar stays "DKIM: Validating..." (with CompactHeader add-on)

### ISSUE THREAD

**Issue by azoellner** [lieser/dkim_verifier#177]
**Issue:** The DKIM validation status in the email's header box stays at "Validating..." (DE: "Überprüfe...") [Update:] The same applies to the status bar.

**System:** DKIM Verifier 3.0.0 on Thunderbird 68.1.0 (32-Bit)

**Analysis:** The error console shows
<pre>
TypeError: headerBox.emailAddresses.firstChild is null
(chrome://dkim_verifier/content/dkim.js:669:29)
</pre>

**Fix:** As a simple fix, insert a check
<pre>
if(!headerBox.emailAddresses.firstChild) return;
</pre>
into functions `setDKIMFromTooltip` and `removeDKIMFromTooltip`, just before the failing lines 669 and 679.
This worked for me, via modifying the .xpi and then disabling and re-enabling the addon. After applying the fix, the DKIM status is shown properly.

**Remarks:** Unfortunately, the source code does not match the code in the repository https://github.com/lieser/dkim_verifier/blob/master/chrome/content/dkim.js#L291-L311

**Full error log:**
<pre>
22.9.2019, 01:14:37	DKIM_Verifier.Display	FATAL
... TypeError: headerBox.emailAddresses.firstChild is null
... (chrome://dkim_verifier/content/dkim.js:669:29) JS Stack trace:
setDKIMFromTooltip@dkim.js:669:29
Display_setCollapsed@dkim.js:724:5
Display_onEndHeaders/promise<@dkim.js:957:9
Display_onEndHeaders@dkim.js:973:5
onEndHeaders@msgHdrView.js:458:32
processHeaders@msgHdrView.js:563:10
dkim.js:669:29
    setDKIMFromTooltip chrome://dkim_verifier/content/dkim.js:669
    Display_setCollapsed chrome://dkim_verifier/content/dkim.js:724
    promise chrome://dkim_verifier/content/dkim.js:957
    Display_onEndHeaders chrome://dkim_verifier/content/dkim.js:973
    onEndHeaders chrome://messenger/content/msgHdrView.js:458
    processHeaders chrome://messenger/content/msgHdrView.js:563

22.9.2019, 01:14:37	DKIM_Verifier.Display	FATAL
... TypeError: headerBox.emailAddresses.firstChild is null
... (chrome://dkim_verifier/content/dkim.js:669:29) JS Stack trace:
setDKIMFromTooltip@dkim.js:669:29
Display_setCollapsed@dkim.js:724:5
displayResult@dkim.js:561:8
handleException@dkim.js:545:4
onReject@dkim.js:975:4
dkim.js:669:29
    setDKIMFromTooltip chrome://dkim_verifier/content/dkim.js:669
    Display_setCollapsed chrome://dkim_verifier/content/dkim.js:724
    displayResult chrome://dkim_verifier/content/dkim.js:561
    handleException chrome://dkim_verifier/content/dkim.js:545
    onReject chrome://dkim_verifier/content/dkim.js:975
</pre>

**Comment by lieser** [comment]
Thanks for the detail detail error reporting and analysis. Will fix it in the next version.

As for the source code:
The 3.0.0 version is still in the beta branch (https://github.com/lieser/dkim_verifier/tree/beta). And all releases should have a matching tag, which point to the exact source code used for building the xpi: https://github.com/lieser/dkim_verifier/tree/v3.0.0

**Comment by lieser** [comment]
Are you using the the CompactHeader add-on? Can only reproduce the error you posted with CompactHeader installed.
If you don't have it installed, please try to disable all other add-ons, and see if you can still reproduce the error.

**Comment by azoellner** [comment]
Yes, I'm using CompactHeader 3.0.0beta3. After deactivating this addon, the DKIM Verifier works just fine.

**Comment by lieser** [comment]
This should be fixed in the 3.0.1 version (currently under review on ATN). You can get it already from https://github.com/lieser/dkim_verifier/releases/tag/v3.0.1
