### ISSUE TITLE
ANYROAM Icon

### ISSUE THREAD

**Issue by Ratief** [lieser/dkim_verifier#180]
Could you please add my company's favicon? We sign all emails.
https://www.anyroam.net/favicon.ico

For easy copy/pasting:
"anyroam.net": "anyroam.net.ico",

I didn't want to create a fork just for a favicon pull request. I hope you don't mind doing it this way.

**Comment by lieser** [comment]
I will add both a default rule and a favicon it in the next version.

That you didn't create a pull request for it is completely fine.

**Comment by lieser** [comment]
Added the domain. You can get a prerelease from https://github.com/lieser/dkim_verifier/issues/169#issuecomment-570950809
