### ISSUE TITLE
Problem with the GUI setup (warn) of missing DNSSEC signing

### ISSUE THREAD

**Issue by cnleo** [lieser/dkim_verifier#182]
Still TB 60.9.0 (32 bit windows 7), Can't install DV > 2.1.0

I setup the view to don’t warn me (with background color) of the lack of DNSSEC but it is still warning me (visual).

SETUP: 

DKIM Verifier Options → Advanced 
… DNSSEC …  DKIM …  => NONE

DKIM Verifier Options → View 
Validate Signature with warnings => Background “ORANGE” 
(“Color differs from the other entries”)

RESULT:
An orange background by the mail header “From”, if only DNSSEC signing is missing.

SHOULD RESULT:
Other then orange background by the mail header “FROM” if no other check failed.

CONSOLE OUTPUT (removed the adresses):
`DKIM_Verifier.AuthVerifier	DEBUG	AuthResult result found: {"version":"3.0","dkim":[{"version":"2.0","result":"SUCCESS","sdid":"_","auid":"@_,"selector":"default","warnings":[{"name":"DKIM_POLICYERROR_KEY_INSECURE"}],"keySecure":false}]}`

**Comment by cnleo** [comment]
Mhh, OK now it works. Looks like it needs a restart on changes.
But the hint is completely gone now, in console and in hover text.
This GUI setting should only a visual “background” and “text” for my understand.

`DKIM_Verifier.AuthVerifier	DEBUG	AuthResult result found: {"version":"3.0","dkim":[{"version":"2.0","result":"SUCCESS","sdid":"_","auid":"@_","selector":"default","warnings":[],"keySecure":false}]}`

**Comment by lieser** [comment]
Sorry for the late reply. You seem to have figured it out by yourself already, Still a few clarifications below:

The result is only saved if you enable the *Save result of the verification* (off by default).
You can force a reverification by selecting `Reverify DKIM signature` in the `More`/`Other Actions` drop-down menu in the e-mail header.
Maybe a better solution for you would be to keep this disabled, and only enable the caching of the DKIM keys.
