### ISSUE TITLE
Varying results

### ISSUE THREAD

**Issue by rsmits1975** [lieser/dkim_verifier#183]
When the verifier states : Invalid (E-Mail was modified)
(This is the case)
But when I modify the options and enable : (Read Authentication-Results header)
The DKIM signature suddenly is Valid ?
Valid (Signed by gmail.com)  SPF:pass  DMARC:pass

I don't know if I am the only one with this issue, or it may be these E-Mails in combination with our Exchange server.
Greetings.

**Comment by lieser** [comment]
The e-mail was probably only modified after the server did it's own DKIM verification. That is why the DKIM result saved by the server in the Authentication-Results header is different from the one done by the add-on.

Microsoft/Exchange is know to cause this,

See also https://github.com/lieser/dkim_verifier/wiki/FAQ#all-or-almost-all-e-mails-with-dkim-signature-are-failing-with-the-same-error and https://github.com/lieser/dkim_verifier/wiki/Options#read-authentication-results-header.
