### ISSUE TITLE
My emails from Thunderbird are not signed DKIM

### ISSUE THREAD

**Issue by scottcmatthew** [lieser/dkim_verifier#194]
I added the DKIM verifier to my Thunderbird.

I have been trying to get my emails "Signed" to improve my sender score.

When I send from this email address, from my thunderbird, through my Bluehost server, it arrives unsigned.

When they send using this same email address from their server it is signed.

Do I need some sort of Certificate?  Where do I get it?

How is my DKIM signature not getting through?  

I have been struggling with this for a week.   Can help me?

Thanks.

Scott Matthew

![Send direct from web host](https://user-images.githubusercontent.com/59898323/72391049-cfd3bd80-36f1-11ea-9b8f-5f4678ce2967.PNG)
<img width="872" alt="Thunderbird say signed" src="https://user-images.githubusercontent.com/59898323/72391050-cfd3bd80-36f1-11ea-8bd0-86e8b363a48e.png">
<img width="673" alt="Thunderbird security settings" src="https://user-images.githubusercontent.com/59898323/72391051-cfd3bd80-36f1-11ea-8eba-a258bf3cecba.png">
<img width="524" alt="DKIM Validator say NOT signed" src="https://user-images.githubusercontent.com/59898323/72391052-cfd3bd80-36f1-11ea-85b3-3825772f8e7d.png">

**Comment by lieser** [comment]
Note that this add-on does not do any DKIM signing. It only verifies DKIM signatures. See also #89.
You will have to configure DKIM in your e-mail server. The client (Thunderbird) is not involved in this.

Also note that DKIM has nothing to do with [S/MIME](https://en.wikipedia.org/wiki/S/MIME), which based on your screenshots you seemed to have configured in Thunderbird.
