### ISSUE TITLE
Next 3.0 release?

### ISSUE THREAD

**Issue by gene-git** [lieser/dkim_verifier#196]
Do you plan to update and release a new 3.0.2 branch soon - been a while since the last one.

**Comment by lieser** [comment]
I plan to release a 3.1.0 version shortly (will probably submit it today to ATN for review). Was waiting for the 2.2.0 review on ATN.

And yes, with that I plan to make it the default branch, and do not plan any more feature releases for the 2.x branch.

**Comment by lieser** [comment]
[v3.1.0](https://github.com/lieser/dkim_verifier/releases/tag/v3.1.0) is released, and submitted to ATN.

**Comment by gene-git** [comment]
Terrific thanks
