### ISSUE TITLE
Minor errors

### ISSUE THREAD

**Issue by ale5000-git** [lieser/dkim_verifier#197]
Two problems:
https://github.com/lieser/dkim_verifier/commit/cc05fe54249d116b05e8641041f2b40220433688#r36881514
https://github.com/lieser/dkim_verifier/commit/cc05fe54249d116b05e8641041f2b40220433688#r36875773

**Comment by lieser** [comment]
Thanks a lot for reporting. Will fix it in the upcoming 3.1.0.
