### ISSUE TITLE
Some version confusion on ATN?

### ISSUE THREAD

**Issue by siffegh** [lieser/dkim_verifier#198]
ATN main entry says 'DKIM Verifier 3.0.1'/Last Updated: Sept. 22, 2019 and it's downloading dkim_verifier-2.2.0-tb.xpi.

Also, 2.2 is listed at the top of the Versions page as 'Version 2.2.0 Released Jan. 19, 2020 867.1 KiB Works with Thunderbird 52.0 - 60.*' .

**Comment by lieser** [comment]
The problem is that 2.2.0 was released after the 3.01. As you have noticed, ATN does not handle this in the best way.

But the problem should go away soon with the upcoming 3.1.0 release. See also #196

**Comment by ale5000-git** [comment]
@lieser: Why the version 3.1.0 isn't available on addons.thunderbird.net?

**Comment by lieser** [comment]
There is a review process on ATN, which can take a couple of days.
