### ISSUE TITLE
ARC signature processing?

### ISSUE THREAD

**Issue by sbsrouteur** [lieser/dkim_verifier#201]
Is there any plan to include ARC validation as part of DKIM verifier, Since many companies will use forwarders and ARC signed messages instead of just DKIM.

**Comment by lieser** [comment]
No, I currently don't see myself adding it. Although I agree it would be a nice addition, I simply don't see myself finding the time to implement it.
Pull request adding it are of course always welcomed.

Note that I will close this, as it should be a duplicate of #87.
