### ISSUE TITLE
Add DKIM Test-Output if DKIM-Signature is in test mode "t=y"

### ISSUE THREAD

**Issue by ahoepner** [lieser/dkim_verifier#211]
I wondered why your plugin works on email from others without problems and on my own emails not. There was no output to see at all and it need a long time, to consider that the reason seems to be the string "t=y" inside the DKIM-Signature on DNS-Server.
This means "dont use dkim mandatory, because we are in test mode". 
So it would be fine also showing test results if "t=y" is active and maybe you should append "Testmode" or any other additional information in that case.

**Comment by lieser** [comment]
Note that there already exist an advanced option to also verify signatures that are in testing mode, see https://github.com/lieser/dkim_verifier/wiki/Options#still-verify-the-signature-if-a-domain-is-only-testing-dkim

This seems to be already what you want.

If this is about changing the default behavior, I don't see my self doing that.
The DKIM standard is explicitly states that a verifier must not treat messages in testing mode differently from unsigned, and I try to follow the standard as close as reasonably possible.

For the future, there is also a debugging option, where one can see that the verifier does. See https://github.com/lieser/dkim_verifier/wiki/Options#enable-debugging
