### ISSUE TITLE
8bits encoding invalid

### ISSUE THREAD

**Issue by Pradesh-GH** [lieser/dkim_verifier#214]
Thunderbird 78.2.2 (64bits)
DKIM Verifier 4.0.0pre1

When using 8bits encodings and/or adding smileys DKIM Verifier reports Invalid (E-Mail was modified).
Example with 7bits encoding:
![DKIM with 7bits encoding](https://user-images.githubusercontent.com/71440031/93509223-ba1d3480-f91f-11ea-86ba-bea42be8da2b.jpg)

And with 8bits encoding:
![DKIM with 8bits encoding](https://user-images.githubusercontent.com/71440031/93509262-c608f680-f91f-11ea-83f5-4fde731fb91a.jpg)

**Comment by lieser** [comment]
Thanks a lot for reporting the issue. I can reproduce the problem, and will try to fix it this weekend,

**Comment by lieser** [comment]
I just published a new pre-release 4.0.0pre2 at https://github.com/lieser/dkim_verifier/releases that should fix this.

If you still encounter the problem, please reopen this issue.
