### ISSUE TITLE
Try to read non RFC compliant Authentication-Results header option is ignored

### ISSUE THREAD

**Issue by KlaasBonnema** [lieser/dkim_verifier#221]
With version 4.0.0pre3 some emails fail verification. The message says DKIM: validating...
The Thunderbird console log reports: uncaught exception: ParserError: invalid line (no token ";" or ":") "null"

**Comment by lieser** [comment]
Thanks a lot for reporting this. Note that the ARH header is not allowed to end in a `;`. As this is a common error with low impact, there exist the option to allow this: [Try to read non RFC compliant Authentication-Results header](https://github.com/lieser/dkim_verifier/wiki/Options#try-to-read-non-rfc-compliant-authentication-results-header), which you may hat already enabled.

Unfortunately I messed up the refactoring of that code, and this options is simply completely ignored. Will fix it in the next version.

**Comment by lieser** [comment]
fixed in [4.0.0pre4](https://github.com/lieser/dkim_verifier/releases/tag/v4.0.0pre4)
