### ISSUE TITLE
DKIM warning, even for valid signatures

### ISSUE THREAD

**Issue by oligh** [lieser/dkim_verifier#234]
Hi, I'm using TB68.10 with DKIM Verifier 3.1.0 on Linux
Since a few days (or weeks?) EVERY mail is marked with warning. Examples:
Signiert durch \"ubnt.com\")", warnings_str:["Falscher Signierer (sollte ubnt.com sein)
Signiert durch \"github.com\")", warnings_str:["Falscher Signierer (sollte github.com,sgmail.github.com sein)
Occurs on multiple machines.  Does NOT happen on my test machine with TB78 + DKIM Verivifer 4

**Comment by lieser** [comment]
Thanks for reporting.

Can you please enabled debugging in the advanced add-on option, and post or send me via email to lieser+dkim@posteo.net the complete logs of an affected verification?

**Comment by lieser** [comment]
Turned out to be the same Problem as in #229, will close this one as a duplicate.

**Comment by lieser** [comment]
This should be fixed now, you can get a test version at https://github.com/lieser/dkim_verifier/issues/199#issuecomment-774676192.

Please let me know if it is still not working for you.
