### ISSUE TITLE
Insecure Signature Algorithm

### ISSUE THREAD

**Issue by OscamSatUser** [lieser/dkim_verifier#236]
I am not sure as to why i keep getting this error?  Is there documentation as to what causes this specific error.  I have set two of these up so far, one for one domain and one for another.  One domain works fine, the other is giving me this error, and i have tried multiple things trying to resolve it with no success.

The most important thing, i don't want to be creating a situation where my Emails from the domain are getting rejected.  So, this warning has me worried.

Ps.  Using Thunderbird 78.7.0 32bit

Thank you.

**Comment by OscamSatUser** [comment]
Never mind, i figured it out.. It was the difference between sha1 and sha256.  I was able to switch my email server to utilize sha256 and that resolved the issue.  

Great software.  Thank you for your work.

**Comment by lieser** [comment]
Nice so hear that you figured out the problem already by yourself. Just for completeness, there exist an advance option for it, which is documented at https://github.com/lieser/dkim_verifier/wiki/Options#treat-rsa-sha1-sign-algorithm-as.

Default for usage of SHA-1 should be warning, not an error.
