### ISSUE TITLE
Postbox 7 Support

### ISSUE THREAD

**Issue by brandonkal** [lieser/dkim_verifier#240]
I'd love to have this working in Postbox 7 on macOS which is based off of Thunderbird.

**Comment by lieser** [comment]
Unfortunately I don't think I will find the time to port this to Postbox 7. Especially sine it seems to be based on Thunderbird 68, which would mean I would have to maintain multiple major versions of the add-on.

If Postbox will make the switch to a newer underlying Thunderbird that supports WebExtension/MailExtension, it will be more likely for me to port it.
So please let me know if that will be the case in the future.

**Comment by lieser** [comment]
Closing this as not planned for now. Feel free to reopen this once Postbox is based on a recent Thunderbird that supports WebExtension/MailExtension.
