### ISSUE TITLE
Addon disabled, requires "full, unrestricted access to TB and my computer" (upgrade to Ubuntu 20.04)

### ISSUE THREAD

**Issue by hawran** [lieser/dkim_verifier#241]
Hi,
I've just upgraded to `Ubuntu 20.04.2 LTS` and after upgrading add-ons within my TB (`User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Thunderbird/78.7.1` a warning notification has appeared:

![210226-161714 Thunderbird-v 78 7 1 DKIM-Verifier-disabled Ubuntu](https://user-images.githubusercontent.com/25924718/109319959-c5ba4300-784f-11eb-8650-1590b16b1edf.png)

What's going on here?

BTW, `DKIM Verifier is incompatible with Thunderbird 78.7.1.`

**Comment by lieser** [comment]
This is the new permission model that is part of the new WebExtensions. In older Thunderbird versions, add-ons always had this permission, As normal WebExtensions do not provide everything this add-on needs, this full access is still needed,
See also https://support.mozilla.org/en-US/kb/permission-request-messages-thunderbird-extensions#w_have-full-unrestricted-access-to-thunderbird-and-your-computer

Regarding the incompatible with Thunderbird 78, I can not reproduce this. Please make sure you have the latest version of the add-on installed.

**Comment by hawran** [comment]
> This is the new permission model ...

Well, why does this add-on need:
- Change every aspect of Thunderbird’s user interface
- Read and modify all your data (messages, contacts, calendars, web content and passwords)
- Read, **modify** and **execute** any file on your computer

?

I'm on the `3.1.0`.
When I try to update the warning mentioned above appears so I'm not willing to update at the moment.
(unless I'm sure I know what's going on here)

**Comment by lieser** [comment]
Although I understand your curiosity about the permissions, I get the feeling you didn't really understand the linked explanation.

> Well, why does this add-on need:

The list you quoted are only examples of that an add-on **could** potentially do with that permission. Not what an add-on requesting that permission **needs** or will do.
It is just the moment the provided API are not enough, the only think left in the permission model is full access.

The current thinks done via the privileged code are:
- extending the header to show the DKIM result
- DNS queries
- getting access to the settings from older add-on versions
- storing the DKIM result for a mail
- calling some Thunderbird internal utility code 

> I'm not willing to update at the moment.

Again, the older version had in older TB version (there it still worked), like any other add-on, the exact same permissions you are now no longer willing to give. It is just that Thunderbird never that explicitly mentioned it on installation.

And most importantly, like written on the support site I linked too:
> Add-ons published to addons.thunderbird.net (ATN) are subject to human review.

So there is at least a second independent person checking that the add-on is not doing anything malicious.

As no review is perfect, you of course still need to trust the author of an add-on to a certain extend.
But that applied to the old version of the add-on you installed too.

**Comment by hawran** [comment]
> Although I understand your curiosity about the permissions, I get the feeling you didn't really understand the linked explanation.
> ...


Hi lieser, thank you for an exhaustive explanation.
(and sorry for bothering)

**Comment by lieser** [comment]
No problem, good to know your question are answered.

Will leave this open as a reminder to add the permission explanation to the FAQ in the wiki.

**Comment by lieser** [comment]
added the info to the FAQ: https://github.com/lieser/dkim_verifier/wiki/FAQ#why-does-the-add-on-need-full-unrestricted-access-to-thunderbird
