### ISSUE TITLE
Backporting latest fixes to version 2.2.0

### ISSUE THREAD

**Issue by dodmi** [lieser/dkim_verifier#251]
Hi @lieser,
I'm referring to https://github.com/lieser/dkim_verifier/discussions/250#discussioncomment-602339
I had a look at the three relevant commits. 

ARH: fixed missing reason on fail resulting in error https://github.com/lieser/dkim_verifier/commit/8e7241731ede0fced0d9b56d3ddee94f2e5ef004 was pretty straight forward, I've included these changes in my local version, at the moment.

As you wrote, you'd like to host it here, I'd like to ask, how we should do it? Do you just want the XPI file or will you create a "version 2.2.0 branch" (maybe better called TB52 branch, as the version may change) on which I can create separate pull requests with the changes?

At the moment, I've two, 
- the above mentioned backport 
- a patch of my own for users of the charamel/silvermel theme: There already is a neutral contact icon left of the sender address, so I replace the contact icon with the favicon and don't display DKIM Verifier's own icon in case the favicon should be displayed

**Comment by lieser** [comment]
> As you wrote, you'd like to host it here

Note that it is totally up to you if you want to take the additional effort of getting it hosted here. I just wanted to offer the possibility to you, so that hopefully some others can benefit from your efforts.

If I will host it, I also want to see (and review) the code. I just now pushed a `2.x` branch (which already incudes #193, #197) so you can create pull request for it.

**Comment by dodmi** [comment]
Actually, I'm quite happy with your offer.
Yes, there was some initial additional work now, to get it all sorted out and do the git stuff to create separate pull requests, but on the other side, it would definitely take much more time without your help at pointing at the relevant commits. And with your review, I'm confident, that I didn't miss anything.
As long as your interested to provide a TB52 version and I'm unwilling to upgrade because of other addons, it seems to be a win/win situation

**Comment by dodmi** [comment]
You have pull requests

**Comment by lieser** [comment]
Thanks a lot for the pull requests. Some small comments on two, but otherwise they look good.

I will reopen this issue for now, as a reminder to finalize and publish a 2.2.1 version.
If you want to be credited as someone else than `dodmi` in the changelog, please let me know.

**Comment by lieser** [comment]
I just created a 2.2.1 release: https://github.com/lieser/dkim_verifier/releases/tag/v2.2.1

Thanks for your effort, and lets hope some people will see and switch to it also without the automatic update
