### ISSUE TITLE
Signature valid (mailhost) and invalid (DKIM verifier)

### ISSUE THREAD

**Issue by Frank071** [lieser/dkim_verifier#258]
Experiencing a strange issue. Mail from one of my contacts is shown by DKIM verifier as having an invalid signature. Yet the mailserver that receives this email (my side) does mark it as valid. Is this due to some functionality missing?

This is the DKIM signature header (signature clipped):

```
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple;
  d=rws.nl; i=@rws.nl; l=67664; q=dns/txt;
  s=rwsgebruikers; t=1619776671; x=1651312671;
  h=from:to:subject:date:message-id:mime-version;
  bh=...=;
  b=...==;
```

**Comment by lieser** [comment]
You mean the Authentication-Results header (ARH) added by your mailhost shows a valid DKIM signature?

Unfortunately mail server sometimes do change an email slightly. As this breaks DKIM, they do their own DKIM verification before it, which results than in the behavior you see:
Server reports valid DKIM, but the add-ons verification fails.

https://github.com/lieser/dkim_verifier/wiki/FAQ#all-or-almost-all-e-mails-with-dkim-signature-are-failing-with-the-same-error contains a list of server known to me to do this.

If you are affected by this, all you can do is enable reading of the ARH. Note that you can also configure in the advanced options to show both the ARH and the add-ons own verification.

Of course it could also be an error in the add-on. Two ways to test this would be:
1. Use another local verifier, e.g. `dkimverify` from [dkimpy](https://pypi.org/project/dkimpy/)
   - If you do not know how to do that, you can also send me the eml file via mail to check it
2. Ask your contact to send a mail to you and another provider that is not know to change mails (e.g. GMail). Note that it should really be a single mail with multiple recipients, not just the same content in two similar mails. Then save both received mails as a eml file, and compare them (best with a diff tool).

**Comment by Frank071** [comment]
There are two headers that show DKIM verification
```
Authentication-Results: xs4all.nl; spf=pass smtp.mailfrom=rws.nl; dkim=pass
	header.i=@rws.nl; dmarc=pass header.from=rws.nl
...
X-XS4ALL-Spam-Score: -0.2 () DKIM_SIGNED, DKIM_VALID, DKIM_VALID_AU,
	DKIM_VALID_EF, HTML_MESSAGE, SPF_PASS
```
This is not a case of 'all or almost all emails are failing', most are not (but from this domain most part does...) -  I checked with dkimverify and concurs with DKIM verifier. I'll send you the email anyhow, perhaps it'l bring us something.

**Comment by lieser** [comment]
As the verification of the signature itself fails, the problem should be with one of the signed header: `from:to:subject:date:message-id:mime-version`.

As I found the mixed tabs/space usage in the To header strange, I was able to find out what changed by try and error:

Received To:
```
To: "name1" <addr1>,
        "name2"
<tab><addr2>,
        "name3" <addr3>
```
Original To:
```
To: "name1" <addr1>, "name2"
<tab><addr2>, "name3" <addr3>
```

Seems like the receiving server does not like it if there is no line break after the `,`. Could also be a line length limit, but I find the lines a little short for that, especially the first one.

**Comment by Frank071** [comment]
Hi Philippe,

Interesting find... Well... not so much we can do about this. Strange that
this happens at server level. Don't really know why the header should be
folded either.

Thanks for diving into this.

Kind regards,
Frank



Op di 4 mei 2021 om 00:09 schreef Philippe Lieser ***@***.***

**Comment by lieser** [comment]
You could try to report it you mail server and ask why they change incoming mail. Maybe they will change the behavior, one never knows.

Will close the issue, as I think your questions are now answered. If not please reopen the issue.
