### ISSUE TITLE
Does not work with private browsing enabled (Variable name "browser" not defined)

### ISSUE THREAD

**Issue by egberts** [lieser/dkim_verifier#259]
Thunderbird 78.10.1
dkim_verifier 4.0.0
No other Add-On plugins.

The buttons are not highlighted nor filled in with text labels; just four empty buttons.

<img width="104" alt="Screen Shot 2021-05-12 at 8 46 30 AM" src="https://user-images.githubusercontent.com/10352354/117977309-338aec80-b320-11eb-833b-91b3a8f23f93.png">

Error console shows:
```
Error: BaseContext attempted to load when extension is not allowed due to incognito settings. ExtensionCommon.jsm:516:13
    setContentWindow resource://gre/modules/ExtensionCommon.jsm:516
    ExtensionBaseContextChild resource://gre/modules/ExtensionPageChild.jsm:182
    ExtensionPageContextChild resource://gre/modules/ExtensionPageChild.jsm:300
    initExtensionContext resource://gre/modules/ExtensionPageChild.jsm:475
    initExtensionContext chrome://messenger/content/parent/ext-mail.js:113
    initExtensionDocument resource://gre/modules/ExtensionProcessScript.jsm:391
Uncaught ReferenceError: browser is not defined
    <anonymous> moz-extension://263d55c8-e272-1645-bd5e-42512c5e1dfa/content/translation.mjs.js:22
translation.mjs.js:22:4
    <anonymous> moz-extension://263d55c8-e272-1645-bd5e-42512c5e1dfa/content/translation.mjs.js:22
Uncaught (in promise) ReferenceError: browser is not defined
    getCurrentTabId moz-extension://263d55c8-e272-1645-bd5e-42512c5e1dfa/content/displayAction.mjs.js:18
    queryButtonState moz-extension://263d55c8-e272-1645-bd5e-42512c5e1dfa/content/displayAction.mjs.js:52
    <anonymous> moz-extension://263d55c8-e272-1645-bd5e-42512c5e1dfa/content/displayAction.mjs.js:65
displayAction.mjs.js:18:14

```

**Comment by lieser** [comment]
Judging from the error message, it seems to be related to Firefox's incognito mode. Do you remember setting anything in Thunderbird related to it?

**Comment by egberts** [comment]
Not running Firefox.
Just Mozilla Thunderbird.
I don't think I understand the question.  Just reporting the error.

**Comment by lieser** [comment]
I found a way to allow the add-on in private mode if you want to keep the `browser.privatebrowsing.autostart` setting to true:

1. Close Thunderbird
2. Open `extension-preferences.json` in your profile folder
3. add `,"dkim_verifier@pl":{"permissions":["internal:privateBrowsingAllowed"],"origins":[]}` to the json file before the closing `}` at the end

I would still recommend to disable `browser.privatebrowsing.autostart` if that change was not fully intentional.

**Comment by egberts** [comment]
Setting `browser.privatebrowsing.autostart` to **`false`** fixes this problem and results in show a fully filled out 4-button labels.

Thank you for the clarification, and a prompt one too.

Closing this issue.

**Comment by lieser** [comment]
Just that is it not getting lost, my old findings below:

- the code mentions an `extensions.allowPrivateBrowsingByDefault` preference, which unfortunately does not work https://searchfox.org/mozilla-central/source/toolkit/components/extensions/WebExtensionPolicy.cpp#159
- extensions can have an internal `internal:privateBrowsingAllowed` preference
- the Firefox UI sets the preference with the `ExtensionPermissions` module https://searchfox.org/mozilla-central/source/browser/modules/ExtensionsUI.jsm#558
- using that module from the error console with `ExtensionPermissions = ChromeUtils.import("resource://gre/modules/ExtensionPermissions.jsm").ExtensionPermissions` did not work for me
- I could manually edit `extension-preferences.json` file in my profile folder and add `,"dkim_verifier@pl":{"permissions":["internal:privateBrowsingAllowed"],"origins":[]}` to make the extension work in private mode
