### ISSUE TITLE
Show SPF and DMARC data even if there is no DKIM signature

### ISSUE THREAD

**Issue by rastersoft** [lieser/dkim_verifier#272]
I'm testing this extension and looks great, but I see that it only seems to show DMARC and SPF data when there is a DKIM signature. Is it possible to always show SPF and DMARC data?

**Comment by lieser** [comment]
Have you tried setting the `Show DKIM header` option to `when an e-mail is viewed`? Maybe not exactly what you want, as it will also show the header if no SPF and DMARC data is available, but I guess you would have at almost all mails at least DMARC none anyway.

**Comment by lieser** [comment]
Closing as I assume changing the setting achieved what you wanted.
If not feel free to reopen the issue.
