### ISSUE TITLE
How to add dkim key to my mails?

### ISSUE THREAD

**Issue by tykazzz** [lieser/dkim_verifier#273]

**Comment by tykazzz** [comment]
I mean DKIM signature, I want to add DKIM signature, I've already configured DKIM in DNS.

**Comment by lieser** [comment]
If I understand you correctly, you are talking about signing outgoing mails with DKIM? This is not something the addon provides. See also #89.
You need to configure DKIM in the mail server you use, but that is not something I can help with.
