### ISSUE TITLE
More DKIM icons

### ISSUE THREAD

**Issue by mortenn** [lieser/dkim_verifier#274]
Kind of tooting my own horn this time, but here's a couple more domains I would like to see added:

flytit.no https://www.flytit.no/Static/img/logo100.png
hapro.no https://helpdesk.hapro.no/favicon.ico

(full disclosure: I am a current employee of FlytIT and a former employee of Hapro, and the one implementing DKIM for these domains)

**Comment by lieser** [comment]
Thanks for the additional information. Added the icons and rules for both domains.
