### ISSUE TITLE
DKIM verification creates huge UI lag

### ISSUE THREAD

**Issue by pbondoer** [lieser/dkim_verifier#275]
When DKIM verification is enabled, I'm getting huge lag spikes in the UI (multiple seconds of unresponsiveness) while the signatures are resolving. Is there something that can be done to alleviate this problem?

Disabling the extension gets rid of the lag spikes.

I'm on Thunderbird 78.13.0 (64-bit) on Windows 11 (dev channel), and I also have Enigmail and Sieve extensions installed.

Please let me know if there's anything else I can provide to assist / any debugging I could do? I'm fairly new to Thunderbird extensions but happy to learn and help in any way I can.

**Comment by lieser** [comment]
Thanks for reporting. Unfortunately I don't have much experience with debugging performance issues. And although for me the Thunderbird GUI freezes sometimes too, I have the same issues with the DKIM addon disabled. So unfortunately can not reproduce this.

Could you please answer the following:
- Do I understand it correctly, that you only have the GUI freeze between selecting an e-mail for viewing, and until the addon shows a verification result?
- Does this happen with every mail, or do you see a correlation with the size of the viewed mail?
- Does storing the DKIM keys make a difference? https://github.com/lieser/dkim_verifier/wiki/Options#caching-of-the-dkim-keys
- Can you enabled debugging in the advanced log, and post or send me the output of a verification there the GUI froze for a long time (https://github.com/lieser/dkim_verifier/wiki/Debug#view-error-and-debug-messages)? The timestamps of the log are important, as I want to see if there is a long delay between two debug messages, You may need to enable showing them under the gear icon in the upper right corner.
- Does saving the DKIM result make a difference? https://github.com/lieser/dkim_verifier/wiki/Options#save-result-of-the-verification

**Comment by pbondoer** [comment]
Thanks for the prompt reply. After further testing it seems the freezes are unrelated to the DKIM addon. I have uninstalled it for multiple days and it seems to be back (and pretty sporadic)... seems like a Thunderbird issue. Sorry for the confusion.
