### ISSUE TITLE
All mail marked "DKIM internal error"

### ISSUE THREAD

**Issue by counterpoint** [lieser/dkim_verifier#285]
All mail is showing "DKIM Internal eror". Running verifier 4.0.0 in Thunderbird 78.14.0 on Linux Mint 20.2 Cinnamon. Error console shows many entries:
DKIM_Verifier.background	FATAL	 Unexpected error during onMessageDisplayed Error: An unexpected error occurred background.mjs.js:173:7
Anything I can do?

**Comment by lieser** [comment]
Unfortunately the error message doesn't really say anything. Most of the times I encountered this error meant that something inside Thunderbird itself did go wrong. Often with the storage there the addon saves it's data.

If you still have the problem, you could try the following:
1. See if there are any over errors reported in the error log.
2. Disable all over addons (and restart Thunderbird)
3. Remove the addon. Restart Thunderbird. Re-add the addon. **Note that all data of the addon (options, sign rules) will be lost!**

If non of the above helps. If you enable debugging in the advanced options, are there any log messages shown before the error?

**Comment by lieser** [comment]
Closing this for now.
Please let me know and reopen the issue if you still have this problem.

**Comment by joootdooot** [comment]
I had the same error but it went away after changing some settings back and forth, perhaps it was an error with how the config is stored.

**Comment by lieser** [comment]
@joootdooot Thanks for letting me know. Did you take a look at Thunderbird's error console to see that is was `An unexpected error occurred` too?
If yes you are probably correct and it was some strange error with the stored data. Often they disappear by them self again.

If it was something different or you did not look, please check Thunderbird's error console (https://github.com/lieser/dkim_verifier/wiki/Debug#view-error-and-debug-messages) the next time.
And report the error with the additional information provided, best in a new issue unless you see a related open one.
