### ISSUE TITLE
DKIM can not be verified on some emails (4.1.0)

### ISSUE THREAD

**Issue by xsistema** [lieser/dkim_verifier#293]
Just installed 4.1.0 version on Win10 64-bit, and noticed that DKIM can not be verified on some emails (DKIM label is blank). Error:

```
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
[displayAction.mjs.js:45](moz-extension://de74144d-d2f9-4200-ab3a-2f2f0882710e/content/displayAction.mjs.js)
    triggerDisplayAction moz-extension://de74144d-d2f9-4200-ab3a-2f2f0882710e/content/displayAction.mjs.js:45
DKIM_Verifier.AuthVerifier	DEBUG	 reset AuthResult result [authVerifier.mjs.js:316:7](moz-extension://de74144d-d2f9-4200-ab3a-2f2f0882710e/modules/authVerifier.mjs.js)
DKIM_Verifier.SignRules	DEBUG	 shouldBeSigned:  
Object { shouldBeSigned: false, sdid: [], foundRule: false, hideFail: false }
[signRules.mjs.js:462:7](moz-extension://de74144d-d2f9-4200-ab3a-2f2f0882710e/modules/dkim/signRules.mjs.js)
DKIM_Verifier.AuthVerifier	DEBUG	 save AuthResult result [authVerifier.mjs.js:322:7](moz-extension://de74144d-d2f9-4200-ab3a-2f2f0882710e/modules/authVerifier.mjs.js)
DKIM_Verifier.AuthVerifier	DEBUG	 authResult:  
Object { version: "2.1", dkim: (1) […] }
[authVerifier.mjs.js:202:7](moz-extension://de74144d-d2f9-4200-ab3a-2f2f0882710e/modules/authVerifier.mjs.js)
```

**Comment by lieser** [comment]
Thanks for reporting. Unfortunately don't see what could actually go wrong.

The only error I see in the log you posted is `Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved`. But for code that:
- Did not change in 4.1.0 (compared to 4.0.0)
- Is for the popup in the DKIM button of the email header. It should not run unless you open the popup and click a button.

Could you please try/answer the following:

- Does the error still occur after a restart of Thunderbird?
- Does it always happen with the same messages?
- Which Thunderbird version are you using?
- Which addon version there you using before?

**Comment by xsistema** [comment]
After restarting TB 97.0b3 - problem disappeared.  But if email does not contain DKIM signature - the line is blank, though occupies some vertical space. Is it by default? I think it should be a message - no DKIM or similar. At error console:

`DKIM_Verifier.AuthVerifier	DEBUG	 AuthResult result found:  {"version":"3.0","dkim":[{"version":"2.0","result":"none"}]}`

**Comment by lieser** [comment]
No, the blank line is a bug in the addon. Unsure if that is something new, or if I missed it in TB 96. Should be fixed now.

Will wait with releasing a new version in case more bugs are reported. Attached a new version here.
[dkim_verifier@pl-1d8edf3.zip](https://github.com/lieser/dkim_verifier/files/8010431/dkim_verifier%40pl-1d8edf3.zip)
