### ISSUE TITLE
The "Add signers rule" window is too small

### ISSUE THREAD

**Issue by Mr-Update** [lieser/dkim_verifier#296]
Please enlarge the window "Add signers rule".

The translation of "Rule type" is too long for one line together with the drop-down list in most languages.

Tested with Thunderbird 91.6.0 under Ubuntu 20.04 LTS and Windows 10 21H1.

![Ubuntu 20 04 en](https://user-images.githubusercontent.com/37781396/153678934-fccdcb8f-a991-41e3-a4a7-c1cb7ab9d080.png)

![Ubuntu 20 04](https://user-images.githubusercontent.com/37781396/153678945-502b504b-1ba6-448d-9b27-9a2674225338.png)

![Windows 10 en](https://user-images.githubusercontent.com/37781396/153678967-857286c1-990a-4901-a757-16b15aa04c79.png)

![Windows 10](https://user-images.githubusercontent.com/37781396/153678973-46554267-7ce1-470b-855d-d92757601213.png)

**Comment by lieser** [comment]
Thanks for reporting. Will increase the dialog size in the next release.

**Comment by lieser** [comment]
The *Add signers rule* window is now bigger. I also increased the size of the *Signers rules* table view, so the buttons are shown in one row.
