### ISSUE TITLE
Add icon for microsoftsupport.com

### ISSUE THREAD

**Issue by mortenn** [lieser/dkim_verifier#298]
Please add icon for microsoftsupport.com
https://c.s-microsoft.com/favicon.ico?v2

Snippet from a validated email earlier today:
```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoftsupport.com;
 s=selector1;
 ...
From: ... <...@microsoftsupport.com>
```

They do not have a website on that domain, but I can confirm this is the real support department of Microsoft.
As they helped me resolve an issue on the backend of dev.azure.com after I contacted them through Crayon.

**Comment by lieser** [comment]
Sorry for the late response. Added `microsoftsupport.com` to the icons and rules.
