### ISSUE TITLE
From address is ill formed.  Really?

### ISSUE THREAD

**Issue by alevesely** [lieser/dkim_verifier#304]
`From: Alessandro Vesely <vesely@tana.it>, 2nd name <user@example.com>`

I think the add-on complaints about multiple mailboxes, which are allowed by RFC5322.  It displays **From address is ill formed**.  (For obscure reasons, DMARC does not consider this case, but DKIM says nothing about that, IIRC).  The Authentication-Results: header said **dkim=pass**.  Error console says:
```
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved [displayAction.mjs.js:45](moz-extension://694bf5d4-0ccd-4013-88d6-a4fdb3a218aa/content/displayAction.mjs.js)
    triggerDisplayAction moz-extension://694bf5d4-0ccd-4013-88d6-a4fdb3a218aa/content/displayAction.mjs.js:45

DKIM_Verifier.AuthVerifier	ERROR	 Parsing of from header failed <unavailable> [authVerifier.mjs.js:133:8](moz-extension://694bf5d4-0ccd-4013-88d6-a4fdb3a218aa/modules/authVerifier.mjs.js)
    verify moz-extension://694bf5d4-0ccd-4013-88d6-a4fdb3a218aa/modules/authVerifier.mjs.js:133
​

**Comment by lieser** [comment]
The From header is probably valid, as not handling `mailbox-list` is a known limitation.
Never saw such an headed, so hoped I could get away with not handling it.

Will try to fix this in the next version.

**Comment by lieser** [comment]
The issue should be fixed. Note that I decided to simply ignore all but the first address for e.g. the sign rules. By default Thunderbird seems to also only display the first address.

**Comment by alevesely** [comment]
I agree that's the simplest way to treat it.  Some argue that, in the rare cases where multiple authorship is needed, the order can be important.  In such cases, it is necessary that the message be actually sent by the first author.

Thanks for the fix.
