### ISSUE TITLE
Ability to 'mass delete' cached DKIM keys

### ISSUE THREAD

**Issue by mdavids** [lieser/dkim_verifier#305]
Over the past few years the add-on collected many DKIM keys, but there sees to be no good way of cleaning things up in one go.

I can only select one key at a time and then choose 'delete selected keys'.

And the same applies for the signers rules database. 

Would be great if this can be fixed.

Also additional features, such as the ability to sort on columns (like the 'last used' column) would be very useful.

**Comment by lieser** [comment]
Thanks for the suggestion. The current tables certainly could benefit from some improvements. See also #248.

As a workaround:
- For the signers rules you could use the export, manually modify the json, and then import them again (replacing the existing rules).
- For the keys you could use Thunderbird's debugging features to manually interact with the storage, and e.g. delete all stored keys. Deleting some would be harder. Let me know if I should elaborate on that.

**Comment by mdavids** [comment]
This sounds complicated, I still miss a handy way of selecting all or many keys and then 'mass delete' them.

**Comment by lieser** [comment]
> Am I doing something wrong?

No you are not, you are just encountering a bad GUI 😅.
I will try to look into it before the next release, and if not to much work will implement the deletion of multiple keys. But no promises.

**Comment by lieser** [comment]
I'm currently trying out switching to the [Tabulator](https://tabulator.info) library for rendering the tables.
I'm not 100% happy with it, but it has a few advantages like being able to select multiple rows, making the requested mask delete a lot easier.

@mdavids  Would be nice if you could try out the attached version and give feedback.
[dkim_verifier@pl-2024-01-08-49c77b4.zip](https://github.com/lieser/dkim_verifier/files/13866906/dkim_verifier%40pl-2024-01-08-49c77b4.zip)
