### ISSUE TITLE
DKIM Verifier 4.1.1 "eats" the complete header panel, when switching to an other folder

### ISSUE THREAD

**Issue by ThunderbirdMailDE** [lieser/dkim_verifier#306]
This issue occurs (at least) in latest Daily builds - maybe due to the massive code changes in header area.

The related error in console could be this:
`can't access property "firstChild", expandedFromBox.emailAddresses is undefined` in file `[dkimHeader.js:690]`

**Comment by lieser** [comment]
Thanks for reporting, will try to fix this in the next days.

**Comment by lieser** [comment]
The addon should now work again with the latest daily (*102.0a1 (2022-05-29)*). Hopefully there will be no more breaking changes in the 102 release.

Attached is a fixed version:
[dkim_verifier@pl-23b7691.zip](https://github.com/lieser/dkim_verifier/files/8793565/dkim_verifier%40pl-23b7691.zip)

I noticed that the From tooltip is also broken. I opened another issue to track that: #311.

**Comment by ThunderbirdMailDE** [comment]
Phillipe, where are the colors gone, which have been indicating the DKIM status?

**Comment by lieser** [comment]
> Phillipe, where are the colors gone, which have been indicating the DKIM status?

The highlighting of the from address should still work. Please make sure you have that still enabled. E.g. if you removed the non working addon (and then restarted TB), and not just disabled it, unfortunately all your preferences are gone.
