### ISSUE TITLE
Highlighting the from address fails

### ISSUE THREAD

**Issue by ThunderbirdMailDE** [lieser/dkim_verifier#312]
Highlighting the from address fails, when the option "Allways show sender's full address" is enabled in the new built-in "Customize" header. The new "Customize" dialog can be opened from the little down arrow menu in message header.

![image](https://user-images.githubusercontent.com/47142502/170935000-01917e50-f3af-4aaf-a88b-6835718d3ef3.png)

**Comment by lieser** [comment]
Thanks for not only reporting the issue, but also finding the responsible option.
Attached is a fixed version:
[dkim_verifier@pl-5660c6c.zip](https://github.com/lieser/dkim_verifier/files/8800777/dkim_verifier%40pl-5660c6c.zip)
