### ISSUE TITLE
Additional Icons

### ISSUE THREAD

**Issue by Rimole** [lieser/dkim_verifier#327]
From: info@mail.lidlplus.de		Signed by: mail.lidlplus.de		Icon: https://www.lidl.de/cdn/assets/logos/1.0.1/favicon-32x32.png or ...16x16

From: no-reply@mein-grundeinkommen.de	Signed by: mein-grundeinkommen.de	Icon: https://www.mein-grundeinkommen.de/favicon-32x32.png or ...16x16

From: info@reply.deutschlandcard.de	Signed by: reply.deutschlandcard.de	Icon: https://www.deutschlandcard.de/favicon/favicon-32x32.png or ...16x16

From: postmaster@reply.quoka.de		Signed by: reply.quoka.de		Icon: https://www.quoka.de/img/quoka/favicon.ico

From: newsletter@payback.de		Signed by: payback.de			Icon: https://www.payback.de/resource/blob/4506/9907db6356ea7c60c3c36d353e2cee5f/main-favicon.ico

From: veeb@eestipank.ee			Signed by: eestipank.ee			Icon: https://www.eestipank.ee/favicon.ico

From: info@weact.de			Signed by: weact.de			Icon:  https://weact.campact.de/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8d9fa84b8932b7b78266c1990371a97815bef635/weact-favicon.ico

Please note that the used zeit.de SVG-icon does not work (scg-error). New icon at: 
https://static.zeit.de/p/zeit.web/icons/favicon.ico

Thank you very much!

**Comment by lieser** [comment]
Thanks for the entries, I will add them.

A question about the zeit.de SVG-icon:
Which Thunderbird version are you using? For me both in TB 91 and 104 the icon works.

**Comment by Rimole** [comment]
Thank you for looking into this! I looked at the assortment of provided icons with an external viewer, and only the Zeit icon threw an error.Thus, it might even work with Thunderbird. Either there is an issue with the icon and Thunderbird is able to handle it nevertheless, or the icon is OK for a certain set of rules and the other viewer does not work with that version of rules. The icon might work also with future versions of Thunderbird, or it might break. Therefore the suggestion to replace it with a more "standard" version.

**Comment by lieser** [comment]
Updated the icons and rules.

Note that I decided to stay with the zeit.de SVG-icon for now. Didn't see anything that is wrong with it, and Thunderbird an Firefox also do not show any warnings for it.
Is the viewer you are using saying anything more specific than just *scg-error*?
