### ISSUE TITLE
Favicon not shown for local PayPal domains (paypal.de, etc.)

### ISSUE THREAD

**Issue by tbertels** [lieser/dkim_verifier#334]
PayPal uses many country code TLDs (ccTLD):
See https://www.xolphin.com/sslcheck/paypal.de fo the full list

DKIM Verifier could show the PayPal favicon for them as well.

The main ones could be added:

> paypal.at
paypal.be
paypal.ca
paypal.ch
paypal.cl
paypal.cn
paypal.co
paypal.co.id
paypal.co.il
paypal.co.in
paypal.co.kr
paypal.co.nz
paypal.co.th
paypal.co.uk
paypal.co.za
paypal.com.ar
paypal.com.au
paypal.com.br
paypal.com.hk
paypal.com.mx
paypal.com.my
paypal.com.pe
paypal.com.pt
paypal.com.sa
paypal.com.sg
paypal.com.tr
paypal.com.tw
paypal.com.ve
paypal.de
paypal.dk
paypal.es
paypal.eu
paypal.fi
paypal.fr
paypal.ie
paypal.in
paypal.it
paypal.jp
paypal.lu
paypal.nl
paypal.no
paypal.ph
paypal.pl
paypal.pt
paypal.ru
paypal.se
paypal.vn

**Comment by lieser** [comment]
I did not want to randomly add PayPal also for other top level domains without knowing that PayPal is actually using them.
But thanks for suggesting to use the information included in the certificate PayPal is using for this. I think this is a good idea, will probably add most of them in the next release.

**Comment by lieser** [comment]
Added a lot more local PayPal domains in a90433996de26657b97c4ec4aec313a4eec10680.
