### ISSUE TITLE
Further Icons

### ISSUE THREAD

**Issue by Rimole** [lieser/dkim_verifier#337]
I collected some other domains which send me signed mails but had no associated icon in your add-on:

Signed by: Icon:
scv.va https://www.vaticanstate.va/images/favicon.png or https://www.vaticanstate.va/favicon.ico

listen.uni-bonn.de https://listen.uni-bonn.de/ubn-content/favicon.ico

researchgatemail.net https://explore.researchgate.net/download/attachments/557057/atl.site.logo?version=7&modificationDate=1567009946639&api=v2

edv-buchversand.de https://www.edv-buchversand.de/favicon.ico

omnivea.ee https://www.omniva.ee/img/favicon.png

rettet-das-melbbad.de https://www.rettet-das-melbbad.de/wp-content/uploads/2020/08/cropped-i-love-melbbad-32x32.jpg

mail.iherb.com https://s3.images-iherb.com/static/i/favicon-iherb/favicon.ico

jobagent.stepstone.de https://www.stepstone.de/modules/duplo/resources/favicons/stepstone/apple-touch-icon-57x57.png?v=VuWeZv6r

mail.xing.com https://faq.xing.com/themes/custom/xingskin/favicon.ico

e-mai.xing.com https://faq.xing.com/themes/custom/xingskin/favicon.ico

sparkasse-koelnbonn.de https://www.sparkasse-koelnbonn.de/content/dam/myif/sk-koelnbonn/work/bilder/icons/favicon1x.png

loox.io https://global-uploads.webflow.com/5ffa9cb466ed902ac6f8fffc/606492a89e43d4725e0a7a09_Fav.png

mailings.web.de https://img.ui-portal.de/webde/favicon.ico

trustedshops.com https://www.trustedshops.com/static/icons/favicon.ico

groupes.renater.fr https://groupes.renater.fr/static-sympa/icons/favicon_sympa.png

PSU.EDU https://www.psu.edu/favicon.ico

**Comment by lieser** [comment]
Thanks for the list will look at it more closely in the next weeks.

One think I already noticed is `mailings.web.de`. Can you please confirm that only messages from Web.de the company are signed with this

**Comment by Rimole** [comment]
Newly discovered signed e-mails from:

innn.it https://innn.it/favicon-32.png

profamilia.de https://www.profamilia.de/fileadmin/tmpl/Resources/Public/img/favicon.ico

muenze-deutschland.de	https://www.muenze-deutschland.de/typo3conf/ext/krag_muenze_template/Resources/Public/Icons/Favicons/favicon_32x32.png

e-mail.xing.com https://faq.xing.com/themes/custom/xingskin/favicon.ico
(they corrected their typing mistake "e-mai" -> e-mail, i.e. no longer signed by e-mai.xing.com)

mail.xing.com https://faq.xing.com/themes/custom/xingskin/favicon.ico
(OK, if they keep changing their sign daily, we should just ignore xing)

uni-koeln.de	https://uni-koeln.de/img/icons/favicons/uzk/favicon-32x32.png

**Comment by Rimole** [comment]
iherb.com same as mail.iherb.com https://s3.images-iherb.com/static/i/favicon-iherb/favicon.ico

service.fressnapf.de https://www.fressnapf.de/favicon.ico

letsencrypt.org https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://letsencrypt.org&size=32

**Comment by lieser** [comment]
Thanks for the additional domains.

Can you please answer my question about web.de I asked in my first comment? Thanks.

**Comment by Rimole** [comment]
> One think I already noticed is `mailings.web.de`. Can you please confirm that only messages from Web.de the company are signed with this domain, e.g. news letters? And not messages send by people who just use web.de as their mail provider.

Obviously my answer via e-mail has been eaten up by some hungry mail daemon...
Thus:
Mails by users are signed by "web.de", while newsletters and such from web.de themselves are signed by "mailings.web.de" (might use some additionals something.web.de, but at least mailings.web.de is the company and not a customer).

**Comment by Rimole** [comment]
hosttest.de https://www.hosttest.de/assets/img/base/favicon.ico

lists.egu.eu https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.egu.eu&size=32

quokamail.de https://www.quoka.de/img/quoka/favicon.ico

fressnapf.com same as service.fressnapf.de https://www.fressnapf.de/favicon.ico

lima-city.de https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url= https://www.lima-city.de&size=32

doctolib.de https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.doctolib.de&size=32

**Comment by lieser** [comment]
Currently taking a closer look at the domains.

As you are only listing the signing domain (SDID), and not the from address, I will assume that the domain of the from address was always the same as the SDID.
Please let me know if that is not the case for one of the domains.

**Comment by lieser** [comment]
Added icons and rules for the domains.

Note that:
- I assumed `omnivea.ee` is a typo for `omniva.ee`
- For `renater.fr`/`groupes.renater.fr` I used the icon of the `renater.fr` domain. The one you linked seems to be for the groupes software they use.

I will leave this issue open until the next release in case you still have more domains.

**Comment by Rimole** [comment]
> As you are only listing the signing domain (SDID), and not the from address, I will assume that the domain of the from address was always the same as the SDID.

That is right.

> I assumed omnivea.ee is a typo for omniva.ee

Yes, sorry.

> For renater.fr/groupes.renater.fr I used the icon of the renater.fr domain. The one you linked seems to be for the groupes software they use.

Makes sense.

Thank you!

**Comment by Rimole** [comment]
Encountered another one - DKIM really sees more use now!
stadt-koeln.de   https://www.stadt-koeln.de/images/x22/logo-adler-stadt-koeln.png
(which probably needs some downsizing)

**Comment by lieser** [comment]
Added icons and rules for the additional domains.

**Comment by Rimole** [comment]
And additionally:

redditmail.com https://www.redditstatic.com/desktop2x/img/favicon/favicon-32x32.png
 or ...16x16.png or ...96*96.png

newsletter.lindt.com https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://lindt.com&size=32

accounts.bitly.com https://docrdsfx76ssb.cloudfront.net/static/1668710162/pages/wp-content/uploads/2019/02/favicon.ico

ctan.org https://ctan.org/assets/favicon/favicon-afd4a866cd0c27587b7b06cd4199a57f.ico

mail.plr.bl.uk https://plr.bl.uk/favicon.ico
 is not small but tiny, https://www.bl.uk/britishlibrary/resources/global/images/bl_logo_100.gif
 is a larger version

pdg.lbl.gov https://pdg.lbl.gov/2022/images/favicon.png

koelnalumni.de https://alumni.uni-koeln.de/sites/alumni/user_upload/Seitenkopf_Logo_KoelnAlumni/KoelnAlumni_180_72_Trans_200_200.png - but probably it is better to use the symbol without text, because it is otherwise too wide, i.e. it would get scaled down too much

**Comment by lieser** [comment]
Thanks for the additional domains and sry for the late reply. Updated the icons and rules.

> Note: There are some organisations, where mail from "sombody@organization.org" is signed by sign.organization.org, while "newsletter@organization.org" is signed by "mailchimp.app" (for example).

Which domains are this?
To properly write the sign rules I need to know which addresses to treat differently, and by which domain they are signed.

- `koelnalumni.de` - reused `uni-koeln.de.png`, as the website the domain is redirecting to is using that too
- `mail.tnt.com` - only sign rule added (icon seems to be to big, the ones on the website are broken)
- `mailer-daemon@gmx.net` - only rule added, icon needs #107
- `fax-und-voice@web.de` - only rule added, icon needs #107
- `latex.org` - Not added, `gappssmtm.com` does not seem like an official (or even registered) domain
- `interactadvocates.org` - Not added, `gappssmtm.com` does not seem like an official (or even registered) domain

Not added because it is only signed by a general newsletter sender and not the from address:

- `igel-monitor.de` (signed by `amxe.net`)
- `letsencrypt.org` (signed by `zendesk.com`)
- `maltacoincentre.com` (signed by `mailchimpapp.net`)
- `queeres-netzwerk.nrw` (signed by `crsend.com`)
- `apegames.com` (signed by `cmail2.com`)
- `interactadvocates.org` (signed by `mailchimpapp.net`)
- `genderleicht.de` (signed by `mailchimpapp.net`)
- `aufarbeitungskommission.de` (signed by `crsend.com`)
- `fotoparadies.de` (signed by `elaine-asp.de`)
- `sankt-cyprian.de` (signed by `crsend.com`)
- `rarechromo.org` (signed by `auth.ccsend.com`)

**Comment by lieser** [comment]
I noticed that there was just a typo in `gappssmtp.com`, and that it is a domain from Google. As they use a sub domain for each domain they sign on behalf of, I now also added a rule and icon for `latex.org` and `interactadvocates.org`.
