### ISSUE TITLE
Bug: Empty body leads to Internal Error

### ISSUE THREAD

**Issue by Yannik** [lieser/dkim_verifier#347]
Hi,

I'd like to report a bug with this extension: A validly dkim-signed mail with an empty body leads to "internal error" being displayed as verification result.

Yannik

**Comment by lieser** [comment]
Thanks a lot for reporting this.

Currently the addon expects the empty line that is separating the headers and the body to be there. And if not throws an internal error.

I took a closer look at the specification (https://www.rfc-editor.org/rfc/rfc5322#section-3.5) and noticed that the body is actually optional. So the current assumption that the empty line always has to be there is wrong.

I will fix this in the next version. But would be nice if you could confirm that the email causing the issue has a missing body, and not just an empty one.

**Comment by Yannik** [comment]
Yes, I can indeed confirm that is the case. There is no linebreak after the headers.

**Comment by lieser** [comment]
The issue should be fixed now.
