### ISSUE TITLE
"Error connecting to DNS server" after a certain period of time

### ISSUE THREAD

**Issue by Yannik** [lieser/dkim_verifier#362]
Hi,

after a certain amount of time, the plugin always shows `Error connecting to DNS server` for all emails.

This can be fixed by disabling/enabling the extension, or even just disabling/enabling `Get DNS servers from OS configuration`.

My plugin dns config looks like this:
![Screenshot from 2023-04-18 19-46-39](https://user-images.githubusercontent.com/801996/232861336-7a003277-39c3-47da-b0ed-c190f2ae0fd7.png)

I am using systemd-resolved (which is replying to dns requests just fine).

I have enabled `Enable debugging` and `show detailed error reasons`, and have the following error console output:

```
DKIM_Verifier.Verifier	DEBUG	 computed body hash: UaCug3v8n7Js1cl/W/czoiu5Cd7DNq3Ic/DrLQv+H0o= [verifier.mjs.js:1139:7](moz-extension://00068a3c-f15b-46a6-9806-977e48731e08/modules/dkim/verifier.mjs.js)
DKIM_Verifier.JSDNS: no DNS Server alive [JSDNS.jsm.js:540:8](chrome://dkim_verifier_jsdns/content/JSDNS.jsm.js)
WebExtensions: JSDNS failed with: no DNS Server alive [jsdns.js:99](jar:file:///home/yannik/.thunderbird/8aotb2oj.default/extensions/dkim_verifier@pl.xpi!/experiments/jsdns.js)
contentscript: set [content-script.js:94:15](moz-extension://294d7aba-0329-4242-995c-67bd6e264508/scripts/content-script.js)
DKIM_Verifier.KeyStore	DEBUG	 dns result 
Object { data: null, rcode: 2, secure: false, bogus: false }
[keyStore.mjs.js:372:7](moz-extension://00068a3c-f15b-46a6-9806-977e48731e08/modules/dkim/keyStore.mjs.js)
DKIM_Verifier.KeyStore	INFO	 DNS query failed with result: 
Object { data: null, rcode: 2, secure: false, bogus: false }
[keyStore.mjs.js:378:8](moz-extension://00068a3c-f15b-46a6-9806-977e48731e08/modules/dkim/keyStore.mjs.js)
DKIM_Verifier.Verifier	ERROR	 Internal error during DKIM verification: <unavailable> [verifier.mjs.js:1349:8](moz-extension://00068a3c-f15b-46a6-9806-977e48731e08/modules/dkim/verifier.mjs.js)
DKIM_Verifier.Verifier	DEBUG	 Exception on DKIM-Signature 1
```

Unfortunately, this is not very helpful..

@lieser do you have any idea how this could be debugged further? Could you perhaps add some additional debug log messages?

**Comment by lieser** [comment]
Thanks for the detailed report. This is a known issue of the default JavaScript DNS resolver and something I plan trying to improve in the next version.
I initially tried to implement some kind of offline detection (the `no DNS Server alive` in the log) which in hindsight is probably causing more problems than it brings.
For details see #269.

As a workaround you could:
- Switch to the libunbound resolver which does not have this broken offline detection (https://github.com/lieser/dkim_verifier/wiki/DNS#libunbound).
- Enabling caching of the DKIM keys which should reduce the number of needed DNS queries (https://github.com/lieser/dkim_verifier/wiki/Options#caching-of-the-dkim-keys).
- If you stay with the JavaScript DNS resolver change the advanced setting [`dns.jsdns.autoResetServerAlive`](https://github.com/lieser/dkim_verifier/wiki/DNS#dnsjsdnsautoresetserveralive-boolean) to `true` (see https://github.com/lieser/dkim_verifier/wiki/Debug#set-hidden-options on how to do this).

Note that I will close this as a duplicate, but don't hesitate to ask if you have more questions about this,

**Comment by Yannik** [comment]
Hi @lieser,

thanks for the detailed answer!

I have set [dns.jsdns.autoResetServerAlive](https://github.com/lieser/dkim_verifier/wiki/DNS#dnsjsdnsautoresetserveralive-boolean) to true and will further observe this in the future.
