### ISSUE TITLE
Does nothing on message opened from .eml file

### ISSUE THREAD

**Issue by php4fan** [lieser/dkim_verifier#367]
Steps to reproduce:

1. Have a .eml file. This could be a message that you saved from your inbox in Thunderbird with right-click-> "Save As", or a file that you saved from any other source. The result is the same
2. Open this file in Thunderbird. On my linux system, I do this by just double-clicking on the file from Dolphin.

Expected result:
Should show exactly the same information that it shows when you open a message from your inbox. That is, whether the DKIM signature was valid or not (or if it doesn't have a DKIM signatura at all or whatever other information there is to display regarding DKIM).

Observed result:
Absolutely nothing. Regardless of whether the message has a DKIM signature or not, whether it is valid or not, no DKIM information whatsoever is displayed. There is the "DKIM" button, with "Reverify DKIM signature" option (and a few other that are greyed out), but it you click that it does nothing. Doesn't even show an error message, just does nothing.

**Comment by lieser** [comment]
I'm assuming you are using one of the affected Thunderbird version I mentioned. If not please let me know.

Closing as a duplicate for now.
