### ISSUE TITLE
DKIM DNS record as a CNAME

### ISSUE THREAD

**Issue by tekvsakdan** [lieser/dkim_verifier#368]
Our organisation is using Office 365 and we have enabled DKIM. DKIM DNS record is stored at Microsoft DNS server. 
Following the [instructions](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/email-authentication-dkim-configure?view=o365-worldwide) from Outlook, we created a CNAME record in our domain DNS, which points to a record on the MS DNS server.

`selector1._domainkey.organisation.com CNAME selector1-organisation.com0i._domainkey.organisationcom.onmicrosoft.com`

When we tried to test DKIM we get the error No DKIM key found in DNS server. I guess the verifier doesn't follow CNAME. Can this be integrated into addon? We cannot copy key from MS DNS because the key is rotating and we should do this manually.

**Comment by lieser** [comment]
> I guess the verifier doesn't follow CNAME

Correct the *JavaScript DNS library* is not following CNAME. But it has partial support for it, in the sense that it ignores the CNAME answer an use the additional TXT answer if it is available.

I'm not an expert on DNS, but reading https://serverfault.com/questions/832816/resolving-a-cname-who-looks-up-subsequent-a-record-resolver-or-server, my guess is that you are using a non recursive DNS server that is not following the CNAME.

Could you try a different DNS server that is recursive?

A workaround could be to use the libunbound resolver.

---

If you still need it I could try to implement complete support for CNAME. But unless I'm mistaken almost all DNS severs that a user would configure should be recursive DNS servers, there the current partial support of CNAME is enough.
So fixing this would not have the highest priority for me.

**Comment by tekvsakdan** [comment]
You are right. I hadn't thought about it, but there is no record in our internal DNS server, so it doesn't work. I had completely forgotten about that and was looking for a solution to the problem at the wrong end. I tried with a different DNS and it works without a problem. I apologize and I will close this issue.
