### ISSUE TITLE
Still further Icons

### ISSUE THREAD

**Issue by Rimole** [lieser/dkim_verifier#387]
from&signed   icon
news.kleinanzeigen.de   https://www.kleinanzeigen.de/apple-touch-icon.png
ko-fi.com   https://ko-fi.com/favicon.png
bequiet.com   https://www.bequiet.com/favicon.ico
openpetition.org   https://www.openpetition.de/favicon-32x32.png
news.vgwort.de   https://www.vgwort.de/favicon/favicon-16x16.png
gd.nrw.de	https://www.gd.nrw.de/image/gd_logo2.gif
news.conrad.de   https://www.conrad.de/etc/designs/ccp-sites/favicon/favicon-16x16.png?v=2
miele.de   https://media.miele.com/ex/international/favicon/favicon-miele-16x16.png or big: https://media.miele.com/ex/international/favicon/favicon-miele-192x192.png
news.co2online.de   https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.co2online.de&size=32
stadtfruechtchen.de   https://www.stadtfruechtchen.de/wp-content/uploads/2019/02/favicon-32x32.png
info.ga.de   https://ga.de/assets/skins/general-anzeiger-bonn/apple-touch-icon-180x180.png?v=1692073624
nomail.ec.europa.eu   https://commission.europa.eu/profiles/contrib/ewcms/themes/ewcms_theme/favicon.ico
drrocke.de   https://www.drrocke.de/wp-content/uploads/2014/07/favicon.png
mail.fotoparadies.de   https://www.fotoparadies.de/asset/assets/images/favicon.ico
email.usmint.gov   https://www.usmint.gov/wordpress/wp-content/themes/us-mint/favicon.ico
pagure.io   https://pagure.io/theme/static/favicon.ico
genderleicht.de   https://www.genderleicht.de/wp-content/uploads/2019/10/cropped-GL_Logo_Final_GL_Signet_wei%C3%9F-auf-rot-1-300x300.png
mail.verivox.de https://static.verivox.de/bilder/verivox/foundation/data/favicon.ico
muenzen.eu   https://www.muenzen.eu/files/design/favicon//favicon-32x32.png

From: gamboz@medialab.sissa.it
Signed by: cbsolt.net
Icon:    https://medialab.sissa.it/sites/default/files/favicon.ico

From: craig@rarechromo.org
Signed by: auth.ccsend.com
Icon:    https://rarechromo.org/cms/wp-content/themes/unique/images/favicon/apple-touch-icon-144x144.png

From: info@queeres-netzwerk.nrw
Signed by: crsend.com
Icon:    https://queeres-netzwerk.nrw/wp-content/uploads/2021/04/cropped-QN_Favicon-32x32.png

From: web@noreply.openstreetmap.org
Signed by: openstreetmap.org
Icon: https://www.openstreetmap.org/assets/apple-touch-icon-180x180-ea6361d7ae5b3f08c6290652ad703fa239364cc09c84873044f3299845f24652.png

From: medicover.de
Signed by: fireeye.com
Icon: https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.medicover.de&size=32

stepstone.de is already included, but now uses a new icon: https://www.stepstone.de/favicon.ico

From: agu.org
Signed by: AGUORG.onmicrosoft.com
Icon: https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.agu.org&size=32

From: @glasgow.ac.uk
Signed by: gla.onmicrosoft.com
Icon: https://www.gla.ac.uk/3t4/img/university-of-glasgow-280.png

**Comment by lieser** [comment]
Thanks for the additional icons, will take a closer look at it latest before the next release.

**Comment by lieser** [comment]
I added both rules and favicons for the domains, except for the following there only a rule was added:

- `medialab.sissa.it`
- `rarechromo.org`
- `queeres-netzwerk.nrw`
- `medicover.de`

The reason for not adding the favicon is the missing connection between the domain and the From address. See also https://github.com/lieser/dkim_verifier/wiki/Contribute#additional-requirements-for-favicon.

**Comment by HyperCriSiS** [comment]
Why is this done manually?
There are plugins in Keepass for example that automatically fetch fav icons for a domain.
Would be awesome to have such a feature integrated. :)

**Comment by lieser** [comment]
> Why is this done manually?

Short answer: For security reasons, to have a trust relation between the shown icon and the signing domain.
A longer answer can be found at https://github.com/lieser/dkim_verifier/issues/118#issuecomment-409293231.
