### ISSUE TITLE
Hardcoded Thunderbird should be a useragent variable

### ISSUE THREAD

**Issue by Rimole** [lieser/dkim_verifier#388]
"DKIM Failed to make a DNS query because Thunderbird is in offline mode."

It is totally irrelevant, whether Thunderbird is in offline mode or even not installed at all. 

It is relevant, whether the used e-mail client is in offline mode. (OK, that client might by Thunderbird, but could also be e.g. Betterbird.)

I.e.: Please replace "Thunderbird" either by "e-mail client" or, better yet, by the name of the e-mail client/useragent (which it hopefully makes available to the add-ons).

**Comment by lieser** [comment]
Thunderbird's API provides [`browser.runtime.getBrowserInfo()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getBrowserInfo) which seems to provide the dynamic name we probably want to use.

Could you make sure the branding you are using (probably Betterbird?) is proving a usefull name there?

1. Open the consol for the addon
    1. Open the add-on manager
    2. Click the gear icon and select *Debug Add-ons*
    3. Click on the *Inspect* button of the add-on
    4. Select the *Console* tab
2. Execute `await browser.runtime.getBrowserInfo()`
3. Something like `Object { name: "Thunderbird", vendor: "", version: "102.15.0", buildID: "20230826133440" }` should be posted. Hopefully with proper branding in the name.

**Comment by lieser** [comment]
From reading https://github.com/Betterbird/thunderbird-patches/issues/192 it sounds like they currently also don't plan to change what `browser.runtime.getBrowserInfo()` returns. So for now I will also not implement using the information there.

Feel free to reopen this issue if Betterbird in the future will return something different from Thunderbird as the name.
