### ISSUE TITLE
DKIM Verifier may provide incorrect test result

### ISSUE THREAD

**Issue by Oktonaut** [lieser/dkim_verifier#389]
The Thunderbird add-on complains that the signature is invalid for messages sent by a PHP script via SMTP. However, the online test at https://www.appmaildev.com/en/dkim does not return any errors (DKIM result: pass)!

It would also be nice if you could display a somewhat more detailed test result, for example via a context menu.

**Comment by lieser** [comment]
You can enable more detailed error reasons in the advanced options. See https://github.com/lieser/dkim_verifier/wiki/Options#show-detailed-error-reasons.

But if it is really that the signature itself is invalid, the add-on will never be able to tell why. You would need to have the original and unmodified e-mail and compare them with the received one to see what changed.

Note that there are some e-mail providers know to have problems with this: https://github.com/lieser/dkim_verifier/wiki/FAQ#all-or-almost-all-e-mails-with-dkim-signature-are-failing-with-the-same-error

**Comment by Oktonaut** [comment]
I was able to reproduce the error. It seems to be due to non-encoded umlauts in the header for To or From. Here it returns "_Invalid (signature wrong)_".

If you check the same mail at appmaildev.com or mxtoolbox.com, however, this is not objected to and the check result is positive.

If the fields in the header are transferred in accordance with RFC, the result of the signature check is also valid.

Instead of invalid signature, it would be better to display valid with warning: "_To/From incorrectly formatted_"!
After all, the signature should be correct, since it was calculated with the incorrect header, wasn't it?

P.S. I activated "_Show detailed error reasons_" and "_lock after the SDID_", but the view remains unchanged for me!?

**Comment by lieser** [comment]
This is a problem outside the scope of the addon:

- The script sends out e-mails in a format that some receiving servers don't like.
- The server you are using to receive the e-mail is such a server, and is "correcting" the To and From headers. This however invalidates the DKIM signature.
- The appmaildev.com and mxtoolbox.com servers do not change the incoming e-mails before doing the DKIM verification. They wherefore don't have any trouble verifying the signature.

The best solution would probably to change the script to send e-mails in an encoding that servers don't want to "fix".

> Instead of invalid signature, it would be better to display valid with warning: "To/From incorrectly formatted"!

This is however not an information the add-on has or can easily get! Multiple headers are signed, and if only a single bit changes the signature is invalid. With no information provided what changed.

The only way to tell is to luckily guess what changed, revert it, and see if that fixes the signature. Doing this is however way out of scope for the add-on.

> I activated "Show detailed error reasons" and "lock after the SDID", but the view remains unchanged for me!?

The *Show detailed error reasons* option will only show more information if the add-on can provide more.
An example would be an ill-formatted signature. Normally the add-on would only say that the signature is ill-formed. With the option enabled it would go into more detail which part is ill-formed.

But like I said, verifying a signature with a changed input does not give you any more information than the signature being invalid for the given input.

**Comment by Oktonaut** [comment]
@lieser Thank you for your detailed reply.
This of course makes it clear that the signature has really been invalidated and that the receiving server is responsible for this.
Unfortunately, if the server does not transmit its own correction, the error cannot be displayed... It's a shame but it's not a mistake with this great add-on!

**Comment by lieser** [comment]
Sounds like your questions are answered now, so will close this. Feel free to reopen if there is till something unclear.

Like it already said, if you are in control of the sending the message, the best you can do is try to find a format that is accepted my all emails servers without it being changed.

For the receiving side, one can enable the reading of the Authenticated Results header. Most server that change e-mails do so at least after they themselves validated the DKIM signature.
