### ISSUE TITLE
Cannot validate DKIM if NextDNS is used

### ISSUE THREAD

**Issue by ffscz** [lieser/dkim_verifier#390]
Hello, DKIM validation does not work when using NextDNS, only the error getting: Error connecting to that DNS

Which IP range or which provider should I set in the whitelist for validation to take place? I can't at all identify where the extension is asking or which IP.

When using WARP+ from Cloudflare, everything works normally, but this is not a solution. I need NextDNS

Thank you

**Comment by lieser** [comment]
The add-on has options to configure which DNS server should be used. See also https://github.com/lieser/dkim_verifier/wiki/DNS.

A few things could potentially go wrong:

- The add-on fails to detect the DNS servers configured in the OS, and the default fallback of `8.8.8.8` is not reachable. Manually setting the correct one would be the easiest if that is a solution for you.
- The NextDNS is only reachable by UDP. The default resolver used however only supports TCP. You would need to switch to libunbound.

**Comment by ffscz** [comment]
@lieser  did it according to the instructions and used libunbound now I get an Internal Error in DKIM Validator. But I have not solved the problem. 

Is there any other instruction how to make this work when using NextDNS?

Screen internal Error: [https://i.ibb.co/w4n5ryY/dkim-err.jpg](url)
DKIM Validator DNS settings: [https://i.ibb.co/R7n99TY/dkim-sett.jpg](url)

**Comment by lieser** [comment]
For trying to fix it with libunbound:

Do you use Thunderbird 115?
It seems like there is an issue there with the *Path relative to profile directory* option, if the path contains a folder. Please try with moving the dll directly under the profile folder or deselect the option and specify an absolute path.

For trying to fix it with the normal resolver:

Have you looked into what is going wrong here? E.g. does it not try the correct DNS server, or does connecting to it failed?
See also https://github.com/lieser/dkim_verifier/wiki/Debug#view-error-and-debug-messages, best with enabling debug logging in the advanced options.

**Comment by ffscz** [comment]
@lieser I don't know, I just can't get it to work and I don't have time to solve it.

For one thing it doesn't work when using NextDNS, but with Cloudflare WARP+ it works normally, but that's not a solution for me. 

Try to use NextDNS yourself as a developer (it's free) and debug it.

I have TB version 102.15.0 (64bit)

Error console: https://i.ibb.co/FWxZSvB/dfvdfvvfvdfvdfv.jpg

I had the dll moved directly to the profile directory, but it didn't help.

**Comment by lieser** [comment]
I did go to https://my.nextdns.io/start. There under *Linked IP* it gave me the following two DNS servers:
`45.90.28.155` and `45.90.30.155`.
Both worked without a problem for me.

If you still have the problems please:
- Enable debugging in the advanced options of the add-on.
- Post the output of the *Error Console* here.
- If the output still contains errors that have the `<unavailable>` at the end (like in your screenshot), also go to the debugging view of the add-on and the console there. Post the output from there too.

**Comment by ffscz** [comment]
@lieser I used the NextDNS desktop application. Now I have set up DNS directly in the router and it works fine.

So, if anyone has the same problem, use DNS for NextDNS other than using the NextDNS for Windows app.

You can mark the case as closed.
