### ISSUE TITLE
Sometimes no DKIM result is shown (despite DKIM signature being ok)

### ISSUE THREAD

**Issue by MaximeMaW** [lieser/dkim_verifier#391]
Sometimes (it seems to happen randomly on some messages), no DKIM-test result is displayed on the window (example):

![Capture d’écran du 2023-08-30 12-02-58](https://github.com/lieser/dkim_verifier/assets/26774320/97a8a2b7-41a5-4fc4-a02b-6c47842fb81d)

If I open the same email in full screen, the DKIM-test runs properly:

![Capture d’écran du 2023-08-30 12-03-54](https://github.com/lieser/dkim_verifier/assets/26774320/bd294e5c-992a-4bbc-9c9c-0e9998784c0c)

For other emails (same sender & receiver), the display is always correct (in both windows).

Is there a place where I could see a debug log?

**Comment by lieser** [comment]
See https://github.com/lieser/dkim_verifier/wiki/Debug#view-error-and-debug-messages on how to view the log.

You should probably also enable debugging in the advanced options.

---

The behavior you describe is definitely strange. Normally all exceptions should be catched and at least `Internal error` be shown. Hopefully the logs for then this occurs will show a reason why.

**Comment by aiboost** [comment]
I see this issue too. No "temporary error" flag, neither any other badge (I've enabled highlighting for all the statuses).

My guess: DKIM highlighting does not work for text-only (without HTML body) messages. 

But I have only one highlighted e-mail message (really from a spammer, text-only, DKIM verification must fail). Another messages with this e-mail (from real website) are highlighted fine (they also have HTML body).

If I "Open this message in a new tab", I see the DKIM verification problem under e-mail (no error here).

**Comment by MaximeMaW** [comment]
On my sides, this happens with HTML emails too. I will post the error/debug log this week.

**Comment by MaximeMaW** [comment]
Here are the logs. I think I managed to set `logging.console` to `All` and `debug` to true (but I might be wrong, please correct me). I don't see any reason why a specific email will not display. Let me know if I can provide extra information to reproduce the issue. Thanks a lot!

## Email displaying DKIM/DMARC check properly:
```
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. 3 blank
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. INBOX>9261
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. contentAreaClick.js:97:6
DKIM_Verifier.AuthVerifier	DEBUG	 ARH result: 
Object { version: "3.0", dkim: (1) […], spf: (1) […], dmarc: (1) […] }
authVerifier.mjs.js:320:6
DKIM_Verifier.AuthVerifier	DEBUG	 authResult:  
Object { version: "2.1", dkim: (1) […], spf: (1) […], dmarc: (1) […] }
authVerifier.mjs.js:198:7
```

And the content of the objects:
```
[
  {
    "method": "spf",
    "method_version": 1,
    "result": "pass",
    "propertys": {
      "smtp": {
        "mailfrom": "SRS0=/TjM=EV=blabla.girofle.cloud=noreply@chif.fr"
      },
      "header": {},
      "body": {},
      "policy": {}
    }
  }
]

{
  "version": "2.1",
  "dkim": [
    {
      "version": "2.0",
      "result": "SUCCESS",
      "warnings": [],
      "sdid": "blabla.girofle.cloud",
      "auid": "@blabla.girofle.cloud",
      "res_num": 10,
      "result_str": "Valid (Signed by blabla.girofle.cloud)",
      "warnings_str": []
    }
  ],
  "spf": [
    {
      "method": "spf",
      "method_version": 1,
      "result": "pass",
      "propertys": {
        "smtp": {
          "mailfrom": "SRS0=/TjM=EV=blabla.girofle.cloud=noreply@chif.fr"
        },
        "header": {},
        "body": {},
        "policy": {}
      }
    }
  ],
  "dmarc": [
    {
      "method": "dmarc",
      "method_version": 1,
      "result": "pass",
      "propertys": {
        "smtp": {},
        "header": {
          "from": "blabla.girofle.cloud"
        },
        "body": {},
        "policy": {}
      }
    }
  ]
}
```

## Email NOT displaying DKIM/DMARC properly
```
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. INBOX>9262
DKIM_Verifier.AuthVerifier	DEBUG	 ARH result: 
Object { version: "3.0", dkim: (1) […], spf: (1) […], dmarc: (1) […] }
authVerifier.mjs.js:320:6
DKIM_Verifier.AuthVerifier	DEBUG	 authResult:  
Object { version: "2.1", dkim: (1) […], spf: (1) […], dmarc: (1) […] }
authVerifier.mjs.js:198:7
```
Content of the objects:
```
[
  {
    "method": "spf",
    "method_version": 1,
    "result": "pass",
    "propertys": {
      "smtp": {
        "mailfrom": "SRS0=/TjM=EV=blabla.girofle.cloud=noreply@chif.fr"
      },
      "header": {},
      "body": {},
      "policy": {}
    }
  }
]

{
  "version": "2.1",
  "dkim": [
    {
      "version": "2.0",
      "result": "SUCCESS",
      "warnings": [],
      "sdid": "blabla.girofle.cloud",
      "auid": "@blabla.girofle.cloud",
      "res_num": 10,
      "result_str": "Valid (Signed by blabla.girofle.cloud)",
      "warnings_str": []
    }
  ],
  "spf": [
    {
      "method": "spf",
      "method_version": 1,
      "result": "pass",
      "propertys": {
        "smtp": {
          "mailfrom": "SRS0=/TjM=EV=blabla.girofle.cloud=noreply@chif.fr"
        },
        "header": {},
        "body": {},
        "policy": {}
      }
    }
  ],
  "dmarc": [
    {
      "method": "dmarc",
      "method_version": 1,
      "result": "pass",
      "propertys": {
        "smtp": {},
        "header": {
          "from": "blabla.girofle.cloud"
        },
        "body": {},
        "policy": {}
      }
    }
  ]
}
```

**Comment by lieser** [comment]
Thanks for the log, don't see anything wrong there.
But please make sure that:
- You got the log from the Error Console of Thunderbird an not the debug view of the add-on.
- There is no error reported further up in the log.

If the messages you have problems with are always the same could you possibly send me an affected one to lieser+dkim@posteo.net? If I could reproduce it myself it would help a lot in finding the issue.

Btw what Thunderbird version are you both using?

**Comment by lieser** [comment]
Can one of you provide the additional information I asked for? Without being able to reproduce it or at least get some concrete error message it is unlikely I will be able to fix this.

**Comment by MaximeMaW** [comment]
Hello @lieser.  Thank you for the reminder. I am no longer receiving emails with inconsistent DKIM signatures, and the problematic emails were on a mailbox I no longer have access to. I am closing this ticket and will reopen it if I encounter the issue again. I will double check/answer the questions you asked. I apologize about this.
