### ISSUE TITLE
Two similar email, one shows RED the other GREEN

### ISSUE THREAD

**Issue by graemev** [lieser/dkim_verifier#425]
Now, I'd not go so far as to say this is a bug but there seems to be a disagreement between two locations or a misunderstanding on my part.

I received two BUMF email (advertising) from  the same company on two consecutive days. One was marked GEEEN (DKIM)   , the other RED (the email was modified). Taking the headers and pasting into https://mxtoolbox.com/Public/Tools/EmailHeaders.aspx, the two appear very similar.
(they see SPF issues  but no DKIM problem ...if I'm understanding their site)

I have no reason to suppose there has been any MITM attack .

This is just BUMF mail, do there is no confidential information . The only bit I care are about is my email address (don't want even more junk)

**Comment by lieser** [comment]
Thanks for attaching the e-mails, you can delete them now if you want. Note that the next time you can also separately mail them to me.

Unfortunately without seeing the original send one it is nearly impossible to find out what was modified, even when having a very similar one. One must basically guess it and test if the guess was right.

I tested both e-mails with the [dkimpy](https://pypi.org/project/dkimpy/) library and got the same result, that the one from the 28. is valid and the one from the 27. was modified.
So I currently find it unlikely to be a bug in the add-on.

It is probably also unlikely that this is a real attack, and more likely that one of the servers just modified the e-mail in a non malicious way.

On interesting note is the `DKIM_VALID` in the `X-Spam-Status` header. I'm not that familiar with SpamAssassin but I would expect that the `DKIM_VALID` only appears there if DKIM was successfully validated by SpamAssassin, indicating that it was only changed afterwards.

**Comment by graemev** [comment]
OK, thanks, I edited comment to remove reference to the files , can't see a way to actually delete the upload. Did you try cut & paste the headers into https://mxtoolbox.com/Public/Tools/EmailHeaders.aspx ?

It could be I'm misreading it, but it looks to me as if it's saying:
