### ISSUE TITLE
Error Reverifying DKIM Signature

### ISSUE THREAD

**Issue by moggoly** [lieser/dkim_verifier#426]
I've not noticed it until recently when I wanted to check the DKIM status of a few emails, but I'm seeing the following error since the last update everytime I click on Reverify DKIM Signature:

```
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
displayAction.mjs.js:47
    triggerDisplayAction moz-extension://cb2a8480-36a6-4c5b-9173-d6ddff65f986/content/displayAction.mjs.js:47
```

![image](https://github.com/lieser/dkim_verifier/assets/895494/dfef82b5-34d1-48e3-885d-b6b2333b3761)

Running Thunderbird Beta 122.0b4.

Apart from this error in the Error Console, there's no feedback from the plugin to show anything has gone wrong.

**Comment by lieser** [comment]
Thanks for reporting, but this error is expected to come when clicking any of the buttons, and can be safely ignored.
It should have also appeared in earlier Thunderbird versions.

As you closed the issue yourself already, I assume the reverification itself is working for you, and you were just unsure why you did see the error.
