### ISSUE TITLE
Mark as spam / Assign specific tag for mail that failed to validate DKIM

### ISSUE THREAD

**Issue by windymelt** [lieser/dkim_verifier#431]
Hello, I'm using DKIM Verifier 5.4.0 on Linux.

Would you add feature that mark as spam / assign tag to wipe spam out from my mail box?

Of course this add-on shows DKIM validity status in green / yellow indicator, but I'd like to filter spam more smarter.

If we have the feature to mark spam / assign tag to "failed" mail, we can define filter rule to deal with it.

Though there seems to be filter rule "DKIM", but I don't know how to use it.

**Comment by lieser** [comment]
I'm not against adding filters in principle but it currently has a low priority for me.
What you are suggesting should already be tracked in https://github.com/lieser/dkim_verifier/issues/215 and https://github.com/lieser/dkim_verifier/issues/158, so I will close this as a duplicate.

Note that the addon so far does not add any filters. I'm not sure about what DKIM filter rule you are taking about but it must come from somewhere else.
