### ISSUE TITLE
Seems not to work at all in thunderbird 38.1.0

### ISSUE THREAD

**Issue by stamfest** [lieser/dkim_verifier#45]
No matter of how I configure the add on, the verification indicator never changes from "verifying"... There are also NO DNS queries whatsoever related to DKIM DNS entries (using tcpdump and wireshark). The error console also does not show any useful log entries (besides "initialized" and "DB initialized").

Are there any know incompatibilities with other addons?

**Comment by lieser** [comment]
Currently I don't know of any incompatibilities with other add-ons. But it would still be nice if you could test it with all other add-ons disabled, and if this doesn't help with a clean profile.

It sound like for some reason the Start of the verification is not triggered at all, or is stuck at the very beginning like the reading of the message.
If the disabling of the other add-ons does not help, I could pack a new version for you with additional tracing debug info. Maybe this way we could find out were exactly the verification is stuck.

**Comment by lieser** [comment]
Could you please give me a link to the add-on? Maybe I am able to fix this.

**Comment by stamfest** [comment]
Am 2015-07-21 um 15:27 schrieb Philippe Lieser:
>
> Could you please give me a link to the add-on? Maybe I am able to fix
> this.
>
http://blog.kamens.us/send-later

**Comment by lieser** [comment]
I just did a quick test with both add-ons installed (DKIM verifier 1.3.5, Sent later 4.4.1), but was unfortunately unable to reproduce it.
Are the versions you have installed the same?

**Comment by stamfest** [comment]
Am 2015-07-21 um 17:21 schrieb Philippe Lieser:
>
> I just did a quick test with both add-ons installed (DKIM verifier
> 1.3.5, Sent later 4.4.1), but was unfortunately unable to reproduce it.
> Are the versions you have installed the same?
>
Yes, they are. I have a gut feeling that it might be related to the fact
that "Send later" is the LAST in the list of add-ons (but I have no
experience regarding TB addons whatsoever, so this is likely complete
nonsense). Because of that, it was also among the last three add-ons I
re-enabled in my tests. Then DKIM verify did no longer work, I disabled
"Send later" and DKIM verify worked again...

This installation also is ancient: The profile likely was set up using
Thunderbird 3.x and went through many TB upgrades. The same is true for
most add-ons: Installed a long time ago and upgraded whenever I upgraded TB.

I did not yet mention that I am using Linux, BTW. Sorry for that.

Regarding the bug: I consider it fixed, with the problem being with
send-later (which would be nice to have, but it has its own set of
problems anyway, so I can live without it).

**Comment by lieser** [comment]
The add-on list is alphabetical, and I don't think the installation order causes this. I now also tested it with Linux.
The problem is probably causes by a non default preference or a change of the UI (for example removed/added button in the header).

Even if a fix is not important to you, I would appreciate it if you could do a little more testing, so that I can maybe find the problem.

To do so, please install version 1.3.6pre1 from https://github.com/lieser/dkim_verifier/releases. If still no Error is shown, change the preference `extensions.dkim_verifier.logging.console` to `All` and `javascript.options.showInConsole` to true.
