### ISSUE TITLE
Thunderbird 128 support

### ISSUE THREAD

**Issue by sha-265** [lieser/dkim_verifier#451]
Please add support for Thunderbird 128.

Thanks.

**Comment by bernieEV** [comment]
YES, please add support for Thunderbird 128
my platform is GNU/Linux Ubuntu 22.04LTS desktop distribution.
Thanks

**Comment by lieser** [comment]
I definitely plan to also support Thunderbird 128. Unfortunately I am currently away an will earliest be able to work on this end of next week.

**Comment by lieser** [comment]
Just tested the last released version 5.4.0 and did not see any compatibility issues. So I marked 5.4.0 now as compatible until Thunderbird 130 on ATN.

But thank you all for reporting this. Don't always follow the latest beta/daily Thunderbird releases that closely, so sometimes helpful to get a reminder that where is a new version out I need to test with.
