### ISSUE TITLE
Support ARC-Authentication-Results header

### ISSUE THREAD

**Issue by KlaasBonnema** [lieser/dkim_verifier#468]
An increasing number of e-mail providers is including an ARC-Seal protected ARH header inside the processed mails. The benefit of this is that an ARH evaluated by a previous mail server in the chain can be trusted based on a valid ARC-Seal.
DKIM verifier validates DKIM signatures and can display the result of an ARH. The ARH typically gives more information, including iprev, spf and dmarc results. 
The request is to use the most recent ARC-Authentication-Results header with a matching valid ARC-Seal to display the ARH results.
As a bonus, display a warning message when the ARC chain appears to be broken.

**Comment by lieser** [comment]
Thanks for the suggestion, adding support for it is already tracked in #87. Will close this as duplicate.
