### ISSUE TITLE
Automatically switch to verifying if no ARH is found

### ISSUE THREAD

**Issue by alevesely** [lieser/dkim_verifier#57]
If there is no ARH, but an (unverified) DKIM-Signature exists, no verification is carried out.  The following error sometimes is displayed, presumably due to an empty ARH.

2016-01-17 19:50:03	DKIM_Verifier.AuthVerifier	ERROR	Error: Parsing error (resource://dkim_verifier/ARHParser.jsm:249) JS Stack trace: match@ARHParser.jsm:249:1 < parseResinfo@ARHParser.jsm:186:14 < _ARHParser_parse@ARHParser.jsm:161:21 < getARHResult@AuthVerifier.jsm:161:10 < _authVerifier_verify/promise<@AuthVerifier.jsm:103:17

**Comment by lieser** [comment]
I can not confirm that with a non existing ARH no verification is carried out. Are you perhaps instead meaning an ARH header without a DKIM result in it? For this the verification is indeed not carried out. This behavior will be corrected.

About the parsing error:
Are you meaning with an empty ARH header something like `Authentication-Results: ` or `Authentication-Results: authserv-id;`? This are not correct ARH headers. The correct way to indicate that no message authentication was done is `Authentication-Results: authserv-id; none`. Although this currently also produces an error (which will be corrected), it is not a paring error.
If you still think the ARH header which produces the parsing error is correct, please post it (or send it to dkim.verifier.addon@gmail.com) so I can look into it in detail.

**Comment by alevesely** [comment]
There is a silly:
Authentication-Results: tana.it; auth=pass (details omitted)
and there is a DKIM-Signature.  It looks as if parsing throws an exception, so nothing else is going to be done.   The status bar says "DKIM: No Signature", although there is one.

**Comment by lieser** [comment]
Could you please send me the complete header that is giving the parsing error to dkim.verifier.addon@gmail.com?

**Comment by lieser** [comment]
The verification should now continue if the ARH header does not include a DKIM result. You can download a pre-release form https://github.com/lieser/dkim_verifier/releases.
