### ISSUE TITLE
Links in amo.properties clickable?

### ISSUE THREAD

**Issue by mlocati** [lieser/dkim_verifier#61]
What about enclosing the links in the `amo.properties` files with `<a href="...">...</a>`?

**Comment by lieser** [comment]
That happens automatically. It is only needed if the shown test should be different from the link.

**Comment by mlocati** [comment]
In my Thunderbird (38.5.1), I go to `Menu` > `Add-ons`, then I click the `More...` link under the `DKIM Verifier 1.3.6" extension, and I see that the links may not be clicked...

![image](https://cloud.githubusercontent.com/assets/928116/12614819/7bfc9912-c502-11e5-9938-4d3e41291eec.png)

**Comment by lieser** [comment]
Yes, you are right, at that place the links are not clickable. But the "firme DKIM", which has the `<a href="...">...</a>`, is also not clickable. I suspect it is not possible to make links clickable in this place.

On the AMO site itself (https://addons.mozilla.org/it/thunderbird/addon/dkim-verifier/) the links are clickable.

**Comment by mlocati** [comment]
:+1:
