### ISSUE TITLE
Problem with version 1.4.0+

### ISSUE THREAD

**Issue by beerisgood** [lieser/dkim_verifier#65]
Currently i use version 1.3.6 in Fossamail (Thunderbird fork from the Pale Moon browser dev) and if i try to update my addons in Fossamail i get for your addon
"There was an error downloading null"

So i download the addon from AMO manual but the install fails with the message
"addon is corrupted".

Then i download the version from github and the install fails too. I compare the checksum with this version and the ones from AMO - same.
If i try to install 1.4.0 from github i get the same install error.

**Comment by lieser** [comment]
I installed the newest version of Fossamail (25.2.0), and installing both version 1.4.0 (from a file) and 1.4.1 (through the add-on managers "Get Add-ons") of the add-on worked without problems.

That version of Fossamail are you using?
Have you tried to remove the add-on, restart Fossamail, and the re-install the new version?
Have you already tried installing the add-on in a clean Profile?

**Comment by beerisgood** [comment]
I test a clean profile and all works, so it must be something wrong with my profile.
Sorry for the false alarm.

**Comment by lieser** [comment]
Have you been able to fix the problem? If not, you could give version 1.5.0pre2 a try. In there, I fixed an installation problem for another user. Although your problem sounds like a different one, it may still help.

If the version 1.5.0pre2 is also not working, could you please give me the exact error message as logged to the error console (Ctrl + Shift + J)? Maybe I can find a workaround for it by searching for the error message.

**Comment by beerisgood** [comment]
Thank you!
That version works great.
