### ISSUE TITLE
Shortcut to open rules list?

### ISSUE THREAD

**Issue by mjdl** [lieser/dkim_verifier#78]
New user of your excellent DKIM verifier here.

Is there no way to open the rules editor other than going through the Thunderbird add-ons list and opening the options panel for the extension? Have I missed something?

Two things would improve usability: 1) a custom button `DKIM rules` the user can put anywhere the Thunderbird UI user customization allows, and 2) match the `domain` and `From` in the currently open email to any corresponding DKIM rule (wildcard `From` included), or, if none is found, pre-populate the `domain`, `From`, and `SDID` fields of a new rule.

UPDATE: Actually, maybe adding `Create DKIM rule from Address...` to the context menu pop-up for `From` addresses in the Thunderbird email header pane is a better alternative to access the DKIM rules list.

**Comment by lieser** [comment]
Yes, at the moment this is the only way to open the rules list.

I like you idea about adding `Create DKIM rule from Address...`. Will try to include this in the next version.

I will also think about adding a custom button for the DKIM rules.

Note that it is already possible to [automatically addthe rules based on the vied e-mails](https://github.com/lieser/dkim_verifier/wiki/Options#automatically-add-rules-based-on-viewed-dkim-signed-e-mails). In case the add-on gives an error saying an e-mail should be signed, on can also add an exception for the From address by clicking "Add must be signed exception" in the "Other Actions" drop-down menu in the e-mail header.

**Comment by mjdl** [comment]
Thanks for considering this as a possible enhancement, and also for pointing me to the option to have rules automatically added (and exceptions).

**Comment by lieser** [comment]
Although it took a while, there is now a toolbar button and a menu entry under More in the message heder, that shows the rules list. Would be nice if you could try out v2.0.0pre4 to see if it works for you.

Note that the `Create DKIM rule from Address...` suggestion is still not implemented. If you are still interested in this, please create a separate issue for this.
