### ISSUE TITLE
dkim key not signed by dnssec

### ISSUE THREAD

**Issue by thwaller** [lieser/dkim_verifier#80]
Emails sent from my domain are being warned as (because I have set to warn if it applies) "dkim key not signed by dnssec". My question is that I have verified and confirmed that my domain is protected by DNSSEC and all is enabled on DNS side and Registrar side. How might I find out why I am getting this warning while DNSSEC is enabled for my domain? Maybe I am misunderstanding the warning too.

**Comment by lieser** [comment]
Are you using the libunbound DNS resolver? The default one does not support DNSSEC (see https://github.com/lieser/dkim_verifier/wiki/FAQ#dnssec-does-not-work).

If you are using libunbound, please enable logging and post the output.

**Comment by thwaller** [comment]
I see. That was the problem. Now, however, I get "Internal Error" when selecting an email in which DKIM is signed by DNSSEC. If I simply select "Reverify DKIM Signature", then it will show as DNSSEC validation with the lock and all pass. If I click off the email, then back on it again, the same process repeats... shows as error then reverify and then good.

Any ideas on why this might be happening? It might help, so using Ubuntu 16.10 64 bit with Thunderbird 51.0b2. DKIM Verifier is at latest, 1.6.3 version.

**Comment by lieser** [comment]
Could you please provide a log? If you do not want it to be public, you can also sent it to lieser+dkim@posteo.net.

**Comment by thwaller** [comment]
sent per request.

**Comment by lieser** [comment]
Thanks for the log. It is a problem with saving the result and the lock as DNSSEC indicator. Disable one of them until this is fixed.

**Comment by lieser** [comment]
Could you please try out the new version 1.6.4pre1?
You can download it from https://github.com/lieser/dkim_verifier/releases or https://addons.mozilla.org/en-US/thunderbird/addon/dkim-verifier/#beta-channel.

**Comment by thwaller** [comment]
I have installed the new pre version as requested. Install went fine. Only issue I am having is that by using libunbound DNS resolver, it gets stuck on DKIM verification and does not ever verify. It will if I switch it to default though. This problem started a few days back, a bit before updating to the new version though. So I will need to figure out that issue before I can test the new version as the fix will depend on DNSSEC working.

FYI- Using libunbound did work just fine after you pointed out the issue with my configuration. Unfortunately I am not sure what caused it to stop functioning.

**Comment by lieser** [comment]
Here are a few thinks you could try:
- disable the option for getting the DNS server from the OS, and try out a different DNS servers (for example googles `8.8.8.8`)
- enable debug mode, and look in the log for some obvious problem. Otherwise send the log to me

The last option would be to use the [`extensions.dkim_verifier.dns.libunbound.conf`](https://github.com/lieser/dkim_verifier/wiki/DNS#extensionsdkim_verifierdnslibunboundconf-string) option to specify a [unbound.conf](http://unbound.net/documentation/unbound.conf.html) file there you enable logging to a file for libunbound.

**Comment by lieser** [comment]
Thanks for the error log. There was still an incompatibility with Thunderbird and libundbound, which I missed.
I just released the 1.6.4pre2 version, which will hopefully work for you.

**Comment by thwaller** [comment]
This does appear to be working now. Glad all is sorted out. Should I have any further issues, I will let you know. Thanks for the assistance and glad the logs I provided could help.
