### ISSUE TITLE
Some emails do not validate

### ISSUE THREAD

**Issue by exussum12** [lieser/dkim_verifier#81]
Not sure if this is helpful but the email passes here 
https://9vx.org/~dho/dkim_validate.php

But not on this extention, below is a trace of exceptions generated from Tiny Javascript Debugger

Anything else you need let me know!

** Exception in file resource://gre/modules/XPCOMUtils.jsm, line 399:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/XPCOMUtils.jsm, line 399:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://dkim_verifier/dkimPolicy.jsm, line 278:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://dkim_verifier/dkimVerifier.jsm, line 1398:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://dkim_verifier/dkimKey.jsm, line 322:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://dkim_verifier/dkimKey.jsm, line 205:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://dkim_verifier/dkimVerifier.jsm, line 1049:
Exception text: Error name: DKIM Signature Error
Error message: The signing domain is only testing DKIM

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: DKIM Signature Error
Error message: The signing domain is only testing DKIM

** Exception in file resource://dkim_verifier/dkimVerifier.jsm, line 1160:
Exception text: Error name: DKIM Signature Error
Error message: The signing domain is only testing DKIM

** Exception in file resource://dkim_verifier/dkimVerifier.jsm, line 1172:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 332:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://dkim_verifier/dkimVerifier.jsm, line 1350:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://dkim_verifier/dkimPolicy.jsm, line 432:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://dkim_verifier/AuthVerifier.jsm, line 650:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://dkim_verifier/AuthVerifier.jsm, line 616:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://dkim_verifier/AuthVerifier.jsm, line 176:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: undefined
Error message: undefined

** Exception in file resource://gre/modules/Task.jsm, line 331:
Exception text: Error name: undefined
Error message: undefined

**Comment by lieser** [comment]
Do you mean it's not getting validated at all, or showing an invalid signature?

If it is the first one, it's probably because the domain is only testing DKIM. By default, this signatures are not validated, but you can enable it in the advanced options (https://github.com/lieser/dkim_verifier/wiki/Options#still-verify-the-signature-if-a-domain-is-only-testing-dkim).

A note for the next time:
Error messages of the add-on are written to the Thunderbird Error Console (Ctr-Shift-J or Thunderbird menu -> Tools -> Error Console). Extended logging can be enabled in the add-ons advanced options.

**Comment by exussum12** [comment]
Wow thanks for the quick reply

Its githubs emails 

![image](https://cloud.githubusercontent.com/assets/1102850/23038467/08829ef4-f482-11e6-8fbb-fcdc79c0233e.png)

Some of the emails from github do verify. So not sure it is the domain ?

![image](https://cloud.githubusercontent.com/assets/1102850/23038579/6afee9de-f482-11e6-9f65-0c06a6a97725.png)

but another email of a similar type is fine from github. Seems intermittant ?

Thanks again for the quick reply!

**Comment by exussum12** [comment]
it is that, they are differnt keys

$ dig +short -t txt pf2014._domainkey.github.com
"v=DKIM1; k=rsa; t=y; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDaCCQ+CiOqRkMAM/Oi04Xjhnxv3bXkTtA8KXt49RKQExLCmBxRpMp0PMMI73noKL/bZwEXljPO8HIfzG43ntPp1QRBUpn1UEvbp1/rlWPUop3i1j6aUpjxYGHEEzgmT+ncLUBDEPO4n4Zzt36DG3ZcJaLhvKtRkk2off5XD+BMvQIDAQAB"
$ dig +short -t txt s20150108._domainkey.github.com
"k=rsa; t=s; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDF3DepunKacQZV1E0etEESNkTOG1GlIDm03+1gscZ7Tf/Vsyy9OMsTkOHFPNcbe7iBpJUfo3eC0jJGeHw+EKtvT5Ed2yDpGBxpWX8/TSW7lBrIOul2/QXoyWYXv7/EqWld/NZ+tyndBRPW+q6M2gILPrjdl9A/0TBCRZdGiAJDkwIDAQAB"


Thanks!

**Comment by lieser** [comment]
This test mode is not a property of a domain, but of a DKIM key. A single domain can have multiple of such DKIM keys. In the DKIM signature, the selector (s-tag, e.g `s=pf2014` or `s=s20150108`) specify which DKIM key to use.

GitHub currently uses multiple such selector (and wherefore DKIM keys) at the same time. At least one DKIM key (`pf2014`), but not all are in testing mode.

**Comment by exussum12** [comment]
Thanks for the speedy reply!

**Comment by lieser** [comment]
No problem, glad I could help (at least with the first reply. for the second you yourself there even faster^^).

**Comment by Darlelet** [comment]
Hi folks, quick question here, what do you mean by

> a domain which is only testing DKIM

I mean, what are the other requirements to get rid of the warning?

Thanks

**Comment by lieser** [comment]
The testing mode is a property of the DKIM key used to sign the e-mail.

### Getting rid of testing warning in the add-on:
A warning will only be shown if you have enabled the verification of such e-mails it in the advanced option. By default an e-mail singed with a DKIM key which has the testing flag enabled is treated like it is not signed.

It is not possible to configure the add-on to completely ignore this flag (e.g. verify the signature without adding the warning).

See also https://github.com/lieser/dkim_verifier/wiki/Options#still-verify-the-signature-if-a-domain-is-only-testing-dkim.

#### Workaround:
If you have enabled the saving of the DKIM keys, you can manually remove the testing flag from the saved DKIM key. View the DKIM keys from the add-ons options, and remove the ` t=y;` part of the DKIM key.

### Getting rid of testing warning as the domain owner:
You need to change the DKIM key to disable the testing mode. See https://tools.ietf.org/html/rfc6376#page-28 for details.

**Comment by Darlelet** [comment]
Thank you very much, I didn't notice the **t** flag in the DNS record and didn't know its purpose, you nailed it! 😄
