### ISSUE TITLE
Error in ebay.de default signer rule? (eply.ebay.de)

### ISSUE THREAD

**Issue by Stebs** [lieser/dkim_verifier#82]
Mails from ebay@reply.ebay.de now show a warning: Wrong signer (should be ebay.de, eply.ebay.de)
In the default signer rule for ebay.de from *@reply.ebay.de it really reads for the SDID:  ebay.de eply.ebay.de

I guess this is a typo, eply.ebay.de should be reply.ebay.de

**Comment by lieser** [comment]
Yes, this is a typo. Thanks for Reporting it.

Note that I will probably not create a new release just for this. But if you haven't already done it, you can solve this for yourself locally, by adding a correct sign rule for ebay.de, with a higher priority. Let me know if you need help with it.
