### ISSUE TITLE
Error connecting to the DNS server.

### ISSUE THREAD

**Issue by gkoulomz** [lieser/dkim_verifier#91]
Running DKIM Verifier 1.6.5  with TB 52.21.1 (32 bit) under Win7 (latest/greatest).
Get "Error  connecting to the DNS server" whenever incoming mail has a DKIM-Signature header.
Sample TB error console output:
2017-07-15 20:57:17	DKIM_Verifier.Verifier	ERROR	DKIM_DNSERROR_SERVER_ERROR: DKIM verifier internal error: Error connecting to the DNS server (resource://dkim_verifier/helper.jsm:10:32) JS Stack trace: getKeyFromDNS/promise<@dkimKey.jsm:315:10
  Log.jsm:753
	App_append resource://gre/modules/Log.jsm:753:9
	Logger.prototype.log resource://gre/modules/Log.jsm:389:7
	Logger.prototype.error resource://gre/modules/Log.jsm:397:5
	handleExeption resource://dkim_verifier/dkimVerifier.jsm:975:5
	processSignatures resource://dkim_verifier/dkimVerifier.jsm:1163:14
	throw self-hosted:1186:9
	TaskImpl_run resource://gre/modules/Task.jsm:337:41
	bound TaskImpl_run self-hosted:957:17
	Handler.prototype.process resource://gre/modules/Promise-backend.js:935:21
	this.PromiseWalker.walkerLoop resource://gre/modules/Promise-backend.js:813:7
	bound  self-hosted:913:17
	bound bound  self-hosted:913:17
	this.PromiseWalker.scheduleWalkerLoop/< resource://gre/modules/Promise-backend.js:747:11

**Comment by lieser** [comment]
Thanks for reporting the issue. Can you please enabled debugging in the advance options of the add-on, and post the output here or send it to lieser+dkim@posteo.net?

Please also try it with googles `8.8.8.8` DNS server. Do do this, in the add-ons DNS options, disable `Get DNS servers from OS configuration` and put in the `DNS name servers` filed `8.8.8.8`.
