### ISSUE TITLE
Include SeaMonkey support

### ISSUE THREAD

**Issue by Dash** [lieser/dkim_verifier#92]
I find this addon excellent for Thunderbird and would love to see it available for SeaMonkey too.  I don't know how much work is involved in making addons compatible, but there seem to be plenty that work in both Thunderbird and SeaMonkey.

https://addons.mozilla.org/en-GB/seamonkey/

**Comment by lieser** [comment]
The add-on is currently being migrated to be a WebExtension/MailExtension. From my understanding this is not yet supported my SeaMonkey.

Will close this issue for now, as I do not see myself on porting older version of the add-on, as I do not want to support multiple version of the add-on.

If SeaMonkey will ever support WebExtensions, please reopen this issue.
