### ISSUE TITLE
Does not function on TB v57.0b1

### ISSUE THREAD

**Issue by thwaller** [lieser/dkim_verifier#93]
Don't have much more detail here. It just does nothing. There is no data in the display fields while viewing emails. The preferences for the addon load just fine and everything appears to be just right, there is just no data appearing after the labels, such as after the "DKIM" label where the pass/fail data would normally appear.

**Comment by lieser** [comment]
Thanks a lot for reporting. I had quick lock, and it seems like the old syntax for generators was deprecated.

I will try to fix it this weekend, but can't promise anything.

**Comment by lieser** [comment]
Could you please test the new pre release version v2.0.0pre1?

**Comment by thwaller** [comment]
All appears to be working back to how it was, as it relates to this extension. Leaving open only in case there is more testing you may ask for, otherwise, I consider the issue as reported closed.
