### ISSUE TITLE
date.toLocaleFormat is gone in current Thunderbird builds

### ISSUE THREAD

**Issue by jikamens** [lieser/dkim_verifier#94]
They've removed date.toLocaleFormat because it's non-standard. You're going to need to update DKIM Verifier not to use it. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleFormat for alternatives.

**Comment by lieser** [comment]
Thanks a lot for letting me know.

**Comment by lieser** [comment]
The new pre-release v2.0.0pre2 works now for me in 58.0b2.
