### ISSUE TITLE
conditional catch statements no longer supported?

### ISSUE THREAD

**Issue by jikamens** [lieser/dkim_verifier#99]
Thunderbird daily is complaining:

```
JavaScript error: resource://dkim_verifier/dkimVerifier.jsm, line 608: SyntaxError: missing ) after catch
```

The issue appears to be a conditional catch statement at https://github.com/lieser/dkim_verifier/blob/master/modules/dkimVerifier.jsm#L608. Given that this is non-standard syntax and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch seems to discourage its use, perhaps, support for it has been removed?

**Comment by jikamens** [comment]
It looks like there's another instance of this same syntax slightly later in the file that also needs to be fixed.

**Comment by lieser** [comment]
fixed it.

But in `59.0a1 (2017-12-18) (32-bit)` I still have the problem that it complains about missing default options, although https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57 states this was fixed in "Daily 59 as of 2017-12-12".

**Comment by jikamens** [comment]
I think that page is mistaken. I'm using the 2017-12-14 Thunderbird build and default preferences still aren't being loaded. Note that there is still a very active discussion in [bug 1414398](https://bugzilla.mozilla.org/show_bug.cgi?id=1414398) about how to restore the functionality of loading default preferences.

If you wish, you may want to add code to your add-on to load your default preferences manually rather than relying on Thunderbird to do it. This is what I've ended up doing for all the add-ons I maintain. See e.g. https://github.com/jikamens/folder-pane-view-switcher/commit/050ffbdca2b6821862bb399a3be7082baf141faa. Feel free to steal my code (which I derived from code I stole (with attribution) from somebody else.

**Comment by lieser** [comment]
Thanks a lot for letting me know about the workaround. Don't know if and when I will include it (hoping they are able to fix it on the Thunderbird side soon)
